#!/usr/bin/env python3

from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[5]
BOOTSTRAP = ROOT / "tools/cbg/adapters/cbp/helpers/bootstrap_cbg_manifest_from_git.py"
LOCATION_OUTPUT = "main_menu/common/static_modifiers/cbp_location.txt"
BUILDING_OUTPUT = (
    "packages/cbp_economy_rebalance/in_game/common/building_types/"
    "cbp_production_saltpeter.txt"
)
LEGACY_BUILDING_OUTPUT = (
    "packages/cbp_economy_rebalance/in_game/common/building_types/"
    "production_saltpeter.txt"
)
SPEC_MARKER = "# Generated by fixture-spec."


class CbpManifestBootstrapTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.repo = Path(self.temp.name)
        subprocess.run(["git", "init", "-q"], cwd=self.repo, check=True)
        self.output = self.repo / "package/in_game/common/example.txt"
        self.output.parent.mkdir(parents=True)
        self.output.write_text("tracked generated output\n")
        self.spec = self.repo / "spec.json"
        self.write_standard_spec()
        subprocess.run(["git", "add", "."], cwd=self.repo, check=True)
        subprocess.run(
            [
                "git",
                "-c",
                "user.name=CBG Test",
                "-c",
                "user.email=cbg@example.invalid",
                "commit",
                "-qm",
                "fixture",
            ],
            cwd=self.repo,
            check=True,
        )
        self.manifest = self.repo / "manifest.json"

    def tearDown(self) -> None:
        self.temp.cleanup()

    def write_standard_spec(self) -> None:
        self.spec.write_text(json.dumps({"transformations": [{
            "file": "in_game/common/example.txt",
            "object": "example",
            "field": "value",
            "operation": "replace",
            "value": 1,
            "header": [SPEC_MARKER],
        }]}))

    def write_replace_spec(self) -> None:
        self.spec.write_text(json.dumps({"transformations": [{
            "file": "in_game/common/example.txt",
            "object": "example",
            "field": "value",
            "operation": "replace",
            "value": 1,
            "render_mode": "replace_objects",
            "header": [SPEC_MARKER],
        }]}))

    def run_bootstrap(self, *extra: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                "python3", str(BOOTSTRAP),
                "--spec", str(self.spec),
                "--output-root", str(self.repo / "package"),
                "--manifest", str(self.manifest),
                *extra,
            ],
            cwd=self.repo,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )

    def untrack_output(self) -> None:
        subprocess.run(
            ["git", "rm", "-q", str(self.output.relative_to(self.repo))],
            cwd=self.repo,
            check=True,
        )
        subprocess.run(
            [
                "git",
                "-c",
                "user.name=CBG Test",
                "-c",
                "user.email=cbg@example.invalid",
                "commit",
                "-qm",
                "untrack output",
            ],
            cwd=self.repo,
            check=True,
        )
        self.output.parent.mkdir(parents=True, exist_ok=True)

    def test_bootstraps_clean_tracked_output(self) -> None:
        result = self.run_bootstrap()
        self.assertEqual(0, result.returncode, result.stdout)
        payload = json.loads(self.manifest.read_text())
        self.assertEqual("community_balance_generator", payload["generator"])
        self.assertEqual("in_game/common/example.txt", payload["files"][0]["path"])

    def test_refuses_locally_modified_output(self) -> None:
        self.output.write_text("locally modified\n")
        result = self.run_bootstrap()
        self.assertNotEqual(0, result.returncode)
        self.assertIn("locally modified output", result.stdout)

    def test_reconciles_stale_manifest_when_output_is_clean_at_head(self) -> None:
        self.manifest.write_text(json.dumps({
            "schema_version": 1,
            "generator": "community_balance_generator",
            "files": [{
                "path": "in_game/common/example.txt",
                "generated_sha256": "stale-checksum",
                "transformations": [],
            }],
        }))

        result = self.run_bootstrap()

        self.assertEqual(0, result.returncode, result.stdout)
        payload = json.loads(self.manifest.read_text())
        self.assertNotEqual("stale-checksum", payload["files"][0]["generated_sha256"])

    def test_adopts_only_explicitly_signed_output_in_declared_tree(self) -> None:
        self.untrack_output()
        marker = "# Generated by legacy-generator."
        self.output.write_text(marker + "\ngenerated output\n")

        result = self.run_bootstrap(
            "--adopt-marked-output-tree", "in_game/common",
            "--adopt-output-marker", marker,
        )

        self.assertEqual(0, result.returncode, result.stdout)
        payload = json.loads(self.manifest.read_text())
        self.assertEqual(
            "signed_legacy_output",
            payload["files"][0]["transformations"][0]["bootstrap"],
        )

    def test_adopts_untracked_output_signed_by_its_spec_header(self) -> None:
        self.untrack_output()
        self.output.write_text(SPEC_MARKER + "\ngenerated output\n")

        result = self.run_bootstrap()

        self.assertEqual(0, result.returncode, result.stdout)
        payload = json.loads(self.manifest.read_text())
        self.assertEqual(
            "spec_signed_untracked_output",
            payload["files"][0]["transformations"][0]["bootstrap"],
        )

    def test_rejects_untracked_output_without_spec_header(self) -> None:
        self.untrack_output()
        self.output.write_text("# Hand-written file.\ngenerated output\n")

        result = self.run_bootstrap()

        self.assertNotEqual(0, result.returncode)
        self.assertIn("refusing untracked output not owned", result.stdout)

    def test_discovers_tracked_legacy_output_from_replace_rule_without_manifest(self) -> None:
        self.write_replace_spec()

        result = self.run_bootstrap()

        self.assertEqual(0, result.returncode, result.stdout)
        payload = json.loads(self.manifest.read_text())
        self.assertEqual(["in_game/common/example.txt"], [entry["path"] for entry in payload["files"]])
        self.assertEqual(
            "clean_git_tracked_legacy_output",
            payload["files"][0]["transformations"][0]["bootstrap"],
        )

    def test_refuses_modified_tracked_legacy_output_from_replace_rule(self) -> None:
        self.write_replace_spec()
        self.output.write_text("locally modified legacy output\n")

        result = self.run_bootstrap()

        self.assertNotEqual(0, result.returncode)
        self.assertIn("locally modified legacy output", result.stdout)

    def test_adopts_signed_untracked_legacy_output_from_replace_rule(self) -> None:
        self.write_replace_spec()
        self.untrack_output()
        marker = "# Generated by legacy-generator."
        self.output.write_text(marker + "\ngenerated legacy output\n")

        result = self.run_bootstrap(
            "--adopt-marked-output-tree", "in_game/common",
            "--adopt-output-marker", marker,
        )

        self.assertEqual(0, result.returncode, result.stdout)
        payload = json.loads(self.manifest.read_text())
        self.assertEqual("in_game/common/example.txt", payload["files"][0]["path"])
        self.assertEqual(
            "signed_legacy_output",
            payload["files"][0]["transformations"][0]["bootstrap"],
        )

    def test_vanilla_derived_outputs_are_ignored_and_not_tracked(self) -> None:
        for generated in (LOCATION_OUTPUT, BUILDING_OUTPUT):
            ignored = subprocess.run(
                ["git", "check-ignore", "--quiet", generated],
                cwd=ROOT,
                check=False,
            )
            self.assertEqual(0, ignored.returncode, generated)

        for generated in (LOCATION_OUTPUT, BUILDING_OUTPUT, LEGACY_BUILDING_OUTPUT):
            tracked = subprocess.run(
                ["git", "ls-files", "--error-unmatch", generated],
                cwd=ROOT,
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            self.assertNotEqual(0, tracked.returncode, generated)


if __name__ == "__main__":
    unittest.main()
