#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=tools/modeu5_goods.sh
source "$repo_root/tools/modeu5_goods.sh"
goods=("${modeu5_goods[@]}")

table_output="${1:-$repo_root/in_game/gui/modeu5_us10_stock_table.gui}"
market_production_output="${2:-$repo_root/in_game/common/scripted_effects/modeu5_us10_ui_market_production_effects.txt}"

mkdir -p "$(dirname "$table_output")" "$(dirname "$market_production_output")"

write_stock_table() {
	cat <<'TXT'
# Generated by tools/generate_us10_ui_helpers.sh.
# Do not edit manually.
#
# ModeU5 US-10 reusable stock table templates.
#
# Kept separate from the Plan A mounting point so the table can be reused if
# Plan B later generates a full production_lateralview.gui override.
#
# US-10 spec columns:
# Good | Country Stocks | Market Stocks | Overproduction | Production Efficiency
#
# Row visibility is generated for every ModeU5 stock good from tools/modeu5_goods.sh
# and is based on selected-market production, not stored-stock presence.

template modeu5_us10_stock_header_cell_good {
	layoutpolicy_horizontal = fixed
	minimumsize = { 38 22 }
	maximumsize = { 38 22 }
	autoresize = no
	align = center|nobaseline
	fontsize = 11
	default_format = "#bold"
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_header_cell_stock {
	layoutpolicy_horizontal = fixed
	minimumsize = { 84 22 }
	maximumsize = { 84 22 }
	autoresize = no
	align = right|nobaseline
	fontsize = 11
	default_format = "#bold"
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_header_cell_overproduction {
	layoutpolicy_horizontal = fixed
	minimumsize = { 74 22 }
	maximumsize = { 74 22 }
	autoresize = no
	align = right|nobaseline
	fontsize = 11
	default_format = "#bold"
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_header_cell_efficiency {
	layoutpolicy_horizontal = fixed
	minimumsize = { 62 22 }
	maximumsize = { 62 22 }
	autoresize = no
	align = right|nobaseline
	fontsize = 11
	default_format = "#bold"
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_value_cell_stock {
	layoutpolicy_horizontal = fixed
	minimumsize = { 84 22 }
	maximumsize = { 84 22 }
	autoresize = no
	align = right|nobaseline
	fontsize = 12
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_value_cell_overproduction {
	layoutpolicy_horizontal = fixed
	minimumsize = { 74 22 }
	maximumsize = { 74 22 }
	autoresize = no
	align = right|nobaseline
	fontsize = 12
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_value_cell_efficiency {
	layoutpolicy_horizontal = fixed
	minimumsize = { 62 22 }
	maximumsize = { 62 22 }
	autoresize = no
	align = right|nobaseline
	fontsize = 12
	block "text" { raw_text = "" }
}

template modeu5_us10_stock_good_icon_cell {
	layoutpolicy_horizontal = fixed
	minimumsize = { 38 24 }
	maximumsize = { 38 24 }

	icon = {
		parentanchor = center
		size = { 22 22 }
		texture = "gfx/interface/icons/trade_goods/icon_goods_wheat.dds"
		texture_density = 2
	}
}

template modeu5_us10_stock_row {
	layoutpolicy_horizontal = fixed
	layoutpolicy_vertical = fixed
	minimumsize = { 370 26 }
	maximumsize = { 370 26 }
	spacing = 4

	block "good" {
		widget = {
			using = modeu5_us10_stock_good_icon_cell
		}
	}
	block "country_stocks" { text_single = { using = modeu5_us10_stock_value_cell_stock } }
	block "market_stocks" { text_single = { using = modeu5_us10_stock_value_cell_stock } }
	block "overproduction" { text_single = { using = modeu5_us10_stock_value_cell_overproduction } }
	block "production_efficiency" { text_single = { using = modeu5_us10_stock_value_cell_efficiency } }
}

template modeu5_us10_stock_table {
	layoutpolicy_horizontal = expanding
	layoutpolicy_vertical = expanding
	using = bg_window_default_alt

	vbox = {
		layoutpolicy_horizontal = expanding
		layoutpolicy_vertical = expanding
		margin = { 8 8 }
		spacing = 5

		hbox = {
			layoutpolicy_horizontal = fixed
			layoutpolicy_vertical = fixed
			minimumsize = { 370 24 }
			maximumsize = { 370 24 }
			spacing = 4
			text_single = { using = modeu5_us10_stock_header_cell_good blockoverride "text" { raw_text = "Good" } }
			text_single = { using = modeu5_us10_stock_header_cell_stock blockoverride "text" { raw_text = "Country" } }
			text_single = { using = modeu5_us10_stock_header_cell_stock blockoverride "text" { raw_text = "Market" } }
			text_single = { using = modeu5_us10_stock_header_cell_overproduction blockoverride "text" { raw_text = "Overprod." } }
			text_single = { using = modeu5_us10_stock_header_cell_efficiency blockoverride "text" { raw_text = "Eff." } }
		}

		scrollarea = {
			using = layoutpolicy_expanding
			scrollbarpolicy_horizontal = always_off
			autoresizescrollarea = no

			scrollbar_vertical = { using = Scrollbar_Vertical }

			scrollwidget = {
				vbox = {
					layoutpolicy_horizontal = fixed
					set_parent_dimension_to_minimum = height
					spacing = 2
TXT

	for good in "${goods[@]}"; do
		cat <<TXT

					hbox = {
						using = modeu5_us10_stock_row
						visible = "[GreaterThan_CFixedPoint(Player.MakeScope.GetVariable('modeu5_us10_ui_${good}_produced_by_market').GetValue, '(CFixedPoint)0')]"
						blockoverride "good" { widget = { using = modeu5_us10_stock_good_icon_cell icon = { parentanchor = center size = { 22 22 } texture = "gfx/interface/icons/trade_goods/icon_goods_${good}.dds" texture_density = 2 } } }
						blockoverride "country_stocks" { text_single = { using = modeu5_us10_stock_value_cell_stock blockoverride "text" { raw_text = "[Player.MakeScope.GetVariable('modeu5_us10_ui_${good}_country_stock').GetValue|2]/[Player.MakeScope.GetVariable('modeu5_us10_ui_${good}_country_capacity').GetValue|2]" } } }
						blockoverride "market_stocks" { text_single = { using = modeu5_us10_stock_value_cell_stock blockoverride "text" { raw_text = "[Player.MakeScope.GetVariable('modeu5_us10_ui_${good}_market_stock').GetValue|2]/[Player.MakeScope.GetVariable('modeu5_us10_ui_${good}_market_capacity').GetValue|2]" } } }
						blockoverride "overproduction" { text_single = { using = modeu5_us10_stock_value_cell_overproduction blockoverride "text" { raw_text = "[Player.MakeScope.GetVariable('modeu5_us10_ui_${good}_overproduction_percent').GetValue|2]%" } } }
						blockoverride "production_efficiency" { text_single = { using = modeu5_us10_stock_value_cell_efficiency blockoverride "text" { raw_text = "n/a" } } }
					}
TXT
	done

	cat <<'TXT'
				}
			}
		}
	}
}
TXT
}

write_market_production_effects() {
	cat <<'TXT'
# Generated by tools/generate_us10_ui_helpers.sh.
# Do not edit manually.
#
# ModeU5 US-10 UI market-production row visibility helpers.
#
# The Production-hosted stock table should not decide row visibility from stored
# stock. Stock can exist in a market because it was imported, cached, or left from
# a previous cycle. For the Production UI, rows should normally be visible when
# the selected market produced that good in the ModeU5 US-00 ledger.

modeu5_us10_ui_clear_market_produced_row = {
	remove_variable = modeu5_us10_ui_$key$_produced_by_market
}

modeu5_us10_ui_clear_all_market_produced_rows = {
TXT

	for good in "${goods[@]}"; do
		printf '\tmodeu5_us10_ui_clear_market_produced_row = { key = %s }\n' "$good"
	done

	cat <<'TXT'
}

modeu5_us10_ui_capture_market_produced_row = {
	scope:modeu5_us10_ui_country = {
		set_local_variable = { name = modeu5_us10_ui_$key$_produced_by_market_accumulator value = 0 }
	}

	if = {
		limit = { has_global_variable_list = modeu5_countries_present_in_market }
		every_in_global_list = {
			variable = modeu5_countries_present_in_market
			save_temporary_scope_as = modeu5_us10_ui_market_country

			modeu5_read_void_economy_record = {
				country = scope:modeu5_us10_ui_market_country
				market = scope:modeu5_us10_ui_selected_market_scope
				good = $good$
			}

			scope:modeu5_us10_ui_country = {
				change_local_variable = {
					name = modeu5_us10_ui_$key$_produced_by_market_accumulator
					add = scope:modeu5_us00_produced
				}
			}
		}
	}

	scope:modeu5_us10_ui_country = {
		save_temporary_scope_value_as = {
			name = modeu5_us10_ui_$key$_produced_by_market_value
			value = local_var:modeu5_us10_ui_$key$_produced_by_market_accumulator
		}
		set_variable = { name = modeu5_us10_ui_$key$_produced_by_market value = scope:modeu5_us10_ui_$key$_produced_by_market_value }
	}
}

modeu5_us10_ui_capture_all_market_produced_rows = {
TXT

	for good in "${goods[@]}"; do
		printf '\tmodeu5_us10_ui_capture_market_produced_row = { good = %s key = %s }\n' "$good" "$good"
	done

	cat <<'TXT'
}

modeu5_us10_ui_capture_selected_market_produced_by_market = {
	save_temporary_scope_as = modeu5_us10_ui_country
	modeu5_us10_ui_clear_all_market_produced_rows = yes

	if = {
		limit = { has_global_variable_list = modeu5_us10_ui_selected_market }
		every_in_global_list = {
			variable = modeu5_us10_ui_selected_market
			save_temporary_scope_as = modeu5_us10_ui_selected_market_scope
			scope:modeu5_us10_ui_selected_market_scope = { save_temporary_scope_as = modeu5_market_country_cache_market }
			modeu5_rebuild_countries_present_in_market = yes
			modeu5_us10_ui_capture_all_market_produced_rows = yes
		}
	}
}

modeu5_us10_ui_prepare_current_market_table_for_production_ui = {
	modeu5_us10_ui_prepare_current_market_table = yes
	modeu5_us10_ui_capture_selected_market_produced_by_market = yes
}
TXT
}

write_stock_table > "$table_output"
write_market_production_effects > "$market_production_output"
