#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=tools/cbp_goods.sh
source "$repo_root/tools/cbp_goods.sh"

output="$repo_root/packages/cbp_economy_rebalance/in_game/common/modifiers/cbp_us04_local_pop_demand_modifiers_generated.txt"
mkdir -p "$(dirname "$output")"

{
	cat <<'HEADER'
# Generated by tools/generate_us04_local_pop_demand_modifiers.sh.
# Do not edit by hand.
#
# US-04 / Q12 probe modifiers for the EU5 1.3 beta local_pop_demands surface.
#
# The all-goods modifier below targets the documented broad key:
#   local_pop_demands
#
# The per-good modifiers are intentionally probes. They test whether the engine
# exposes a generated per-good modifier key family:
#   local_<good>_pop_demands
#
# If the per-good keys are rejected by the parser, only the broad all-goods
# location modifier exists and US-04 still needs a proper Pop × good endpoint.

HEADER

	cat <<'ALL_GOODS'
cbp_us04_local_pop_demands_all_goods_probe_modifier = {
	local_pop_demands = 1
}

ALL_GOODS

	for good in "${cbp_goods[@]}"; do
		printf 'cbp_us04_local_%s_pop_demands_probe_modifier = {\n' "$good"
		printf '\tlocal_%s_pop_demands = 1\n' "$good"
		printf '}\n\n'
	done
} > "$output"

printf 'Generated %s US-04 per-good local Pop-demand probe modifiers plus one all-goods probe.\n' "${#cbp_goods[@]}"
printf 'Output: %s\n' "$output"
