#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_local_config

bash "$repo_root/tools/generate_local_runtime_config.sh"
"$repo_root/tools/generate_stock_good_helpers.sh"
python3 "$repo_root/tools/postprocess_perf14_promotion_guards.py" "$repo_root/in_game/common/scripted_effects/modeu5_stock_goods_generated.txt"
python3 "$repo_root/tools/postprocess_perf14_overmaterialized_repair.py" \
	"$repo_root/in_game/common/scripted_effects/modeu5_stock_goods_generated.txt" \
	"$repo_root/packages/modeu5_core_tests/in_game/common/scripted_effects/modeu5_perf14_guarded_test_effects.txt" \
	"$repo_root/packages/modeu5_core_tests/in_game/common/scripted_effects/modeu5_perf14_test_effects.txt"
bash "$repo_root/tools/generate_pr71_active_good_dispatch_helpers.sh"
"$repo_root/tools/generate_good_transport_helpers.sh"
bash "$repo_root/tools/generate_us10_ui_helpers.sh"
bash "$repo_root/tools/generate_us20_promoted_destination_receipt_dispatchers.sh"

us09_enabled="${MODEU5_ENABLE_US09_STATIC_OVERRIDES:-true}"
defines_output="$repo_root/loading_screen/common/defines/00_defines.txt"

remove_generated_defines_override() {
	if [[ -f "$defines_output" ]] && \
		head -n 1 "$defines_output" | grep -qx '# Generated by tools/generate_modeu5_defines_override.sh.'
	then
		rm -f "$defines_output"
		printf 'Removed stale generated defines override: %s\n' "$defines_output"
	fi
}

if [[ "$us09_enabled" == "false" || "$us09_enabled" == "0" ]]; then
	printf '%s\n' 'Skipping US-09 static file generation; MODEU5_ENABLE_US09_STATIC_OVERRIDES=false.'
	remove_generated_defines_override
else
	if [[ -x "$repo_root/tools/generate_us09_economy_overrides.sh" || -f "$repo_root/tools/generate_us09_economy_overrides.sh" ]]; then
		if [[ -n "${EU5_GAME_COMMON_DIR:-}" ]]; then
			bash "$repo_root/tools/generate_us09_economy_overrides.sh" \
				"${MODEU5_US09_BONUS_PERCENT:-5}" \
				--extra-burgher-promotion-speed "${EXTRA_BURGHER_PROMOTION_SPEED:-10}" \
				--extra-laborer-promotion-speed "${EXTRA_LABORER_PROMOTION_SPEED:-10}" \
				--package-common-dir "$repo_root/packages/modeu5_economy_rebalance/in_game/common"
		else
			printf '%s\n' 'Skipping US-09 static common-file generation; set EU5_GAME_COMMON_DIR to vanilla game/in_game/common.'
		fi
	fi

	if [[ -n "${EU5_GAME_DEFINES_FILE:-}" || -n "${EU5_GAME_COMMON_DIR:-}" || -n "${EU5_INSTALL_DIR:-}" ]]; then
		bash "$repo_root/tools/generate_modeu5_defines_override.sh" \
			--output-file "$defines_output"
	else
		printf '%s\n' 'Skipping complete defines generation; configure EU5_GAME_DEFINES_FILE, EU5_GAME_COMMON_DIR, or EU5_INSTALL_DIR.'
		remove_generated_defines_override
	fi
fi
