#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=tools/cbp_tool_lib.sh
source "$repo_root/tools/cbp_tool_lib.sh"
cbp_load_local_config

if [[ -n "${EU5_GAME_LOCATION_STATIC_MODIFIERS_FILE:-}" || -n "${EU5_GAME_COMMON_DIR:-}" ]]; then
	bash "$repo_root/tools/generate_cbp_location_overrides.sh"
else
	printf '%s\n' 'Skipping CBP location static-modifier generation; configure EU5_GAME_LOCATION_STATIC_MODIFIERS_FILE or EU5_GAME_COMMON_DIR.'
fi

# Remove artifacts produced by the abandoned exact-path vanilla Pop-demand
# generator. Leaving either file in a working tree would reintroduce an override
# or duplicate the tracked injection script value during local installation.
obsolete_us04_override="$repo_root/packages/cbp_economy_rebalance/in_game/common/goods_demand/pop_demands.txt"
obsolete_us04_values="$repo_root/packages/cbp_economy_rebalance/in_game/common/script_values/cbp_us04_pop_demand_values_generated.txt"
if [[ -f "$obsolete_us04_override" || -f "$obsolete_us04_values" ]]; then
	rm -f "$obsolete_us04_override" "$obsolete_us04_values"
	printf '%s\n' 'Removed obsolete generated US-04 Pop-demand override artifacts.'
fi

bash "$repo_root/tools/generate_local_runtime_config.sh"
"$repo_root/tools/generate_stock_good_helpers.sh"
python3 "$repo_root/tools/postprocess_perf14_promotion_guards.py" "$repo_root/in_game/common/scripted_effects/cbp_stock_goods_generated.txt"
python3 "$repo_root/tools/postprocess_perf14_overmaterialized_repair.py" \
	"$repo_root/in_game/common/scripted_effects/cbp_stock_goods_generated.txt" \
	"$repo_root/packages/cbp_core_tests/in_game/common/scripted_effects/cbp_perf14_guarded_test_effects.txt" \
	"$repo_root/packages/cbp_core_tests/in_game/common/scripted_effects/cbp_perf14_test_effects.txt"
bash "$repo_root/tools/generate_pr71_active_good_dispatch_helpers.sh"
"$repo_root/tools/generate_us04_pop_demand_helpers.sh"
bash "$repo_root/tools/generate_us04_local_pop_demand_modifiers.sh"
python3 "$repo_root/tools/validate_us04_pop_demand_architecture.py"

"$repo_root/tools/generate_good_transport_helpers.sh"
bash "$repo_root/tools/generate_us10_ui_helpers.sh"
bash "$repo_root/tools/generate_us20_promoted_destination_receipt_dispatchers.sh"

us09_enabled="${MODEU5_ENABLE_US09_STATIC_OVERRIDES:-true}"
defines_output="$repo_root/loading_screen/common/defines/00_defines.txt"

remove_generated_defines_override() {
	if [[ -f "$defines_output" ]] && \
		head -n 1 "$defines_output" | grep -qx '# Generated by tools/generate_cbp_defines_override.sh.'
	then
		rm -f "$defines_output"
		printf 'Removed stale generated defines override: %s\n' "$defines_output"
	fi
}

if [[ "$us09_enabled" == "false" || "$us09_enabled" == "0" ]]; then
	printf '%s\n' 'Skipping US-09 static file generation; MODEU5_ENABLE_US09_STATIC_OVERRIDES=false.'
	remove_generated_defines_override
else
	if [[ -x "$repo_root/tools/generate_us09_economy_overrides.sh" || -f "$repo_root/tools/generate_us09_economy_overrides.sh" ]]; then
		if [[ -n "${EU5_GAME_COMMON_DIR:-}" ]]; then
			bash "$repo_root/tools/generate_us09_economy_overrides.sh" \
				"${MODEU5_US09_BONUS_PERCENT:-5}" \
				--trade-capacity-percent "${MODEU5_US09_TRADE_CAPACITY_BONUS_PERCENT:-15}" \
				--extra-burgher-promotion-speed "${EXTRA_BURGHER_PROMOTION_SPEED:-10}" \
				--extra-laborer-promotion-speed "${EXTRA_LABORER_PROMOTION_SPEED:-10}" \
				--package-common-dir "$repo_root/packages/cbp_economy_rebalance/in_game/common"
		else
			printf '%s\n' 'Skipping US-09 static common-file generation; set EU5_GAME_COMMON_DIR to vanilla game/in_game/common.'
		fi
	fi

	# if [[ -n "${EU5_GAME_DEFINES_FILE:-}" || -n "${EU5_GAME_COMMON_DIR:-}" || -n "${EU5_INSTALL_DIR:-}" ]]; then
	# 	bash "$repo_root/tools/generate_cbp_defines_override.sh" \
	# 		--output-file "$defines_output"
	# else
	# 	printf '%s\n' 'Skipping complete defines generation; configure EU5_GAME_DEFINES_FILE, EU5_GAME_COMMON_DIR, or EU5_INSTALL_DIR.'
	# 	remove_generated_defines_override
	# fi
fi

# US-177 is package-owned independently from US-09. It records the authoritative
# vanilla food-good set, scans the complete vanilla source tree for
# minting_income_factor, and composes building changes with whichever exact-path
# building files are already present.
if [[ -n "${EU5_GAME_COMMON_DIR:-}" ]]; then
	us177_common_dir="${EU5_GAME_COMMON_DIR%/}"
	us177_game_root="${us177_common_dir%/in_game/common}"
	python3 "$repo_root/tools/generate_us177_food_goods_manifest.py" \
		--game-root "$us177_game_root" \
		--package-root "$repo_root/packages/cbp_economy_rebalance" \
		--food-price "${MODEU5_US177_FOOD_PRICE:-0.3}" \
		--food-production-divisor "${MODEU5_US177_FOOD_PRODUCTION_DIVISOR:-3}"
	python3 "$repo_root/tools/generate_us177_minting_overrides.py" \
		--game-root "$us177_game_root" \
		--package-root "$repo_root/packages/cbp_economy_rebalance" \
		--multiplier "${MODEU5_US177_MINTING_MULTIPLIER:-2}"
	python3 "$repo_root/tools/postprocess_us177_minting_building_overrides.py" \
		--common-dir "$us177_common_dir" \
		--package-common-dir "$repo_root/packages/cbp_economy_rebalance/in_game/common" \
		--multiplier "${MODEU5_US177_MINTING_MULTIPLIER:-2}"
else
	printf '%s\n' 'Skipping US-177 source generation; set EU5_GAME_COMMON_DIR to vanilla game/in_game/common.'
fi
