#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
capacity_dispatch_template="$repo_root/tools/templates/cbp_us20_receiver_capacity_dispatch_good.template.txt"
base_receipt_dispatch_template="$repo_root/tools/templates/cbp_us20_base_receipt_dispatch_good.template.txt"
output="${1:-$repo_root/in_game/common/scripted_effects/cbp_us20_promoted_destination_receipt_dispatchers.txt}"

# shellcheck source=tools/cbp_tool_lib.sh
source "$repo_root/tools/cbp_tool_lib.sh"
cbp_load_goods_registry
goods=("${cbp_goods[@]}")

cbp_require_file "$capacity_dispatch_template"
cbp_require_file "$base_receipt_dispatch_template"

mkdir -p "$(dirname "$output")"

{
	cat <<'TXT'
# Generated by tools/generate_us20_promoted_destination_receipt_dispatchers.sh.
# Do not edit manually.
# Literal route-good dispatch is generated from tools/cbp_goods.sh.
#
# Implements BR-27 / BR-28 / BR-30 for all ModeU5 stock goods.
# The dispatcher maps a route-good scope to the literal good token required by
# the central stock operators.

cbp_probe_us20_receiver_capacity_literal_good = {
	cbp_read_country_stock_record = {
		country = scope:cbp_us20_receiver_capacity_probe_country
		market = scope:cbp_trade_owner_target_market
		good = $good$
	}
	save_temporary_scope_value_as = { name = cbp_us20_route_good_matched value = 1 }
	if = {
		limit = { scope:cbp_read_country_stock < scope:cbp_read_country_stock_cap }
		save_temporary_scope_value_as = { name = cbp_us20_receiver_capacity_eligible value = 1 }
	}
}

cbp_apply_us20_promoted_destination_base_receipt_literal_good = {
	if = {
		limit = { scope:cbp_us20_origin_market_is_promoted = 0 }
		cbp_add_stock = {
			country = scope:cbp_us20_goods_loss_target_country
			market = scope:cbp_trade_owner_target_market
			good = $good$
			quantity = scope:gui_cbp_us20_goods_base_receipt_quantity
			capacity_policy = allow_over_capacity
		}
		debug_log = "ModeU5 US20 BASE_RECEIPT applied=add_at_destination capacity_policy=allow_over_capacity"
	}
	else = {
		cbp_transfer_stock = {
			seller_country = scope:cbp_trade_owner_country
			buyer_country = scope:cbp_us20_goods_loss_target_country
			source_market = scope:cbp_trade_owner_source_market
			target_market = scope:cbp_trade_owner_target_market
			good = $good$
			quantity = scope:gui_cbp_us20_goods_base_receipt_quantity
			target_capacity_policy = allow_over_capacity
		}
		debug_log = "ModeU5 US20 BASE_RECEIPT applied=country_market_transfer capacity_policy=allow_over_capacity"
	}
	save_temporary_scope_value_as = { name = cbp_us20_receipt_good_matched value = 1 }
}

cbp_probe_us20_receiver_capacity_by_route_good = {
	save_temporary_scope_value_as = { name = cbp_us20_receiver_capacity_eligible value = 0 }
	save_temporary_scope_value_as = { name = cbp_us20_route_good_matched value = 0 }
	if = {
		limit = { exists = scope:cbp_us20_receiver_capacity_probe_country exists = scope:cbp_trade_owner_target_market exists = scope:cbp_trade_owner_good }
TXT

	for good in "${goods[@]}"; do
		cbp_render_template_to_stdout "$capacity_dispatch_template" "GOOD=$good"
	done

	cat <<'TXT'
	}
	if = { limit = { scope:cbp_us20_route_good_matched = 0 } debug_log = "ModeU5 US20 RECEIVER_CAPACITY_DISPATCH blocked reason=unsupported_route_good current_scope=all_goods_dispatcher" }
}

cbp_apply_us20_promoted_destination_base_receipt_by_route_good = {
	save_temporary_scope_value_as = { name = cbp_us20_receipt_good_matched value = 0 }
	if = {
		limit = { exists = scope:cbp_us20_goods_loss_target_country exists = scope:cbp_trade_owner_target_market exists = scope:cbp_trade_owner_good scope:gui_cbp_us20_goods_base_receipt_quantity > 0 }
TXT

	for good in "${goods[@]}"; do
		cbp_render_template_to_stdout "$base_receipt_dispatch_template" "GOOD=$good"
	done

	cat <<'TXT'
	}
	if = { limit = { scope:cbp_us20_receipt_good_matched = 0 } cbp_note_trade_efficiency_goods_delta_blocked_route = yes debug_log = "ModeU5 US20 BASE_RECEIPT_DISPATCH blocked reason=unsupported_route_good_or_missing_scope current_scope=all_goods_dispatcher" }
}
TXT
} > "$output"
