#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_local_runtime_config_generated.txt}"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_local_config

normalize_bool() {
	local raw="${1:-false}"
	case "$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]')" in
		1|true|yes|y|on)
			printf '%s\n' 'true'
			;;
		0|false|no|n|off|'')
			printf '%s\n' 'false'
			;;
		*)
			printf 'Invalid boolean value for MODEU5_ENABLE_DEBUG_RUNTIME: %s\n' "$raw" >&2
			printf 'Accepted values: true/false, 1/0, yes/no, on/off.\n' >&2
			exit 2
			;;
	esac
}

modeu5_make_parent_dir "$output"

debug_enabled="$(normalize_bool "${MODEU5_ENABLE_DEBUG_RUNTIME:-false}")"

if [[ "$debug_enabled" == "true" ]]; then
	selected_effect='modeu5_enter_debug_runtime_mode = yes'
	selected_label='debug'
else
	selected_effect='modeu5_enter_normal_runtime_mode = yes'
	selected_label='normal'
fi

cat > "$output" <<TXT
# Generated by tools/generate_local_runtime_config.sh.
# Do not edit manually.
#
# Source flag: MODEU5_ENABLE_DEBUG_RUNTIME=${debug_enabled}
# Selected ModeU5 runtime mode: ${selected_label}
#
# This decouples ModeU5 debug runtime from the EU5 engine --debug_mode launch
# argument. Use .modeu5.local.env to choose ModeU5 debug behaviour explicitly.

modeu5_apply_generated_local_runtime_mode = {
	${selected_effect}
}
TXT

printf 'Generated %s with ModeU5 runtime mode: %s\n' "$output" "$selected_label"
