#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_us04_pop_demand_generated.txt}"
template="$repo_root/tools/templates/modeu5_us04_pop_demand_good.template.txt"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_goods_registry
modeu5_require_file "$template"

mkdir -p "$(dirname "$output")"

python3 - "$output" "$template" "${modeu5_goods[@]}" <<'PY'
from pathlib import Path
import re
import sys

output = Path(sys.argv[1])
template = Path(sys.argv[2]).read_text(encoding="utf-8")
goods = sys.argv[3:]


def render_good(good: str) -> str:
    rendered = template.replace("__GOOD__", good)
    unresolved = sorted(set(re.findall(r"__[A-Z0-9_]+__", rendered)))
    if unresolved:
        raise SystemExit(
            "Unresolved placeholders in US-04 pop demand template: "
            + ", ".join(unresolved)
        )
    return rendered.rstrip()


lines: list[str] = [
    "# Generated by tools/generate_us04_pop_demand_helpers.sh.",
    "# Do not edit manually.",
    "# US-04 local Pop demand adaptation helpers.",
    "# Location scope: maps are keyed by goods scope.",
    "",
]

for good in goods:
    lines.extend([render_good(good), ""])

lines.extend(
    [
        "modeu5_annual_adjust_location_pop_demand_all_goods = {",
    ]
)
for good in goods:
    lines.append(f"\tmodeu5_annual_adjust_location_pop_demand_good_{good} = yes")
lines.extend(["}", ""])

lines.extend(
    [
        "modeu5_reset_pop_demand_annual_counters_all_goods = {",
    ]
)
for good in goods:
    lines.append(f"\tmodeu5_reset_pop_demand_annual_counters_good_{good} = yes")
lines.extend(["}", ""])

output.write_text("\n".join(lines), encoding="utf-8")
PY
