#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_us04_pop_demand_generated.txt}"
template="$repo_root/tools/templates/modeu5_us04_pop_demand_good.template.txt"
stock_generated="$repo_root/in_game/common/scripted_effects/modeu5_stock_goods_generated.txt"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_goods_registry
modeu5_require_file "$template"

mkdir -p "$(dirname "$output")"

python3 - "$output" "$template" "$stock_generated" "${modeu5_goods[@]}" <<'PY'
from collections import Counter
from pathlib import Path
import re
import sys

output = Path(sys.argv[1])
template = Path(sys.argv[2]).read_text(encoding="utf-8")
stock_generated = Path(sys.argv[3])
goods = sys.argv[4:]


def render_good(good: str) -> str:
    rendered = template.replace("__GOOD__", good)
    unresolved = sorted(set(re.findall(r"__[A-Z0-9_]+__", rendered)))
    if unresolved:
        raise SystemExit(
            "Unresolved placeholders in US-04 pop demand template: "
            + ", ".join(unresolved)
        )
    return rendered.rstrip()


def assert_balanced_braces(text: str, label: str) -> None:
    depth = 0
    in_string = False
    escaped = False
    for line_number, line in enumerate(text.splitlines(), start=1):
        for char in line:
            if not in_string and char == "#":
                break
            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    in_string = False
                continue
            if char == '"':
                in_string = True
            elif char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth < 0:
                    raise SystemExit(
                        f"{label} has an unexpected closing brace at line {line_number}"
                    )
    if in_string:
        raise SystemExit(f"{label} has an unclosed quoted string")
    if depth != 0:
        raise SystemExit(f"{label} has {depth} unclosed opening brace(s)")


def top_level_effect_names(text: str) -> list[str]:
    return re.findall(r"^([a-zA-Z0-9_]+)\s*=\s*\{\s*$", text, re.M)


lines: list[str] = [
    "# Generated by tools/generate_us04_pop_demand_helpers.sh.",
    "# Do not edit manually.",
    "# US-04 local Pop demand adaptation helpers.",
    "# Location scope: maps are keyed by goods scope.",
    "",
]

for good in goods:
    lines.extend([render_good(good), ""])

lines.extend(
    [
        "modeu5_initialize_pop_demand_multiplier_all_goods = {",
    ]
)
for good in goods:
    lines.append(f"\tmodeu5_initialize_pop_demand_multiplier_good_{good} = yes")
lines.extend(["}", ""])

lines.extend(
    [
        "modeu5_annual_adjust_location_pop_demand_all_goods = {",
    ]
)
for good in goods:
    lines.append(f"\tmodeu5_annual_adjust_location_pop_demand_good_{good} = yes")
lines.extend(["}", ""])

lines.extend(
    [
        "modeu5_reset_pop_demand_annual_counters_all_goods = {",
    ]
)
for good in goods:
    lines.append(f"\tmodeu5_us04_reset_pop_demand_annual_counters_good_{good} = yes")
lines.extend(["}", ""])

generated = "\n".join(lines)
assert_balanced_braces(generated, "Generated US-04 Pop-demand helpers")

names = top_level_effect_names(generated)
duplicates = sorted(name for name, count in Counter(names).items() if count > 1)
if duplicates:
    raise SystemExit(
        "Generated US-04 Pop-demand helpers contain duplicate top-level keys: "
        + ", ".join(duplicates)
    )

if stock_generated.is_file():
    stock_names = set(top_level_effect_names(stock_generated.read_text(encoding="utf-8")))
    collisions = sorted(set(names) & stock_names)
    if collisions:
        raise SystemExit(
            "Generated US-04 Pop-demand helpers collide with stock-generated keys: "
            + ", ".join(collisions)
        )

nested_map_value = re.compile(
    r"add_to_variable_map\s*=\s*\{(?:(?!\n\}).)*?\bvalue\s*=\s*\{",
    re.S,
)
if nested_map_value.search(generated):
    raise SystemExit(
        "Generated US-04 Pop-demand helpers must precompute arithmetic before "
        "add_to_variable_map; nested value blocks are not accepted by EU5 runtime"
    )

output.write_text(generated, encoding="utf-8")
PY
