#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$repo_root/in_game/common/scripted_effects/zz_modeu5_pr71_active_good_dispatch_generated.txt}"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_goods_registry
goods=("${modeu5_goods[@]}")

mkdir -p "$(dirname "$output")"

{
	cat <<'TXT'
# Generated by tools/generate_pr71_active_good_dispatch_helpers.sh.
# Do not edit manually.
#
# PR126 PR7.1 active-good dispatch guards.
#
# This file preserves PR7's promoted-market ownership shape while avoiding the
# expensive generated all-good helper body when the existing main-branch
# business gate says the good has no work.
#
# Important: the generated per-good symbol surface still exists because EU5
# scripted effect names and map names must remain literal. PR7.1 narrows the
# call into the heavy generated helpers; it does not remove the generated
# helpers from the repository.

modeu5_pr71_reset_active_good_metrics = {
	remove_global_variable = modeu5_pr71_active_good_metrics_stamp
	remove_global_variable = modeu5_pr71_us00_goods_considered
	remove_global_variable = modeu5_pr71_us00_goods_processed
	remove_global_variable = modeu5_pr71_us00_goods_produced_gate_hits
	remove_global_variable = modeu5_pr71_us00_goods_previous_state_hits
	remove_global_variable = modeu5_pr71_us10_goods_considered
	remove_global_variable = modeu5_pr71_us10_requests_processed
	remove_global_variable = modeu5_pr71_us10_pending_request_hits

	set_global_variable = { name = modeu5_pr71_us00_goods_considered value = 0 }
	set_global_variable = { name = modeu5_pr71_us00_goods_processed value = 0 }
	set_global_variable = { name = modeu5_pr71_us00_goods_produced_gate_hits value = 0 }
	set_global_variable = { name = modeu5_pr71_us00_goods_previous_state_hits value = 0 }
	set_global_variable = { name = modeu5_pr71_us10_goods_considered value = 0 }
	set_global_variable = { name = modeu5_pr71_us10_requests_processed value = 0 }
	set_global_variable = { name = modeu5_pr71_us10_pending_request_hits value = 0 }
}

modeu5_pr71_prepare_active_good_metrics = {
	save_temporary_scope_value_as = {
		name = modeu5_pr71_active_good_metrics_stamp
		value = {
			value = current_year
			multiply = 12
			add = current_month
		}
	}

	if = {
		limit = {
			OR = {
				NOT = { has_global_variable = modeu5_pr71_active_good_metrics_stamp }
				global_var:modeu5_pr71_active_good_metrics_stamp != scope:modeu5_pr71_active_good_metrics_stamp
			}
		}
		modeu5_pr71_reset_active_good_metrics = yes
		set_global_variable = { name = modeu5_pr71_active_good_metrics_stamp value = scope:modeu5_pr71_active_good_metrics_stamp }
	}
	else_if = {
		limit = { NOT = { has_global_variable = modeu5_pr71_us00_goods_considered } }
		modeu5_pr71_reset_active_good_metrics = yes
		set_global_variable = { name = modeu5_pr71_active_good_metrics_stamp value = scope:modeu5_pr71_active_good_metrics_stamp }
	}
}

modeu5_pr71_note_us00_goods_considered = {
	set_global_variable = { name = modeu5_pr71_us00_goods_considered value = { value = global_var:modeu5_pr71_us00_goods_considered add = 1 } }
}

modeu5_pr71_note_us00_goods_processed = {
	set_global_variable = { name = modeu5_pr71_us00_goods_processed value = { value = global_var:modeu5_pr71_us00_goods_processed add = 1 } }
}

modeu5_pr71_note_us00_goods_produced_gate_hit = {
	set_global_variable = { name = modeu5_pr71_us00_goods_produced_gate_hits value = { value = global_var:modeu5_pr71_us00_goods_produced_gate_hits add = 1 } }
}

modeu5_pr71_note_us00_goods_previous_state_hit = {
	set_global_variable = { name = modeu5_pr71_us00_goods_previous_state_hits value = { value = global_var:modeu5_pr71_us00_goods_previous_state_hits add = 1 } }
}

modeu5_pr71_note_us10_goods_considered = {
	set_global_variable = { name = modeu5_pr71_us10_goods_considered value = { value = global_var:modeu5_pr71_us10_goods_considered add = 1 } }
}

modeu5_pr71_note_us10_pending_request_hit = {
	set_global_variable = { name = modeu5_pr71_us10_pending_request_hits value = { value = global_var:modeu5_pr71_us10_pending_request_hits add = 1 } }
}

modeu5_pr71_note_us10_request_processed = {
	set_global_variable = { name = modeu5_pr71_us10_requests_processed value = { value = global_var:modeu5_pr71_us10_requests_processed add = 1 } }
}

TXT

	for good in "${goods[@]}"; do
		cat <<TXT
modeu5_pr71_process_us00_monthly_market_good_${good} = {
	modeu5_pr71_note_us00_goods_considered = yes

	scope:modeu5_market = {
		save_temporary_scope_value_as = {
			name = modeu5_pr71_us00_market_produced_gate
			value = {
				value = produced_in_market:${good}
				min = 0
			}
		}
	}

	save_temporary_scope_value_as = { name = modeu5_us00_previous_record_active value = 0 }
	if = {
		limit = { NOT = { scope:modeu5_pr71_us00_market_produced_gate > 0 } }
		modeu5_probe_us00_previous_record_activity_good_${good} = yes
	}

	if = {
		limit = { scope:modeu5_pr71_us00_market_produced_gate > 0 }
		modeu5_pr71_note_us00_goods_produced_gate_hit = yes
	}
	else_if = {
		limit = { scope:modeu5_us00_previous_record_active > 0 }
		modeu5_pr71_note_us00_goods_previous_state_hit = yes
	}

	if = {
		limit = {
			OR = {
				scope:modeu5_pr71_us00_market_produced_gate > 0
				scope:modeu5_us00_previous_record_active > 0
			}
		}
		modeu5_pr71_note_us00_goods_processed = yes
		modeu5_process_us00_monthly_market_good_${good} = yes
	}
}

TXT
	done

	cat <<'TXT'
modeu5_pr71_process_us00_monthly_market_active_goods = {
TXT
	for good in "${goods[@]}"; do
		printf '\tmodeu5_pr71_process_us00_monthly_market_good_%s = yes\n' "$good"
	done
	cat <<'TXT'
}

TXT

	for good in "${goods[@]}"; do
		cat <<TXT
modeu5_pr71_process_us10_monthly_market_good_${good} = {
	modeu5_pr71_note_us10_goods_considered = yes
	save_temporary_scope_value_as = { name = modeu5_pr71_us10_pending_request_quantity value = 0 }

	scope:modeu5_country = {
		if = {
			limit = {
				has_variable_map = modeu5_consumption_${good}_pending_requested_by_market
				is_key_in_variable_map = {
					name = modeu5_consumption_${good}_pending_requested_by_market
					target = scope:modeu5_market
				}
			}
			save_temporary_scope_value_as = {
				name = modeu5_pr71_us10_pending_request_quantity
				value = "variable_map(modeu5_consumption_${good}_pending_requested_by_market|scope:modeu5_market)"
			}
		}
	}

	if = {
		limit = { scope:modeu5_pr71_us10_pending_request_quantity > 0 }
		modeu5_pr71_note_us10_pending_request_hit = yes
		modeu5_pr71_note_us10_request_processed = yes
		modeu5_process_us10_monthly_market_good_${good} = yes
	}
}

TXT
	done

	cat <<'TXT'
modeu5_pr71_process_us10_monthly_market_pending_goods = {
TXT
	for good in "${goods[@]}"; do
		printf '\tmodeu5_pr71_process_us10_monthly_market_good_%s = yes\n' "$good"
	done
	cat <<'TXT'
}

# Override the PR7 live local branch with the PR7.1 guarded dispatch path.
# The name intentionally matches the PR7 effect so the monthly stock cycle keeps
# the same external contract while the inner per-good calls are narrowed.
modeu5_run_promoted_market_live_local_branch_market_all_goods = {
	$country$ = {
		save_temporary_scope_as = modeu5_local_branch_country
		save_temporary_scope_as = modeu5_reconciliation_controller
	}
	$market$ = {
		save_temporary_scope_as = modeu5_market
		save_temporary_scope_as = modeu5_market_country_cache_market
	}

	modeu5_pr71_prepare_active_good_metrics = yes

	modeu5_prepare_promoted_market_country_cache = {
		market = scope:modeu5_market
	}
	modeu5_note_promoted_market_live_country_cache_rebuild = yes

	if = {
		limit = { has_global_variable_list = modeu5_countries_present_in_market }
		every_in_global_list = {
			variable = modeu5_countries_present_in_market
			save_temporary_scope_as = modeu5_promoted_market_capacity_country
			modeu5_prepare_promoted_country_market_capacity = {
				country = scope:modeu5_promoted_market_capacity_country
				market = scope:modeu5_market
			}
			modeu5_note_promoted_market_live_capacity_country = yes
		}

		# Preserve the economic order: all country production/admission and US-00
		# ledgers for the market are updated before any same-market consumption
		# request can scan the market's country stock.
		every_in_global_list = {
			variable = modeu5_countries_present_in_market
			save_temporary_scope_as = modeu5_country
			modeu5_note_promoted_market_live_us00_country_pass = yes
			modeu5_pr71_process_us00_monthly_market_active_goods = yes
		}
		every_in_global_list = {
			variable = modeu5_countries_present_in_market
			save_temporary_scope_as = modeu5_country
			modeu5_note_promoted_market_live_us10_country_pass = yes
			modeu5_pr71_process_us10_monthly_market_pending_goods = yes
		}
	}

	modeu5_note_promoted_market_live_local_market_processed = yes
}
TXT
} > "$output"

printf 'Generated %s\n' "$output"
