#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
local_config="$repo_root/.modeu5.local.env"

if [[ -f "$local_config" ]]; then
	set -a
	# shellcheck source=/dev/null
	source "$local_config"
	set +a
fi

usage() {
	cat <<'EOF'
Usage:
  ./tools/generate_us09_economy_overrides.sh <percent> [options]
  ./tools/generate_us09_economy_overrides.sh --percent <percent> [options]

Options:
  --percent N               Percent increase for building output
  --common-dir PATH         EU5 `game/in_game/common` source directory
  --package-common-dir PATH Output `in_game/common` directory for generated files
  --help                    Show this help text

If no percent is passed and stdin is interactive, the script prompts for one.
Examples:
  ./tools/generate_us09_economy_overrides.sh 5
  ./tools/generate_us09_economy_overrides.sh 10
  ./tools/generate_us09_economy_overrides.sh --percent 7.5

By default, this writes offline probe output under tools/generated/us09_economy_overrides.
Pass --package-common-dir packages/modeu5_economy_rebalance/in_game/common only
for local engine probes; duplicate-key package override loading is not confirmed.
EOF
}

format_decimal() {
	local value="$1"
	local scale="${2:-10}"

	awk -v value="$value" -v scale="$scale" 'BEGIN {
		printf "%.*f", scale, value
	}' | sed -e 's/0\+$//' -e 's/\.$/.0/'
}

source_label() {
	local source_file="$1"
	local relative_source="${source_file#"$common_dir"/}"

	printf '<EU5_GAME_COMMON_DIR>/%s\n' "$relative_source"
}

find_default_common_dir() {
	if [[ -n "${EU5_GAME_COMMON_DIR:-}" && -d "${EU5_GAME_COMMON_DIR:-}" ]]; then
		printf '%s\n' "$EU5_GAME_COMMON_DIR"
		return 0
	fi

	return 1
}

percent=""
common_dir=""
package_common_dir="$repo_root/tools/generated/us09_economy_overrides/common"

while (($# > 0)); do
	case "$1" in
		--percent)
			percent="$2"
			shift 2
			;;
		--common-dir)
			common_dir="$2"
			shift 2
			;;
		--package-common-dir)
			package_common_dir="$2"
			shift 2
			;;
		--help)
			usage
			exit 0
			;;
		-*)
			printf 'Unknown argument: %s\n\n' "$1" >&2
			usage >&2
			exit 1
			;;
		*)
			if [[ -z "$percent" ]]; then
				percent="$1"
				shift
			else
				printf 'Unexpected extra argument: %s\n\n' "$1" >&2
				usage >&2
				exit 1
			fi
			;;
	esac
done

if [[ -z "$percent" ]]; then
	if [[ -t 0 ]]; then
		read -r -p "US-09 percent increase (5 = 5%, 10 = 10%): " percent
	else
		printf 'Missing percent. Pass one explicitly, for example `./tools/generate_us09_economy_overrides.sh 5`.\n' >&2
		exit 1
	fi
fi

if [[ ! "$percent" =~ ^-?[0-9]+([.][0-9]+)?$ ]]; then
	printf 'US-09 percent must be numeric; got %s.\n' "$percent" >&2
	exit 1
fi

if ! awk -v value="$percent" 'BEGIN { exit !(value > -100) }'; then
	printf 'US-09 percent must be greater than -100; got %s.\n' "$percent" >&2
	exit 1
fi

if [[ -z "$common_dir" ]]; then
	if ! common_dir="$(find_default_common_dir)"; then
		printf 'Could not find an EU5 `game/in_game/common` directory. Pass --common-dir or set EU5_GAME_COMMON_DIR.\n' >&2
		exit 1
	fi
fi

building_types_source_dir="$common_dir/building_types"
prices_source_file="$common_dir/prices/00_hardcoded.txt"
building_types_output_dir="$package_common_dir/building_types"
prices_output_dir="$package_common_dir/prices"

if [[ ! -d "$building_types_source_dir" ]]; then
	printf 'Missing source directory: %s\n' "$building_types_source_dir" >&2
	exit 1
fi

if [[ ! -f "$prices_source_file" ]]; then
	printf 'Missing source file: %s\n' "$prices_source_file" >&2
	exit 1
fi

mkdir -p "$building_types_output_dir" "$prices_output_dir"

find "$building_types_output_dir" -maxdepth 1 -type f -name 'zzzz_modeu5_us09_*.txt' -delete
rm -f "$prices_output_dir/zzzz_modeu5_us09_expand_rgo_prices.txt"

output_multiplier="$(awk -v percent="$percent" 'BEGIN { printf "%.12f", 1 + (percent / 100) }')"
rgo_price_multiplier="$(awk -v percent="$percent" 'BEGIN { printf "%.12f", 1 / (1 + (percent / 100)) }')"

generated_building_files=0

while IFS= read -r -d '' source_file; do
	if ! grep -Eq '^[[:space:]]*output[[:space:]]*=' "$source_file"; then
		continue
	fi

	output_file="$building_types_output_dir/zzzz_modeu5_us09_$(basename "$source_file")"

	{
		printf '%s\n' '# Generated by tools/generate_us09_economy_overrides.sh.'
		printf '%s\n' '# Do not edit manually.'
		printf '# Source: %s\n' "$(source_label "$source_file")"
		printf '# Output multiplier: %s (%s%%)\n\n' "$(format_decimal "$output_multiplier")" "$percent"
		MODEU5_US09_OUTPUT_MULTIPLIER="$output_multiplier" \
			perl -pe '
				BEGIN {
					$multiplier = $ENV{"MODEU5_US09_OUTPUT_MULTIPLIER"};
				}

				sub format_decimal {
					my ($value) = @_;
					my $formatted = sprintf("%.10f", $value);
					$formatted =~ s/0+$//;
					$formatted =~ s/\.$/.0/;
					return $formatted;
				}

				if (/^(\s*output\s*=\s*)([0-9]+(?:\.[0-9]+)?)(\s*(?:#.*)?)$/) {
					$_ = $1 . format_decimal($2 * $multiplier) . $3 . "\n";
				}
			' "$source_file"
	} > "$output_file"

	generated_building_files=$((generated_building_files + 1))
done < <(find "$building_types_source_dir" -maxdepth 1 -type f -name '*.txt' -print0 | sort -z)

price_keys=(
	expand_rgo_mining
	expand_rgo_farming
	expand_rgo_hunting
	expand_rgo_gathering
	expand_rgo_forestry
)

prices_output_file="$prices_output_dir/zzzz_modeu5_us09_expand_rgo_prices.txt"

{
	printf '%s\n' '# Generated by tools/generate_us09_economy_overrides.sh.'
	printf '%s\n' '# Do not edit manually.'
	printf '# Source: %s\n' "$(source_label "$prices_source_file")"
	printf '# RGO expansion gold multiplier: %s (inverse of 1 + %s%%)\n\n' "$(format_decimal "$rgo_price_multiplier")" "$percent"

	for price_key in "${price_keys[@]}"; do
		source_gold="$(
			TARGET_PRICE_KEY="$price_key" \
				perl -0ne '
					my $key = $ENV{"TARGET_PRICE_KEY"};
					if (/\b\Q$key\E\s*=\s*\{[^{}]*?\bgold\s*=\s*([0-9]+(?:\.[0-9]+)?)/s) {
						print $1;
						exit 0;
					}
					exit 1;
				' "$prices_source_file"
		)"
		adjusted_gold="$(awk -v gold="$source_gold" -v multiplier="$rgo_price_multiplier" 'BEGIN { printf "%.12f", gold * multiplier }')"

		printf '%s = {\n' "$price_key"
		printf '\tgold = %s\n' "$(format_decimal "$adjusted_gold" 2)"
		printf '}\n\n'
	done
} > "$prices_output_file"

printf 'Generated %d building override files and 1 RGO expansion price override file for US-09 (%s%%).\n' \
	"$generated_building_files" "$percent"
printf 'Output directory: %s\n' "$package_common_dir"
