#!/usr/bin/env python3
"""Export version-tolerant CBG rules for US-09 Pop promotion factors."""

from __future__ import annotations

import argparse
import json
from decimal import Decimal
from pathlib import Path

try:
    from tools.cbg.community_balance_generator import ASSIGNMENT, field_matches, scan_objects
except ModuleNotFoundError:
    from cbg.community_balance_generator import ASSIGNMENT, field_matches, scan_objects


ALIASES = {
    "burgher": "burghers", "burghers": "burghers",
    "laborer": "laborers", "laborers": "laborers",
    "labourer": "laborers", "labourers": "laborers",
}
KNOWN_FIELDS = {
    "promotion", "promote", "promotion_speed", "promotion_speed_modifier",
    "pop_promotion", "pop_promotion_speed", "pop_promotion_speed_modifier",
    "local_pop_promotion_speed", "local_pop_promotion_speed_modifier",
    "local_pop_promotion_speed_scaled", "global_pop_promotion_speed",
    "global_pop_promotion_speed_modifier",
}


def compact(value: Decimal) -> str:
    rendered = f"{value:.10f}".rstrip("0").rstrip(".")
    return rendered if "." in rendered else f"{rendered}.0"


def is_promotion(field: str) -> bool:
    lowered = field.lower()
    return field in KNOWN_FIELDS or "promotion" in lowered or "promote" in lowered


def build_spec(game_root: Path, burgher: Decimal, laborer: Decimal) -> dict[str, object]:
    extras = {"burghers": burgher, "laborers": laborer}
    rules = []
    found: set[str] = set()
    source_root = game_root / "in_game/common/pop_types"
    for source in sorted(source_root.glob("*.txt")):
        lines = source.read_text(encoding="utf-8-sig").splitlines(keepends=True)
        relative = source.relative_to(game_root).as_posix()
        for obj in scan_objects(lines):
            if len(obj.path) != 1 or (target := ALIASES.get(obj.path[0])) is None or extras[target] == 0:
                continue
            matching = []
            for index in range(obj.start + 1, obj.end):
                match = ASSIGNMENT.match(lines[index].rstrip("\r\n"))
                if match and is_promotion(match.group("field")):
                    try:
                        Decimal(match.group("value"))
                    except Exception:
                        continue
                    matching.append(match)
            for match in matching:
                factor = Decimal(1) + extras[target] / Decimal(100)
                header = [
                    "# Generated by tools/generate_us09_economy_overrides.sh.",
                    "# Do not edit manually.",
                    f"# Source: <EU5_GAME_COMMON_DIR>/pop_types/{source.name}",
                ]
                if burgher != 0:
                    header.append(f"# Burgher promotion-speed multiplier: {compact(Decimal(1) + burgher / 100)} (+{compact(burgher)}%)")
                if laborer != 0:
                    header.append(f"# Laborer promotion-speed multiplier: {compact(Decimal(1) + laborer / 100)} (+{compact(laborer)}%)")
                rules.append({
                    "file": relative,
                    "output_file": relative,
                    "render_mode": "normalized_with_header",
                    "header": header,
                    "object": obj.path[0],
                    "field": match.group("field"),
                    "operation": "replace",
                    "value": compact(Decimal(match.group("value")) * factor),
                    "provenance": "preserve",
                })
                found.add(target)
    required = {target for target, extra in extras.items() if extra != 0}
    if found != required:
        raise ValueError(f"Missing Pop promotion targets: {sorted(required - found)}")
    outputs = sorted({rule["output_file"] for rule in rules})
    return {
        "schema_version": 1,
        "mod_id": "cbp-us09-pop-promotion",
        "transformations": rules,
        "scope_contract": {"owned_outputs": outputs, "phase": "pop-promotion"},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--burgher-percent", type=Decimal, required=True)
    parser.add_argument("--laborer-percent", type=Decimal, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(build_spec(args.game_root, args.burgher_percent, args.laborer_percent), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Generated {args.output} with US-09 Pop-promotion CBG policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
