#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
	cat <<'EOF'
Usage:
  ./tools/generate_us09_economy_overrides.sh [options]

Options:
  --percent N               Percent increase for building output. Default: 5
  --common-dir PATH         EU5 `game/in_game/common` source directory
  --package-common-dir PATH Output `in_game/common` directory for generated files
  --help                    Show this help text

Environment:
  MODEU5_US09_PERCENT       Default value for --percent
  EU5_GAME_COMMON_DIR       Default value for --common-dir
EOF
}

format_decimal() {
	awk -v value="$1" 'BEGIN {
		printf "%.10f", value
	}' | sed -e 's/0\+$//' -e 's/\.$/.0/'
}

find_default_common_dir() {
	local candidates=(
		"${EU5_GAME_COMMON_DIR:-}"
		"$HOME/Library/Application Support/CrossOver/Bottles/Steam/drive_c/Program Files (x86)/Steam/steamapps/common/Europa Universalis V/game/in_game/common"
		"$HOME/Library/Application Support/Steam/steamapps/common/Europa Universalis V/game/in_game/common"
	)

	local candidate
	for candidate in "${candidates[@]}"; do
		if [[ -n "$candidate" && -d "$candidate" ]]; then
			printf '%s\n' "$candidate"
			return 0
		fi
	done

	return 1
}

percent="${MODEU5_US09_PERCENT:-5}"
common_dir=""
package_common_dir="$repo_root/packages/modeu5_economy_rebalance/in_game/common"

while (($# > 0)); do
	case "$1" in
		--percent)
			percent="$2"
			shift 2
			;;
		--common-dir)
			common_dir="$2"
			shift 2
			;;
		--package-common-dir)
			package_common_dir="$2"
			shift 2
			;;
		--help)
			usage
			exit 0
			;;
		*)
			printf 'Unknown argument: %s\n\n' "$1" >&2
			usage >&2
			exit 1
			;;
	esac
done

if ! awk -v value="$percent" 'BEGIN { exit !(value > -100) }'; then
	printf 'US-09 percent must be greater than -100; got %s.\n' "$percent" >&2
	exit 1
fi

if [[ -z "$common_dir" ]]; then
	if ! common_dir="$(find_default_common_dir)"; then
		printf 'Could not find an EU5 `game/in_game/common` directory. Pass --common-dir or set EU5_GAME_COMMON_DIR.\n' >&2
		exit 1
	fi
fi

building_types_source_dir="$common_dir/building_types"
prices_source_file="$common_dir/prices/00_hardcoded.txt"
building_types_output_dir="$package_common_dir/building_types"
prices_output_dir="$package_common_dir/prices"

if [[ ! -d "$building_types_source_dir" ]]; then
	printf 'Missing source directory: %s\n' "$building_types_source_dir" >&2
	exit 1
fi

if [[ ! -f "$prices_source_file" ]]; then
	printf 'Missing source file: %s\n' "$prices_source_file" >&2
	exit 1
fi

mkdir -p "$building_types_output_dir" "$prices_output_dir"

find "$building_types_output_dir" -maxdepth 1 -type f -name 'zzzz_modeu5_us09_*.txt' -delete
rm -f "$prices_output_dir/zzzz_modeu5_us09_expand_rgo_prices.txt"

output_multiplier="$(awk -v percent="$percent" 'BEGIN { printf "%.12f", 1 + (percent / 100) }')"
rgo_price_multiplier="$(awk -v percent="$percent" 'BEGIN { printf "%.12f", 1 / (1 + (percent / 100)) }')"

generated_building_files=0

while IFS= read -r -d '' source_file; do
	if ! grep -Eq '^[[:space:]]*output[[:space:]]*=' "$source_file"; then
		continue
	fi

	output_file="$building_types_output_dir/zzzz_modeu5_us09_$(basename "$source_file")"

	{
		printf '%s\n' '# Generated by tools/generate_us09_economy_overrides.sh.'
		printf '%s\n' '# Do not edit manually.'
		printf '# Source: %s\n' "$source_file"
		printf '# Output multiplier: %s (%s%%)\n\n' "$(format_decimal "$output_multiplier")" "$percent"
		MODEU5_US09_OUTPUT_MULTIPLIER="$output_multiplier" \
			perl -pe '
				BEGIN {
					$multiplier = $ENV{"MODEU5_US09_OUTPUT_MULTIPLIER"};
				}

				sub format_decimal {
					my ($value) = @_;
					my $formatted = sprintf("%.10f", $value);
					$formatted =~ s/0+$//;
					$formatted =~ s/\.$/.0/;
					return $formatted;
				}

				if (/^(\s*output\s*=\s*)([0-9]+(?:\.[0-9]+)?)(\s*(?:#.*)?)$/) {
					$_ = $1 . format_decimal($2 * $multiplier) . $3 . "\n";
				}
			' "$source_file"
	} > "$output_file"

	generated_building_files=$((generated_building_files + 1))
done < <(find "$building_types_source_dir" -maxdepth 1 -type f -name '*.txt' -print0 | sort -z)

price_keys=(
	expand_rgo_mining
	expand_rgo_farming
	expand_rgo_hunting
	expand_rgo_gathering
	expand_rgo_forestry
)

prices_output_file="$prices_output_dir/zzzz_modeu5_us09_expand_rgo_prices.txt"

{
	printf '%s\n' '# Generated by tools/generate_us09_economy_overrides.sh.'
	printf '%s\n' '# Do not edit manually.'
	printf '# Source: %s\n' "$prices_source_file"
	printf '# RGO expansion gold multiplier: %s (inverse of 1 + %s%%)\n\n' "$(format_decimal "$rgo_price_multiplier")" "$percent"

	for price_key in "${price_keys[@]}"; do
		source_gold="$(
			TARGET_PRICE_KEY="$price_key" \
				perl -0ne '
					my $key = $ENV{"TARGET_PRICE_KEY"};
					if (/\b\Q$key\E\s*=\s*\{[^{}]*?\bgold\s*=\s*([0-9]+(?:\.[0-9]+)?)/s) {
						print $1;
						exit 0;
					}
					exit 1;
				' "$prices_source_file"
		)"
		adjusted_gold="$(awk -v gold="$source_gold" -v multiplier="$rgo_price_multiplier" 'BEGIN { printf "%.12f", gold * multiplier }')"

		printf '%s = {\n' "$price_key"
		printf '\tgold = %s\n' "$(format_decimal "$adjusted_gold")"
		printf '}\n\n'
	done
} > "$prices_output_file"

printf 'Generated %d building override files and 1 RGO expansion price override file for US-09 (%s%%).\n' \
	"$generated_building_files" "$percent"
