#!/usr/bin/env bash
set -euo pipefail

output="${1:-in_game/common/scripted_effects/modeu5_stock_goods_generated.txt}"

goods=(
	cotton sugar tobacco
	tar porcelain naval_supplies firearms cannons weaponry glass steel cloth
	fine_cloth liquor beer paper books jewelry leather tools masonry
	lacquerware pottery furniture
	horses clay sand coal iron copper goods_gold silver stone tin lead silk
	dyes incense tea cocoa coffee fiber_crops ivory lumber salt medicaments
	gems pearls amber saltpeter alum wine elephants marble mercury saffron
	pepper cloves chili
	wool wild_game fur fish wheat maize rice millet legumes potato livestock
	olives fruit beeswax
	slaves_goods
)

{
	printf '%s\n' '# Generated by tools/generate_stock_good_helpers.sh.'
	printf '%s\n\n' '# Do not edit manually. Goods tokens expand to static per-good map names.'

	first=1
	for good in "${goods[@]}"; do
		if (( first == 0 )); then
			printf '\n'
		fi
		first=0
		printf 'modeu5_add_stock_good_%s = { modeu5_add_stock_for_good = { good = %s } }\n' "$good" "$good"
		printf 'modeu5_remove_stock_good_%s = { modeu5_remove_stock_for_good = { good = %s } }\n' "$good" "$good"
		printf 'modeu5_transfer_stock_good_%s = { modeu5_transfer_stock_for_good = { good = %s } }\n' "$good" "$good"
		printf 'modeu5_decay_stock_good_%s = { modeu5_decay_stock_for_good = { good = %s } }\n' "$good" "$good"
		printf 'modeu5_decay_stock_default_good_%s = { modeu5_decay_stock = { country = scope:modeu5_default_decay_country market = scope:modeu5_default_decay_market good = %s decay_rate = modeu5_default_monthly_decay_rate } }\n' "$good" "$good"
	done
} > "$output"
