#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
template="$repo_root/tools/templates/modeu5_stock_good_adapter.template.txt"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_stock_goods_generated.txt}"

goods=(
	cotton sugar tobacco
	tar porcelain naval_supplies firearms cannons weaponry glass steel cloth
	fine_cloth liquor beer paper books jewelry leather tools masonry
	lacquerware pottery furniture
	horses clay sand coal iron copper goods_gold silver stone tin lead silk
	dyes incense tea cocoa coffee fiber_crops ivory lumber salt medicaments
	gems pearls amber saltpeter alum wine elephants marble mercury saffron
	pepper cloves chili
	wool wild_game fur fish wheat maize rice millet legumes potato livestock
	olives fruit beeswax
	slaves_goods
)

{
	printf '%s\n' '# Generated by tools/generate_stock_good_helpers.sh.'
	printf '%s\n' '# Do not edit manually.'
	printf '%s\n\n' '# Literal map access is generated from tools/templates/modeu5_stock_good_adapter.template.txt.'
	printf '%s\n\n' 'modeu5_validate_dirty_stock_consistency = {'
	printf '%s\n' '	save_temporary_scope_as = modeu5_reconciliation_controller'
	printf '%s\n' '	save_temporary_scope_value_as = { name = modeu5_reconciliation_type value = 1 }'
	printf '%s\n' '	modeu5_reconciliation_prepare = yes'
	for good in "${goods[@]}"; do
		printf '\tmodeu5_validate_dirty_markets_good_%s = yes\n' "$good"
	done
	printf '%s\n' '	modeu5_reconciliation_finalize = yes'
	printf '%s\n' '}'
	printf '%s\n\n' 'modeu5_validate_all_stock_consistency = {'
	printf '%s\n' '	save_temporary_scope_as = modeu5_reconciliation_controller'
	printf '%s\n' '	save_temporary_scope_value_as = { name = modeu5_reconciliation_type value = 2 }'
	printf '%s\n' '	modeu5_reconciliation_prepare = yes'
	for good in "${goods[@]}"; do
		printf '\tmodeu5_validate_all_markets_good_%s = yes\n' "$good"
	done
	printf '%s\n' '	modeu5_reconciliation_finalize = yes'
	printf '%s\n' '}'
	printf '%s\n\n' 'modeu5_clear_all_dirty_stock_markets = {'
	for good in "${goods[@]}"; do
		printf '\tmodeu5_clear_dirty_markets_good_%s = yes\n' "$good"
	done
	printf '%s\n' '}'
	printf '%s\n\n' 'modeu5_initialize_opening_stocks = {'
	for good in "${goods[@]}"; do
		printf '\tmodeu5_initialize_opening_stocks_good_%s = yes\n' "$good"
	done
	printf '%s\n' '}'

	first=1
	for good in "${goods[@]}"; do
		if (( first == 0 )); then
			printf '\n'
		fi
		first=0
		sed \
			-e "s/__GOOD__/$good/g" \
			-e "s/__STOCK_MAP__/modeu5_${good}_stock_by_market/g" \
			-e "s/__CAPACITY_MAP__/modeu5_${good}_stock_cap_by_market/g" \
			-e "s/__BASE_CAPACITY_MAP__/modeu5_${good}_base_capacity_by_market/g" \
			-e "s/__BUILDING_CAPACITY_MAP__/modeu5_${good}_building_capacity_by_market/g" \
			-e "s/__FOREIGN_CAPACITY_MAP__/modeu5_${good}_foreign_capacity_by_market/g" \
			-e "s/__MARKET_MAP__/modeu5_${good}_market_stock/g" \
			-e "s/__DIRTY_LIST__/modeu5_${good}_dirty_markets/g" \
			"$template"
	done
} > "$output"
