#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
template="$repo_root/tools/templates/modeu5_pr71_active_good_dispatch_good.template.txt"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_zz_pr71_active_good_dispatch_generated.txt}"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_goods_registry
goods=("${modeu5_goods[@]}")

mkdir -p "$(dirname "$output")"

{
	cat <<'TXT'
# Generated by tools/generate_pr71_active_good_dispatch_helpers.sh.
# Do not edit manually.
# Literal per-good PR7.1 active-good dispatch guards are generated from
# tools/templates/modeu5_pr71_active_good_dispatch_good.template.txt.
#
# PR126 PR7.1 active-good dispatch guards.
#
# This file preserves PR7's promoted-market ownership shape while avoiding the
# expensive generated all-good helper body when the existing main-branch
# business gate says the good has no work.
#
# Important: the generated per-good symbol surface still exists because EU5
# scripted effect names and map names must remain literal. PR7.1 narrows the
# call into the heavy generated helpers; it does not remove the generated
# helpers from the repository.
#
# The live monthly handoff is intentionally not generated here. EU5 rejects
# duplicate scripted-effect keys, so the tracked PR7 live effect must call the
# generated PR7.1 dispatchers directly.

modeu5_pr71_reset_active_good_metrics = {
	remove_global_variable = modeu5_pr71_active_good_metrics_stamp
	remove_global_variable = modeu5_pr71_us00_goods_considered
	remove_global_variable = modeu5_pr71_us00_goods_processed
	remove_global_variable = modeu5_pr71_us00_goods_produced_gate_hits
	remove_global_variable = modeu5_pr71_us00_goods_previous_state_hits
	remove_global_variable = modeu5_pr71_us10_goods_considered
	remove_global_variable = modeu5_pr71_us10_requests_processed
	remove_global_variable = modeu5_pr71_us10_pending_request_hits

	set_global_variable = { name = modeu5_pr71_us00_goods_considered value = 0 }
	set_global_variable = { name = modeu5_pr71_us00_goods_processed value = 0 }
	set_global_variable = { name = modeu5_pr71_us00_goods_produced_gate_hits value = 0 }
	set_global_variable = { name = modeu5_pr71_us00_goods_previous_state_hits value = 0 }
	set_global_variable = { name = modeu5_pr71_us10_goods_considered value = 0 }
	set_global_variable = { name = modeu5_pr71_us10_requests_processed value = 0 }
	set_global_variable = { name = modeu5_pr71_us10_pending_request_hits value = 0 }
}

modeu5_pr71_prepare_active_good_metrics = {
	save_temporary_scope_value_as = {
		name = modeu5_pr71_active_good_metrics_stamp
		value = {
			value = current_year
			multiply = 12
			add = current_month
		}
	}

	if = {
		limit = {
			OR = {
				NOT = { has_global_variable = modeu5_pr71_active_good_metrics_stamp }
				global_var:modeu5_pr71_active_good_metrics_stamp != scope:modeu5_pr71_active_good_metrics_stamp
			}
		}
		modeu5_pr71_reset_active_good_metrics = yes
		set_global_variable = { name = modeu5_pr71_active_good_metrics_stamp value = scope:modeu5_pr71_active_good_metrics_stamp }
	}
	else_if = {
		limit = { NOT = { has_global_variable = modeu5_pr71_us00_goods_considered } }
		modeu5_pr71_reset_active_good_metrics = yes
		set_global_variable = { name = modeu5_pr71_active_good_metrics_stamp value = scope:modeu5_pr71_active_good_metrics_stamp }
	}
}

modeu5_pr71_note_us00_goods_considered = {
	set_global_variable = { name = modeu5_pr71_us00_goods_considered value = { value = global_var:modeu5_pr71_us00_goods_considered add = 1 } }
}

modeu5_pr71_note_us00_goods_processed = {
	set_global_variable = { name = modeu5_pr71_us00_goods_processed value = { value = global_var:modeu5_pr71_us00_goods_processed add = 1 } }
}

modeu5_pr71_note_us00_goods_produced_gate_hit = {
	set_global_variable = { name = modeu5_pr71_us00_goods_produced_gate_hits value = { value = global_var:modeu5_pr71_us00_goods_produced_gate_hits add = 1 } }
}

modeu5_pr71_note_us00_goods_previous_state_hit = {
	set_global_variable = { name = modeu5_pr71_us00_goods_previous_state_hits value = { value = global_var:modeu5_pr71_us00_goods_previous_state_hits add = 1 } }
}

modeu5_pr71_note_us10_goods_considered = {
	set_global_variable = { name = modeu5_pr71_us10_goods_considered value = { value = global_var:modeu5_pr71_us10_goods_considered add = 1 } }
}

modeu5_pr71_note_us10_pending_request_hit = {
	set_global_variable = { name = modeu5_pr71_us10_pending_request_hits value = { value = global_var:modeu5_pr71_us10_pending_request_hits add = 1 } }
}

modeu5_pr71_note_us10_request_processed = {
	set_global_variable = { name = modeu5_pr71_us10_requests_processed value = { value = global_var:modeu5_pr71_us10_requests_processed add = 1 } }
}

TXT

	for good in "${goods[@]}"; do
		modeu5_render_template_to_stdout "$template" "GOOD=$good"
		printf '\n'
	done

	cat <<'TXT'
modeu5_pr71_process_us00_monthly_market_active_goods = {
TXT
	for good in "${goods[@]}"; do
		printf '\tmodeu5_pr71_process_us00_monthly_market_good_%s = yes\n' "$good"
	done
	cat <<'TXT'
}

modeu5_pr71_process_us10_monthly_market_pending_goods = {
TXT
	for good in "${goods[@]}"; do
		printf '\tmodeu5_pr71_process_us10_monthly_market_good_%s = yes\n' "$good"
	done
	cat <<'TXT'
}
TXT
} > "$output"

printf 'Generated %s\n' "$output"
