#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_transport_cost_generated.txt}"
local_config="$repo_root/.modeu5.local.env"

# shellcheck source=tools/modeu5_goods.sh
source "$repo_root/tools/modeu5_goods.sh"

if [[ -f "$local_config" ]]; then
	set -a
	# shellcheck source=/dev/null
	source "$local_config"
	set +a
fi

common_dir="${EU5_GAME_COMMON_DIR:-}"
goods_dir=""
if [[ -n "$common_dir" && -d "$common_dir/goods" ]]; then
	goods_dir="$common_dir/goods"
fi

mkdir -p "$(dirname "$output")"

python3 - "$output" "$goods_dir" "${modeu5_goods[@]}" <<'PY'
from pathlib import Path
import re
import sys

output = Path(sys.argv[1])
goods_dir_arg = sys.argv[2]
wanted_goods = sys.argv[3:]

number_re = re.compile(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)")


def strip_comments(text: str) -> str:
    stripped_lines: list[str] = []
    for line in text.splitlines():
        stripped_lines.append(line.split("#", 1)[0])
    return "\n".join(stripped_lines)


def find_matching_brace(text: str, opening_index: int) -> int:
    depth = 0
    for index in range(opening_index, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unclosed brace while parsing goods")


def parse_transport_costs(goods_dir: Path) -> dict[str, float]:
    costs: dict[str, float] = {}
    for path in sorted(goods_dir.glob("*.txt")):
        text = strip_comments(path.read_text(encoding="utf-8-sig"))
        position = 0
        while True:
            match = re.search(r"(?m)^([A-Za-z0-9_]+)\s*=\s*\{", text[position:])
            if match is None:
                break
            good = match.group(1)
            block_open = position + match.end() - 1
            block_close = find_matching_brace(text, block_open)
            block = text[block_open + 1:block_close]
            cost_match = re.search(r"(?m)^\s*transport_cost\s*=\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+))\b", block)
            if cost_match:
                costs[good] = float(cost_match.group(1))
            position = block_close + 1
    return costs


def fmt(value: float) -> str:
    if value == int(value):
        return str(int(value))
    return f"{value:.10f}".rstrip("0").rstrip(".")


costs: dict[str, float] = {}
source_mode = "safe defaults"
if goods_dir_arg:
    costs = parse_transport_costs(Path(goods_dir_arg))
    source_mode = "<EU5_GAME_COMMON_DIR>/goods"

lines: list[str] = [
    "# Generated by tools/generate_good_transport_helpers.sh.",
    "# Do not edit manually.",
    "# Converts a known trade-capacity-like volume into an estimated goods quantity.",
    "# This does not read exact vanilla trade quantity and must not mutate stock.",
    f"# Source: {source_mode}.",
    "",
]

missing_goods: list[str] = []
for good in wanted_goods:
    if good in costs:
        raw_cost = costs[good]
        defaulted = 0
    else:
        raw_cost = 1.0
        defaulted = 1
        missing_goods.append(good)

    lines.extend(
        [
            f"modeu5_get_transport_cost_good_{good} = {{",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_good_transport_cost_raw",
            f"\t\tvalue = {fmt(raw_cost)}",
            "\t}",
            f"\tsave_temporary_scope_value_as = {{ name = modeu5_good_transport_cost_defaulted value = {defaulted} }}",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_good_transport_cost",
            "\t\tvalue = {",
            "\t\t\tvalue = scope:modeu5_good_transport_cost_raw",
            "\t\t\tmin = 0.0001",
            "\t\t}",
            "\t}",
            "}",
            "",
            f"modeu5_compute_goods_quantity_from_trade_capacity_good_{good} = {{",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_trade_capacity_volume_raw",
            "\t\tvalue = {",
            "\t\t\tvalue = $capacity_volume$",
            "\t\t\tmin = 0",
            "\t\t}",
            "\t}",
            "",
            f"\tmodeu5_get_transport_cost_good_{good} = yes",
            "",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_computed_goods_quantity",
            "\t\tvalue = {",
            "\t\t\tvalue = scope:modeu5_trade_capacity_volume_raw",
            "\t\t\tdivide = scope:modeu5_good_transport_cost",
            "\t\t\tmin = 0",
            "\t\t}",
            "\t}",
            "\tsave_temporary_scope_value_as = { name = modeu5_estimated_goods_quantity value = scope:modeu5_computed_goods_quantity }",
            "}",
            "",
            f"modeu5_compute_goods_quantity_from_trade_capacity_with_route_good_{good} = {{",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_trade_capacity_volume_raw",
            "\t\tvalue = {",
            "\t\t\tvalue = $capacity_volume$",
            "\t\t\tmin = 0",
            "\t\t}",
            "\t}",
            "",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_trade_route_cost_multiplier",
            "\t\tvalue = {",
            "\t\t\tvalue = $route_cost_multiplier$",
            "\t\t\tmin = 0.0001",
            "\t\t}",
            "\t}",
            "",
            f"\tmodeu5_get_transport_cost_good_{good} = yes",
            "",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_trade_quantity_denominator",
            "\t\tvalue = {",
            "\t\t\tvalue = scope:modeu5_good_transport_cost",
            "\t\t\tmultiply = scope:modeu5_trade_route_cost_multiplier",
            "\t\t\tmin = 0.0001",
            "\t\t}",
            "\t}",
            "",
            "\tsave_temporary_scope_value_as = {",
            "\t\tname = modeu5_computed_goods_quantity",
            "\t\tvalue = {",
            "\t\t\tvalue = scope:modeu5_trade_capacity_volume_raw",
            "\t\t\tdivide = scope:modeu5_trade_quantity_denominator",
            "\t\t\tmin = 0",
            "\t\t}",
            "\t}",
            "\tsave_temporary_scope_value_as = { name = modeu5_estimated_goods_quantity value = scope:modeu5_computed_goods_quantity }",
            "}",
            "",
            f"modeu5_diagnostic_trade_capacity_conversion_good_{good} = {{",
            f"\tmodeu5_compute_goods_quantity_from_trade_capacity_good_{good} = {{",
            "\t\tcapacity_volume = $capacity_volume$",
            "\t}",
            "}",
            "",
        ]
    )

if missing_goods:
    lines.extend(
        [
            "# Goods without explicit static transport_cost used the neutral safe default 1:",
            "# " + " ".join(missing_goods),
            "",
        ]
    )

output.write_text("\n".join(lines), encoding="utf-8")
PY
