#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$repo_root/in_game/common/scripted_effects/modeu5_transport_cost_generated.txt}"
template="$repo_root/tools/templates/modeu5_good_transport_helper.template.txt"

# shellcheck source=tools/modeu5_tool_lib.sh
source "$repo_root/tools/modeu5_tool_lib.sh"
modeu5_load_local_config
modeu5_load_goods_registry

modeu5_require_file "$template"

common_dir="${EU5_GAME_COMMON_DIR:-}"
goods_dir=""
if [[ -n "$common_dir" && -d "$common_dir/goods" ]]; then
	goods_dir="$common_dir/goods"
fi

mkdir -p "$(dirname "$output")"

python3 - "$output" "$goods_dir" "$template" "${modeu5_goods[@]}" <<'PY'
from pathlib import Path
import re
import sys

output = Path(sys.argv[1])
goods_dir_arg = sys.argv[2]
template = Path(sys.argv[3]).read_text(encoding="utf-8")
wanted_goods = sys.argv[4:]

number_re = re.compile(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)")


def strip_comments(text: str) -> str:
    stripped_lines: list[str] = []
    for line in text.splitlines():
        stripped_lines.append(line.split("#", 1)[0])
    return "\n".join(stripped_lines)


def find_matching_brace(text: str, opening_index: int) -> int:
    depth = 0
    for index in range(opening_index, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unclosed brace while parsing goods")


def parse_transport_costs(goods_dir: Path) -> dict[str, float]:
    costs: dict[str, float] = {}
    for path in sorted(goods_dir.glob("*.txt")):
        text = strip_comments(path.read_text(encoding="utf-8-sig"))
        position = 0
        while True:
            match = re.search(r"(?m)^([A-Za-z0-9_]+)\s*=\s*\{", text[position:])
            if match is None:
                break
            good = match.group(1)
            block_open = position + match.end() - 1
            block_close = find_matching_brace(text, block_open)
            block = text[block_open + 1:block_close]
            cost_match = re.search(r"(?m)^\s*transport_cost\s*=\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+))\b", block)
            if cost_match:
                costs[good] = float(cost_match.group(1))
            position = block_close + 1
    return costs


def fmt(value: float) -> str:
    if value == int(value):
        return str(int(value))
    return f"{value:.10f}".rstrip("0").rstrip(".")


def render_good_block(good: str, raw_cost: float, defaulted: int) -> str:
    replacements = {
        "__GOOD__": good,
        "__TRANSPORT_COST__": fmt(raw_cost),
        "__TRANSPORT_COST_DEFAULTED__": str(defaulted),
    }
    rendered = template
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    unresolved = sorted(set(re.findall(r"__[A-Z0-9_]+__", rendered)))
    if unresolved:
        raise SystemExit(
            "Unresolved placeholders in transport helper template: " + ", ".join(unresolved)
        )
    return rendered.rstrip()

def render_trade_owner_dispatcher(goods: list[str]) -> list[str]:
    lines: list[str] = [
        "# Generated PR126 trade-owner quantity dispatcher.",
        "# Converts native trade_volume through the literal-good static transport helpers.",
        "# Caller must set:",
        "# - modeu5_trade_owner_good",
        "# - cbp_trade_owner_trade_volume",
        "",
        "modeu5_compute_trade_owner_goods_quantity_from_traded_good = {",
        "\tsave_temporary_scope_value_as = { name = cbp_trade_owner_quantity_matched value = 0 }",
        "\tsave_temporary_scope_value_as = { name = cbp_trade_owner_goods_quantity value = 0 }",
    ]
    for good in goods:
        lines.extend(
            [
                "\tif = {",
                "\t\tlimit = {",
                "\t\t\tscope:cbp_trade_owner_quantity_matched = 0",
                f"\t\t\tscope:modeu5_trade_owner_good = goods:{good}",
                "\t\t}",
                f"\t\tmodeu5_compute_goods_quantity_from_trade_capacity_good_{good} = {{",
                "\t\t\tcapacity_volume = scope:cbp_trade_owner_trade_volume",
                "\t\t}",
                "\t\tsave_temporary_scope_value_as = { name = cbp_trade_owner_goods_quantity value = scope:cbp_computed_goods_quantity }",
                "\t\tsave_temporary_scope_value_as = { name = cbp_trade_owner_quantity_matched value = 1 }",
                "\t}",
            ]
        )
    lines.append("}")
    return lines



costs: dict[str, float] = {}
source_mode = "safe defaults"
if goods_dir_arg:
    costs = parse_transport_costs(Path(goods_dir_arg))
    source_mode = "<EU5_GAME_COMMON_DIR>/goods"

lines: list[str] = [
    "# Generated by tools/generate_good_transport_helpers.sh.",
    "# Do not edit manually.",
    "# Converts a known trade-capacity-like volume into an estimated goods quantity.",
    "# This does not read exact vanilla trade quantity and must not mutate stock.",
    f"# Source: {source_mode}.",
    "",
]

missing_goods: list[str] = []
for good in wanted_goods:
    if good in costs:
        raw_cost = costs[good]
        defaulted = 0
    else:
        raw_cost = 1.0
        defaulted = 1
        missing_goods.append(good)

    lines.extend([render_good_block(good, raw_cost, defaulted), ""])

if missing_goods:
    lines.extend(
        [
            "# Goods without explicit static transport_cost used the neutral safe default 1:",
            "# " + " ".join(missing_goods),
            "",
        ]
    )

lines.extend(render_trade_owner_dispatcher(wanted_goods))
lines.append("")
output.write_text("\n".join(lines), encoding="utf-8")
PY
