#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path


MODIFIER = "minting_income_factor"
TOKEN = re.compile(rf"\b{re.escape(MODIFIER)}\b")
ASSIGNMENT = re.compile(
    rf"(?<![A-Za-z0-9_])({re.escape(MODIFIER)}[ \t]*=[ \t]*)"
    r"(-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+))"
    r"(?=$|[ \t}\r\n])"
)


@dataclass(frozen=True)
class SourceOccurrence:
    line: int
    old: Decimal
    old_text: str
    expected_text: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compose US-177 minting scaling into generated building overrides "
            "already generated by US-07/US-09."
        )
    )
    parser.add_argument("--common-dir", required=True, type=Path)
    parser.add_argument("--package-common-dir", required=True, type=Path)
    parser.add_argument("--multiplier", default="2")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def parse_multiplier(raw: str) -> Decimal:
    try:
        multiplier = Decimal(raw)
    except InvalidOperation as exc:
        raise SystemExit(f"Multiplier must be numeric; got {raw!r}.") from exc
    if not multiplier.is_finite() or multiplier < 0:
        raise SystemExit(f"Multiplier must be finite and non-negative; got {raw!r}.")
    return multiplier


def format_decimal(value: Decimal) -> str:
    if value == 0:
        return "0"
    text = format(value.normalize(), "f")
    if "." not in text:
        return f"{text}.0"
    return text.rstrip("0").rstrip(".")


def split_comment(line: str) -> tuple[str, str]:
    if "#" not in line:
        return line, ""
    code, comment = line.split("#", 1)
    return code, f"#{comment}"


def source_occurrences(path: Path, multiplier: Decimal) -> list[SourceOccurrence]:
    text = path.read_text(encoding="utf-8-sig")
    occurrences: list[SourceOccurrence] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        code, _ = split_comment(line)
        token_count = len(TOKEN.findall(code))
        matches = list(ASSIGNMENT.finditer(code))
        if token_count != len(matches):
            raise SystemExit(
                f"Unsupported {MODIFIER} syntax in {path}:{line_number}: {line.strip()}"
            )
        for match in matches:
            old_text = match.group(2)
            old = Decimal(old_text)
            occurrences.append(
                SourceOccurrence(
                    line=line_number,
                    old=old,
                    old_text=old_text,
                    expected_text=format_decimal(old * multiplier),
                )
            )
    return occurrences


def apply_expected_values(text: str, expected: list[SourceOccurrence], label: str) -> str:
    ordinal = 0
    output_lines: list[str] = []
    for line_number, line in enumerate(text.splitlines(keepends=True), start=1):
        body = line.rstrip("\r\n")
        newline = line[len(body) :]
        code, comment = split_comment(body)
        token_count = len(TOKEN.findall(code))
        matches = list(ASSIGNMENT.finditer(code))
        if token_count != len(matches):
            raise SystemExit(
                f"Unsupported {MODIFIER} syntax in {label}:{line_number}: {body.strip()}"
            )

        def replace(match: re.Match[str]) -> str:
            nonlocal ordinal
            if ordinal >= len(expected):
                raise SystemExit(
                    f"{label} contains more {MODIFIER} assignments than its vanilla source."
                )
            replacement = expected[ordinal].expected_text
            ordinal += 1
            return f"{match.group(1)}{replacement}"

        output_lines.append(f"{ASSIGNMENT.sub(replace, code)}{comment}{newline}")

    if ordinal != len(expected):
        raise SystemExit(
            f"{label} contains {ordinal} {MODIFIER} assignments but vanilla contains "
            f"{len(expected)}."
        )
    return "".join(output_lines)


def sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def main() -> int:
    args = parse_args()
    multiplier = parse_multiplier(args.multiplier)
    source_dir = args.common_dir / "building_types"
    output_dir = args.package_common_dir / "building_types"
    manifest_path = args.package_common_dir.parent.parent / "cbp_generated/us177_minting_building_manifest.json"

    if not source_dir.is_dir():
        raise SystemExit(f"Missing source building_types directory: {source_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest_files: list[dict[str, object]] = []
    failures: list[str] = []

    for source_file in sorted(source_dir.glob("*.txt")):
        occurrences = source_occurrences(source_file, multiplier)
        if not occurrences:
            continue

        output_file = output_dir / source_file.name
        if output_file.is_file():
            current_bytes = output_file.read_bytes()
            current_text = current_bytes.decode("utf-8-sig")
            had_bom = current_bytes.startswith(b"\xef\xbb\xbf")
        else:
            current_bytes = source_file.read_bytes()
            current_text = current_bytes.decode("utf-8-sig")
            had_bom = current_bytes.startswith(b"\xef\xbb\xbf")

        expected_text = apply_expected_values(current_text, occurrences, source_file.name)
        expected_bytes = expected_text.encode("utf-8")
        if had_bom:
            expected_bytes = b"\xef\xbb\xbf" + expected_bytes

        if args.check:
            if not output_file.is_file():
                failures.append(f"missing generated building override: {source_file.name}")
            elif output_file.read_bytes() != expected_bytes:
                failures.append(f"stale minting scaling in building override: {source_file.name}")
        else:
            output_file.write_bytes(expected_bytes)

        manifest_files.append(
            {
                "path": f"in_game/common/building_types/{source_file.name}",
                "source_sha256": sha256(source_file.read_bytes()),
                "generated_sha256": sha256(expected_bytes),
                "occurrences": [
                    {
                        "line": item.line,
                        "old": item.old_text,
                        "new": item.expected_text,
                    }
                    for item in occurrences
                ],
            }
        )

    if not manifest_files:
        raise SystemExit(
            f"No numeric {MODIFIER} assignments found in {source_dir}; refusing an empty building pass."
        )

    payload = {
        "schema_version": 1,
        "source_root": "<EU5_GAME_COMMON_DIR>/building_types",
        "modifier": MODIFIER,
        "multiplier": format_decimal(multiplier),
        "generated_file_count": len(manifest_files),
        "occurrence_count": sum(len(item["occurrences"]) for item in manifest_files),
        "files": manifest_files,
    }
    expected_manifest = (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")

    if args.check:
        if not manifest_path.is_file():
            failures.append(f"missing building manifest: {manifest_path}")
        elif manifest_path.read_bytes() != expected_manifest:
            failures.append(f"stale building manifest: {manifest_path}")
        if failures:
            raise SystemExit("US-177 building minting validation failed:\n- " + "\n- ".join(failures))
        print(
            f"US-177 building minting composition is current: {len(manifest_files)} files, "
            f"{payload['occurrence_count']} occurrences."
        )
        return 0

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_bytes(expected_manifest)
    print(
        f"Composed US-177 minting scaling into {len(manifest_files)} building files, "
        f"{payload['occurrence_count']} occurrences."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
