#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import sys
from pathlib import Path

import transform_cbp_economy_building_overrides as transformer
import postprocess_us177_minting_building_overrides as minting_transformer


def parse_goods_registry(repo_root: Path) -> list[str]:
    registry = repo_root / "tools" / "cbp_goods.sh"
    text = registry.read_text(encoding="utf-8")
    before, _, after = text.partition("cbp_goods=(")
    if not after:
        raise SystemExit(f"Could not find cbp_goods array in {registry}")
    body, _, _ = after.partition(")")
    goods: list[str] = []
    for raw_line in body.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        goods.extend(line.split())
    if not goods:
        raise SystemExit(f"Could not load any goods from {registry}")
    return goods


def strip_generated_header(text: str) -> list[str]:
    lines = text.splitlines()
    index = 0
    generated_prefixes = (
        "# Generated by tools/generate_us09_economy_overrides.sh.",
        "# Do not edit manually.",
        "# Source: ",
        "# Output multiplier: ",
        "# Trade capacity multiplier: ",
        "# Building maintenance multiplier: ",
        "# Trade-building maintenance multiplier: ",
        "# Minting income multiplier: ",
    )
    while index < len(lines) and any(
        lines[index].startswith(prefix) for prefix in generated_prefixes
    ):
        index += 1
    if index < len(lines) and not lines[index].strip():
        index += 1
    if (
        index < len(lines)
        and lines[index].startswith("# US-07 composed trade-building estate-power multiplier:")
    ):
        index += 1
        if index < len(lines) and not lines[index].strip():
            index += 1
    return lines[index:]


def normalize_generator_whitespace(lines: list[str]) -> list[str]:
    normalized: list[str] = []
    for raw_line in lines:
        line = raw_line.rstrip(" \t")
        while True:
            updated = re.sub(r"^(\t*) +\t", r"\1\t", line)
            if updated == line:
                break
            line = updated
        normalized.append(line)
    return normalized


def maintenance_entries(lines: list[str], goods: set[str]) -> list[tuple[str, float, bool]]:
    ranges = transformer.find_maintenance_blocks(lines)
    entries: list[tuple[str, float, bool]] = []
    for index, line in enumerate(lines):
        maintenance_range = transformer.maintenance_range_for_line(index, ranges)
        if maintenance_range is None:
            continue
        match = transformer.ASSIGNMENT.match(line)
        if not match:
            continue
        key = match.group(2)
        if key in goods:
            trade_building = (
                isinstance(maintenance_range, transformer.MaintenanceRange)
                and maintenance_range.trade_building
            )
            entries.append((key, float(match.group(3)), trade_building))
    return entries


def active_stockpile_capacity_entries(lines: list[str]) -> list[float]:
    entries: list[float] = []
    for line in lines:
        match = transformer.ASSIGNMENT.match(line)
        if not match or match.group(2) != transformer.STOCKPILE_CAPACITY_FIELD:
            continue
        entries.append(float(match.group(3)))
    return entries


def commented_stockpile_capacity_entries(lines: list[str]) -> list[float]:
    entries: list[float] = []
    for line in lines:
        match = transformer.COMMENTED_STOCKPILE_CAPACITY.match(line)
        if match:
            entries.append(float(match.group(1)))
    return entries


def compare_float(actual: float, expected: float) -> bool:
    return math.isclose(actual, expected, rel_tol=1e-9, abs_tol=1e-9)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate generated CBP building maintenance overrides."
    )
    parser.add_argument("--common-dir", type=Path, default=os.environ.get("EU5_GAME_COMMON_DIR"))
    parser.add_argument(
        "--package-common-dir",
        type=Path,
        default=Path("packages/cbp_economy_rebalance/in_game/common"),
    )
    parser.add_argument("--us09-percent", type=float, default=float(os.environ.get("MODEU5_US09_BONUS_PERCENT", "10")))
    parser.add_argument(
        "--trade-capacity-percent",
        type=float,
        default=float(
            os.environ.get(
                "MODEU5_US09_TRADE_CAPACITY_BONUS_PERCENT",
                os.environ.get("MODEU5_US09_BONUS_PERCENT", "10"),
            )
        ),
    )
    parser.add_argument("--maintenance-multiplier", type=float, default=0.7)
    parser.add_argument("--trade-building-maintenance-multiplier", type=float, default=0.5)
    parser.add_argument(
        "--minting-multiplier",
        default=os.environ.get("MODEU5_US177_MINTING_MULTIPLIER", "2"),
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    common_dir = Path(args.common_dir) if args.common_dir is not None else None
    if common_dir is None:
        raise SystemExit("EU5 common dir is required; pass --common-dir or set EU5_GAME_COMMON_DIR")

    source_dir = common_dir / "building_types"
    output_dir = Path(args.package_common_dir) / "building_types"
    manifest_dir = Path(args.package_common_dir).parents[1] / "cbp_generated" / "us09_buildings"
    if not source_dir.is_dir():
        raise SystemExit(f"Missing source building_types directory: {source_dir}")
    if not output_dir.is_dir():
        raise SystemExit(f"Missing generated building_types directory: {output_dir}")
    if not manifest_dir.is_dir():
        raise SystemExit(f"Missing generated building manifest directory: {manifest_dir}")

    goods = parse_goods_registry(repo_root)
    goods_set = set(goods)
    output_multiplier = 1.0 + args.us09_percent / 100.0
    trade_capacity_multiplier = 1.0 + args.trade_capacity_percent / 100.0
    us07_multiplier = 0.5
    minting_multiplier = minting_transformer.parse_multiplier(args.minting_multiplier)

    failures: list[str] = []
    source_files_with_maintenance = 0
    generated_files_checked = 0
    maintenance_entries_checked = 0
    stockpile_capacity_entries_checked = 0
    manifests_checked = 0
    expected_manifest_names: set[str] = set()

    for source_file in sorted(source_dir.glob("*.txt")):
        if source_file.name == "readme.txt":
            continue

        source_lines = source_file.read_text(encoding="utf-8-sig").splitlines()
        source_entries = maintenance_entries(source_lines, goods_set)
        source_stockpile_entries = active_stockpile_capacity_entries(source_lines)
        generated_file = output_dir / source_file.name
        manifest_file = manifest_dir / f"{source_file.stem}.json"

        try:
            expected_body, expected_changes, building_count = transformer.transform_lines_with_plan(
                source_lines,
                source_basename=source_file.name,
                output_multiplier=output_multiplier,
                trade_capacity_multiplier=trade_capacity_multiplier,
                maintenance_multiplier=args.maintenance_multiplier,
                trade_building_maintenance_multiplier=args.trade_building_maintenance_multiplier,
                us07_trade_burghers_estate_power_multiplier=us07_multiplier,
                minting_income_multiplier=float(minting_multiplier),
                goods=goods_set,
            )
        except ValueError as error:
            failures.append(f"{source_file.name}: unsupported vanilla structure: {error}")
            continue

        if not expected_changes:
            if generated_file.exists():
                failures.append(
                    f"{source_file.name}: override exists although no building transformation applies"
                )
            if manifest_file.exists():
                failures.append(
                    f"{source_file.name}: manifest exists although no building transformation applies"
                )
            continue

        expected_manifest_names.add(manifest_file.name)
        if not generated_file.is_file():
            failures.append(f"Missing generated override for applicable source file: {source_file.name}")
            continue
        if not manifest_file.is_file():
            failures.append(f"Missing building-level change manifest: {manifest_file.name}")
            continue

        if source_entries:
            source_files_with_maintenance += 1

        generated_text = generated_file.read_text(encoding="utf-8-sig")
        generated_body_lines = normalize_generator_whitespace(strip_generated_header(generated_text))
        generated_entries = maintenance_entries(generated_body_lines, goods_set)
        minting_occurrences = minting_transformer.source_occurrences(
            source_file, minting_multiplier
        )
        if minting_occurrences:
            expected_text = minting_transformer.apply_expected_values(
                "\n".join(expected_body) + "\n",
                minting_occurrences,
                source_file.name,
            )
            expected_body = expected_text.splitlines()
        expected_body = normalize_generator_whitespace(expected_body)
        expected_entries = maintenance_entries(expected_body, goods_set)

        try:
            manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as error:
            failures.append(f"{manifest_file.name}: invalid manifest: {error}")
            continue
        source_label = f"<EU5_GAME_COMMON_DIR>/building_types/{source_file.name}"
        expected_manifest = transformer.build_manifest(
            source_file=source_file,
            source_label=source_label,
            generated_text=generated_text,
            changes=expected_changes,
            building_count=building_count,
        )
        if manifest != expected_manifest:
            failures.append(
                f"{manifest_file.name}: manifest does not match the parser-derived change plan"
            )
        if manifest.get("source_sha256") != hashlib.sha256(source_file.read_bytes()).hexdigest():
            failures.append(f"{manifest_file.name}: source fingerprint mismatch")
        if manifest.get("generated_sha256") != hashlib.sha256(
            generated_text.encode("utf-8")
        ).hexdigest():
            failures.append(f"{manifest_file.name}: generated fingerprint mismatch")
        manifests_checked += 1
        generated_active_stockpile_entries = active_stockpile_capacity_entries(
            generated_body_lines
        )
        generated_stockpile_entries = commented_stockpile_capacity_entries(
            generated_body_lines
        )

        if source_stockpile_entries:
            if generated_active_stockpile_entries:
                failures.append(
                    f"{source_file.name}: maximum_stockpile_capacity must be commented out; "
                    f"active generated values={generated_active_stockpile_entries}"
                )
            elif generated_stockpile_entries != source_stockpile_entries:
                failures.append(
                    f"{source_file.name}: commented maximum_stockpile_capacity values must "
                    f"match vanilla; vanilla={source_stockpile_entries} "
                    f"generated={generated_stockpile_entries}"
                )
            else:
                stockpile_capacity_entries_checked += len(generated_stockpile_entries)

        if source_entries:
            if len(expected_entries) != len(generated_entries):
                failures.append(
                    f"{source_file.name}: maintenance entry count mismatch "
                    f"expected={len(expected_entries)} generated={len(generated_entries)}"
                )
                continue

            for ordinal, (
                (expected_key, expected_value, expected_trade_building),
                (generated_key, generated_value, generated_trade_building),
            ) in enumerate(
                zip(expected_entries, generated_entries),
                start=1,
            ):
                if expected_key != generated_key:
                    failures.append(
                        f"{source_file.name}: maintenance entry #{ordinal} key mismatch "
                        f"expected={expected_key} generated={generated_key}"
                    )
                    continue
                if expected_trade_building != generated_trade_building:
                    failures.append(
                        f"{source_file.name}: {expected_key} maintenance entry #{ordinal} "
                        f"trade-building classification mismatch "
                        f"expected={expected_trade_building} generated={generated_trade_building}"
                    )
                    continue
                if not compare_float(generated_value, expected_value):
                    failures.append(
                        f"{source_file.name}: {expected_key} maintenance entry #{ordinal} "
                        f"expected {expected_value:g}, found {generated_value:g}"
                    )
                maintenance_entries_checked += 1
        if generated_body_lines != expected_body:
            failures.append(
                f"{source_file.name}: generated building override body is stale or hand-edited"
            )
            continue

        generated_files_checked += 1

    actual_manifest_names = {path.name for path in manifest_dir.glob("*.json")}
    stale_manifests = sorted(actual_manifest_names - expected_manifest_names)
    if stale_manifests:
        failures.append(f"Stale building manifests: {', '.join(stale_manifests)}")

    if failures:
        print("CBP US-08 building maintenance validation failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        return 1

    print(
        "CBP US-08 building maintenance validation passed: "
        f"{source_files_with_maintenance} maintenance source files, "
        f"{generated_files_checked} generated building files, "
        f"{maintenance_entries_checked} maintenance entries checked, "
        f"{stockpile_capacity_entries_checked} disabled stockpile-capacity lines checked, "
        f"{manifests_checked} building manifests checked."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
