#!/usr/bin/env python3
from __future__ import annotations

import argparse
import math
import os
import re
import sys
from pathlib import Path

import transform_cbp_economy_building_overrides as transformer


def parse_goods_registry(repo_root: Path) -> list[str]:
    registry = repo_root / "tools" / "cbp_goods.sh"
    text = registry.read_text(encoding="utf-8")
    before, _, after = text.partition("cbp_goods=(")
    if not after:
        raise SystemExit(f"Could not find cbp_goods array in {registry}")
    body, _, _ = after.partition(")")
    goods: list[str] = []
    for raw_line in body.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        goods.extend(line.split())
    if not goods:
        raise SystemExit(f"Could not load any goods from {registry}")
    return goods


def strip_generated_header(text: str) -> list[str]:
    lines = text.splitlines()
    index = 0
    generated_prefixes = (
        "# Generated by tools/generate_us09_economy_overrides.sh.",
        "# Do not edit manually.",
        "# Source: ",
        "# Output multiplier: ",
        "# Building maintenance multiplier: ",
    )
    while index < len(lines) and any(
        lines[index].startswith(prefix) for prefix in generated_prefixes
    ):
        index += 1
    if index < len(lines) and not lines[index].strip():
        index += 1
    if (
        index < len(lines)
        and lines[index].startswith("# US-07 composed trade-building estate-power multiplier:")
    ):
        index += 1
        if index < len(lines) and not lines[index].strip():
            index += 1
    return lines[index:]


def normalize_generator_whitespace(lines: list[str]) -> list[str]:
    normalized: list[str] = []
    for raw_line in lines:
        line = raw_line.rstrip(" \t")
        while True:
            updated = re.sub(r"^(\t*) +\t", r"\1\t", line)
            if updated == line:
                break
            line = updated
        normalized.append(line)
    return normalized


def maintenance_entries(lines: list[str], goods: set[str]) -> list[tuple[str, float]]:
    ranges = transformer.find_maintenance_ranges(lines)
    entries: list[tuple[str, float]] = []
    for index, line in enumerate(lines):
        if not transformer.line_is_in_ranges(index, ranges):
            continue
        match = transformer.ASSIGNMENT.match(line)
        if not match:
            continue
        key = match.group(2)
        if key in goods:
            entries.append((key, float(match.group(3))))
    return entries


def compare_float(actual: float, expected: float) -> bool:
    return math.isclose(actual, expected, rel_tol=1e-9, abs_tol=1e-9)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate generated CBP building maintenance overrides."
    )
    parser.add_argument("--common-dir", type=Path, default=os.environ.get("EU5_GAME_COMMON_DIR"))
    parser.add_argument(
        "--package-common-dir",
        type=Path,
        default=Path("packages/cbp_economy_rebalance/in_game/common"),
    )
    parser.add_argument("--us09-percent", type=float, default=float(os.environ.get("MODEU5_US09_BONUS_PERCENT", "10")))
    parser.add_argument("--maintenance-multiplier", type=float, default=0.5)
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    common_dir = Path(args.common_dir) if args.common_dir is not None else None
    if common_dir is None:
        raise SystemExit("EU5 common dir is required; pass --common-dir or set EU5_GAME_COMMON_DIR")

    source_dir = common_dir / "building_types"
    output_dir = Path(args.package_common_dir) / "building_types"
    if not source_dir.is_dir():
        raise SystemExit(f"Missing source building_types directory: {source_dir}")
    if not output_dir.is_dir():
        raise SystemExit(f"Missing generated building_types directory: {output_dir}")

    goods = parse_goods_registry(repo_root)
    goods_set = set(goods)
    output_multiplier = 1.0 + args.us09_percent / 100.0
    us07_multiplier = 0.5

    failures: list[str] = []
    source_files_with_maintenance = 0
    generated_files_checked = 0
    maintenance_entries_checked = 0

    for source_file in sorted(source_dir.glob("*.txt")):
        if source_file.name == "readme.txt":
            continue

        source_lines = source_file.read_text(encoding="utf-8-sig").splitlines()
        source_entries = maintenance_entries(source_lines, goods_set)
        generated_file = output_dir / source_file.name

        if source_entries:
            source_files_with_maintenance += 1
            if not generated_file.is_file():
                failures.append(
                    f"Missing generated override for maintenance source file: {source_file.name}"
                )
                continue

        if not generated_file.is_file():
            continue

        generated_text = generated_file.read_text(encoding="utf-8-sig")
        generated_body_lines = normalize_generator_whitespace(strip_generated_header(generated_text))
        generated_entries = maintenance_entries(generated_body_lines, goods_set)

        if source_entries:
            if len(source_entries) != len(generated_entries):
                failures.append(
                    f"{source_file.name}: maintenance entry count mismatch "
                    f"source={len(source_entries)} generated={len(generated_entries)}"
                )
                continue

            for ordinal, ((source_key, source_value), (generated_key, generated_value)) in enumerate(
                zip(source_entries, generated_entries),
                start=1,
            ):
                expected = source_value * args.maintenance_multiplier
                if source_key != generated_key:
                    failures.append(
                        f"{source_file.name}: maintenance entry #{ordinal} key mismatch "
                        f"source={source_key} generated={generated_key}"
                    )
                    continue
                if not compare_float(generated_value, expected):
                    failures.append(
                        f"{source_file.name}: {source_key} maintenance entry #{ordinal} "
                        f"expected {expected:g}, found {generated_value:g}"
                    )
                maintenance_entries_checked += 1

        expected_body = normalize_generator_whitespace(
            transformer.transform_lines(
                source_lines,
                source_basename=source_file.name,
                output_multiplier=output_multiplier,
                maintenance_multiplier=args.maintenance_multiplier,
                us07_trade_burghers_estate_power_multiplier=us07_multiplier,
                goods=goods_set,
            )
        )
        if generated_body_lines != expected_body:
            failures.append(
                f"{source_file.name}: generated building override body is stale or hand-edited"
            )
            continue

        generated_files_checked += 1

    if failures:
        print("CBP US-08 building maintenance validation failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        return 1

    print(
        "CBP US-08 building maintenance validation passed: "
        f"{source_files_with_maintenance} maintenance source files, "
        f"{generated_files_checked} generated building files, "
        f"{maintenance_entries_checked} maintenance entries checked."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
