#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import sys
from pathlib import Path

import postprocess_us177_minting_building_overrides as minting_transformer
import transform_cbp_economy_building_overrides as transformer
from cbg.adapters.cbp.generate_cbp_cbg_building_spec import (
    apply_foreign_trade_capacity_multiplier,
    build_injection_fragment,
    build_prefixed_production_methods,
    changed_additive_fields,
    requires_exact_file_override,
)


def parse_goods_registry(repo_root: Path) -> list[str]:
    registry = repo_root / "tools" / "cbp_goods.sh"
    text = registry.read_text(encoding="utf-8")
    _before, _separator, after = text.partition("cbp_goods=(")
    if not after:
        raise SystemExit(f"Could not find cbp_goods array in {registry}")
    body, _separator, _after = after.partition(")")
    goods: list[str] = []
    for raw_line in body.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        goods.extend(line.split())
    if not goods:
        raise SystemExit(f"Could not load any goods from {registry}")
    return goods


def strip_generated_header(text: str) -> list[str]:
    lines = text.splitlines()
    index = 0
    generated_prefixes = (
        "# Generated by tools/generate_us09_economy_overrides.sh.",
        (
            "# Generated by "
            "tools/cbg/adapters/cbp/generate_cbp_cbg_building_spec.py."
        ),
        "# Do not edit manually.",
        "# Source: ",
        "# Output multiplier: ",
        "# Trade capacity multiplier: ",
        "# Foreign-building merchant capacity multiplier: ",
        "# Building maintenance multiplier: ",
        "# Trade-building maintenance multiplier: ",
        "# Minting income multiplier: ",
        "# Fixed monthly political modifier multiplier: ",
        "# US-07 composed trade-building estate-power multiplier: ",
        "# Generation mode: ",
        "# Additive field family: ",
        "# Additive family: ",
    )
    while index < len(lines) and (
        not lines[index].strip()
        or any(lines[index].startswith(prefix) for prefix in generated_prefixes)
    ):
        index += 1
    return lines[index:]


def normalize_generator_whitespace(lines: list[str]) -> list[str]:
    normalized: list[str] = []
    for raw_line in lines:
        line = raw_line.rstrip(" \t")
        while True:
            updated = re.sub(r"^(\t*) +\t", r"\1\t", line)
            if updated == line:
                break
            line = updated
        normalized.append(line)
    return normalized


def top_level_blocks(lines: list[str]) -> dict[str, list[str]]:
    return {
        block.key: lines[block.start : block.end + 1]
        for block in transformer.top_level_buildings(lines)
    }


def strip_database_entry_modes(lines: list[str]) -> list[str]:
    return [
        re.sub(
            r"^(?P<indent>[ \t]*)(?:REPLACE|INJECT|TRY_INJECT):",
            r"\g<indent>",
            line,
        )
        for line in lines
    ]


def maintenance_entries(lines: list[str], goods: set[str]) -> list[tuple[str, float, bool]]:
    ranges = transformer.find_maintenance_blocks(lines)
    entries: list[tuple[str, float, bool]] = []
    for index, line in enumerate(lines):
        maintenance_range = transformer.maintenance_range_for_line(index, ranges)
        if maintenance_range is None:
            continue
        match = transformer.ASSIGNMENT.match(line)
        if not match:
            continue
        key = match.group(2)
        if key in goods:
            trade_building = (
                isinstance(maintenance_range, transformer.MaintenanceRange)
                and maintenance_range.trade_building
            )
            entries.append((key, float(match.group(3)), trade_building))
    return entries


def active_stockpile_capacity_entries(lines: list[str]) -> list[float]:
    entries: list[float] = []
    for line in lines:
        match = transformer.ASSIGNMENT.match(line)
        if not match or match.group(2) != transformer.STOCKPILE_CAPACITY_FIELD:
            continue
        entries.append(float(match.group(3)))
    return entries


def commented_stockpile_capacity_entries(lines: list[str]) -> list[float]:
    entries: list[float] = []
    for line in lines:
        match = transformer.COMMENTED_STOCKPILE_CAPACITY.match(line)
        if match:
            entries.append(float(match.group(1)))
    return entries


def compare_float(actual: float, expected: float) -> bool:
    return math.isclose(actual, expected, rel_tol=1e-9, abs_tol=1e-9)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate generated CBP exact-path/INJECT building overrides."
    )
    parser.add_argument("--common-dir", type=Path, default=os.environ.get("EU5_GAME_COMMON_DIR"))
    parser.add_argument(
        "--package-common-dir",
        type=Path,
        default=Path("packages/cbp_economy_rebalance/in_game/common"),
    )
    parser.add_argument("--us09-percent", type=float, default=float(os.environ.get("MODEU5_US09_BONUS_PERCENT", "10")))
    parser.add_argument(
        "--trade-capacity-percent",
        type=float,
        default=float(
            os.environ.get(
                "MODEU5_US09_TRADE_CAPACITY_BONUS_PERCENT",
                os.environ.get("MODEU5_US09_BONUS_PERCENT", "10"),
            )
        ),
    )
    parser.add_argument("--maintenance-multiplier", type=float, default=0.7)
    parser.add_argument("--trade-building-maintenance-multiplier", type=float, default=0.5)
    parser.add_argument(
        "--foreign-trade-capacity-multiplier",
        type=float,
        default=2.0,
    )
    parser.add_argument(
        "--minting-multiplier",
        default=os.environ.get("MODEU5_US177_MINTING_MULTIPLIER", "2"),
    )
    parser.add_argument(
        "--generation-mode",
        choices=("override", "compatibility"),
        default=os.environ.get("MODEU5_BUILDING_GENERATION_MODE", "override"),
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    common_dir = Path(args.common_dir) if args.common_dir is not None else None
    if common_dir is None:
        raise SystemExit("EU5 common dir is required; pass --common-dir or set EU5_GAME_COMMON_DIR")

    source_dir = common_dir / "building_types"
    output_dir = Path(args.package_common_dir) / "building_types"
    package_root = Path(args.package_common_dir).parents[1]
    cbg_manifest_file = package_root / "cbp_generated" / "cbg_building_manifest.json"
    if not source_dir.is_dir():
        raise SystemExit(f"Missing source building_types directory: {source_dir}")
    if not output_dir.is_dir():
        raise SystemExit(f"Missing generated building_types directory: {output_dir}")
    if not cbg_manifest_file.is_file():
        raise SystemExit(f"Missing CBG building manifest: {cbg_manifest_file}")

    try:
        cbg_manifest = json.loads(cbg_manifest_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as error:
        raise SystemExit(f"Invalid CBG building manifest {cbg_manifest_file}: {error}")
    cbg_files = {
        entry.get("path"): entry
        for entry in cbg_manifest.get("files", [])
        if isinstance(entry, dict) and isinstance(entry.get("path"), str)
    }

    goods = parse_goods_registry(repo_root)
    goods_set = set(goods)
    output_multiplier = 1.0 + args.us09_percent / 100.0
    trade_capacity_multiplier = 1.0 + args.trade_capacity_percent / 100.0
    us07_multiplier = 0.5
    minting_multiplier = minting_transformer.parse_multiplier(args.minting_multiplier)

    failures: list[str] = []
    source_files_with_maintenance = 0
    generated_files_checked = 0
    exact_files_checked = 0
    injected_files_checked = 0
    objects_checked = 0
    maintenance_entries_checked = 0
    stockpile_capacity_entries_checked = 0
    production_methods_checked = 0
    manifests_checked = 0
    expected_cbg_paths: set[str] = set()

    for source_file in sorted(source_dir.glob("*.txt")):
        if source_file.name == "readme.txt":
            continue

        source_lines = source_file.read_text(encoding="utf-8-sig").splitlines()
        source_blocks = top_level_blocks(source_lines)
        stale_replace_file = output_dir / f"cbp_{source_file.name}"
        injected_file = output_dir / f"cbp_inject_{source_file.name}"
        exact_file = output_dir / source_file.name
        exact_cbg_path = f"in_game/common/building_types/{source_file.name}"
        injected_cbg_path = (
            f"in_game/common/building_types/cbp_inject_{source_file.name}"
        )

        try:
            expected_body, expected_changes, _building_count = transformer.transform_lines_with_plan(
                source_lines,
                source_basename=source_file.name,
                output_multiplier=(
                    output_multiplier
                    if args.generation_mode == "override"
                    else 1.0
                ),
                trade_capacity_multiplier=trade_capacity_multiplier,
                maintenance_multiplier=args.maintenance_multiplier,
                trade_building_maintenance_multiplier=args.trade_building_maintenance_multiplier,
                us07_trade_burghers_estate_power_multiplier=us07_multiplier,
                minting_income_multiplier=float(minting_multiplier),
                goods=goods_set,
                political_modifier_multiplier=0.75,
            )
            expected_body, foreign_changed = apply_foreign_trade_capacity_multiplier(
                expected_body,
                args.foreign_trade_capacity_multiplier,
            )
        except ValueError as error:
            failures.append(f"{source_file.name}: unsupported vanilla structure: {error}")
            continue

        changed_buildings = {change.building for change in expected_changes} | foreign_changed
        if args.generation_mode == "override":
            if not changed_buildings:
                if exact_file.exists():
                    failures.append(
                        f"{source_file.name}: override exists although no "
                        "transformation applies"
                    )
                continue

            expected_cbg_paths.add(exact_cbg_path)
            if not exact_file.is_file():
                failures.append(
                    f"Missing generated override-mode source: {exact_file.name}"
                )
                continue
            generated_text = exact_file.read_text(encoding="utf-8-sig")
            generated_lines = normalize_generator_whitespace(
                strip_generated_header(generated_text)
            )
            while generated_lines and not generated_lines[0].strip():
                generated_lines.pop(0)
            expected_lines = normalize_generator_whitespace(expected_body)
            while expected_lines and not expected_lines[0].strip():
                expected_lines.pop(0)
            if generated_lines != expected_lines:
                failures.append(
                    f"{source_file.name}: override-mode output differs from "
                    "the complete parser-derived transformed source"
                )
            if re.search(
                r"^[ \t]*(?:REPLACE|INJECT|TRY_INJECT):",
                generated_text,
                re.MULTILINE,
            ):
                failures.append(
                    f"{source_file.name}: override mode must contain plain "
                    "Vanilla object keys"
                )

            manifest = cbg_files.get(exact_cbg_path)
            if manifest is None:
                failures.append(f"Missing CBG manifest entry: {exact_cbg_path}")
            else:
                if manifest.get("database_entry_mode") is not None:
                    failures.append(
                        f"{exact_cbg_path}: override manifest must not declare "
                        "a database-entry mode"
                    )
                manifest_objects = {
                    entry.get("object")
                    for entry in manifest.get("transformations", [])
                    if isinstance(entry, dict) and entry.get("object")
                }
                if manifest_objects != changed_buildings:
                    failures.append(
                        f"{exact_cbg_path}: manifest object scope mismatch "
                        f"expected={sorted(changed_buildings)} "
                        f"actual={sorted(manifest_objects)}"
                    )
                if manifest.get("vanilla_sha256") != hashlib.sha256(
                    source_file.read_bytes()
                ).hexdigest():
                    failures.append(
                        f"{exact_cbg_path}: Vanilla fingerprint mismatch"
                    )
                if manifest.get("generated_sha256") != hashlib.sha256(
                    exact_file.read_bytes()
                ).hexdigest():
                    failures.append(
                        f"{exact_cbg_path}: generated fingerprint mismatch"
                    )
                manifests_checked += 1

            generated_blocks = top_level_blocks(generated_lines)
            expected_blocks = top_level_blocks(expected_lines)
            for building in sorted(changed_buildings):
                expected_block = expected_blocks.get(building)
                generated_block = generated_blocks.get(building)
                if expected_block is None or generated_block is None:
                    failures.append(
                        f"{source_file.name}:{building}: missing override object"
                    )
                    continue
                if generated_block != expected_block:
                    failures.append(
                        f"{source_file.name}:{building}: override object differs "
                        "from the configured target"
                    )
                    continue
                expected_entries = maintenance_entries(expected_block, goods_set)
                generated_entries = maintenance_entries(generated_block, goods_set)
                if maintenance_entries(
                    source_blocks.get(building, []),
                    goods_set,
                ):
                    source_files_with_maintenance += 1
                if expected_entries != generated_entries:
                    failures.append(
                        f"{source_file.name}:{building}: maintenance entries "
                        "differ from the configured target"
                    )
                maintenance_entries_checked += len(generated_entries)
                source_stockpile = active_stockpile_capacity_entries(
                    source_blocks.get(building, [])
                )
                if source_stockpile:
                    active = active_stockpile_capacity_entries(generated_block)
                    commented = commented_stockpile_capacity_entries(generated_block)
                    if active or commented != source_stockpile:
                        failures.append(
                            f"{source_file.name}:{building}: override-mode "
                            "stockpile comment must remove the active Vanilla "
                            "value while preserving its provenance"
                        )
                    else:
                        stockpile_capacity_entries_checked += len(commented)
                objects_checked += 1
            generated_files_checked += 1
            exact_files_checked += 1
            continue

        structural_body, structural_changes, _ = (
            transformer.transform_lines_with_plan(
                source_lines,
                source_basename=source_file.name,
                output_multiplier=1.0,
                trade_capacity_multiplier=1.0,
                maintenance_multiplier=args.maintenance_multiplier,
                trade_building_maintenance_multiplier=(
                    args.trade_building_maintenance_multiplier
                ),
                us07_trade_burghers_estate_power_multiplier=1.0,
                minting_income_multiplier=1.0,
                goods=goods_set,
                political_modifier_multiplier=1.0,
                comment_stockpile_capacity=False,
            )
        )
        structural_buildings = {
            change.building
            for change in structural_changes
            if requires_exact_file_override(change)
        }
        production_methods = build_prefixed_production_methods(
            source_lines,
            output_multiplier,
        )
        additive_fields_by_building = {
            building: changed_additive_fields(
                source_lines,
                expected_body,
                building,
            )
            for building in sorted(changed_buildings)
        }
        additive_fields_by_building = {
            building: fields
            for building, fields in additive_fields_by_building.items()
            if fields
        }
        all_changed_buildings = (
            structural_buildings
            | set(additive_fields_by_building)
            | set(production_methods)
        )
        if not all_changed_buildings:
            if (
                stale_replace_file.exists()
                or injected_file.exists()
                or exact_file.exists()
            ):
                failures.append(
                    f"{source_file.name}: override exists although no transformation applies"
                )
            continue

        if stale_replace_file.is_file():
            failures.append(
                f"{stale_replace_file.name}: REPLACE:<building> is runtime-unsafe "
                "for Vanilla nested production-method registries"
            )
        expected_lines = normalize_generator_whitespace(structural_body)
        while expected_lines and not expected_lines[0].strip():
            expected_lines.pop(0)
        expected_blocks = top_level_blocks(expected_lines)

        generated_blocks: dict[str, list[str]] = {}
        inject_buildings: set[str] = set()
        if structural_buildings:
            expected_cbg_paths.add(exact_cbg_path)
            if not exact_file.is_file():
                failures.append(
                    "Missing generated exact-path override for structural source: "
                    f"{exact_file.name}"
                )
            else:
                generated_text = exact_file.read_text(encoding="utf-8-sig")
                generated_lines = normalize_generator_whitespace(
                    strip_generated_header(generated_text)
                )
                while generated_lines and not generated_lines[0].strip():
                    generated_lines.pop(0)
                generated_blocks = top_level_blocks(generated_lines)
                if generated_lines != expected_lines:
                    failures.append(
                        f"{source_file.name}: exact-path output differs from the "
                        "parser-derived complete transformed source"
                    )
                if re.search(
                    r"^[ \t]*(?:REPLACE|INJECT|TRY_INJECT):",
                    generated_text,
                    re.MULTILINE,
                ):
                    failures.append(
                        f"{source_file.name}: exact-path output must contain plain "
                        "Vanilla object keys"
                    )
                manifest = cbg_files.get(exact_cbg_path)
                if manifest is None:
                    failures.append(
                        f"Missing CBG manifest entry: {exact_cbg_path}"
                    )
                else:
                    if manifest.get("database_entry_mode") is not None:
                        failures.append(
                            f"{exact_cbg_path}: exact-path manifest must not "
                            "declare a database-entry mode"
                        )
                    if manifest.get("vanilla_sha256") != hashlib.sha256(
                        source_file.read_bytes()
                    ).hexdigest():
                        failures.append(
                            f"{exact_cbg_path}: Vanilla fingerprint mismatch"
                        )
                    if manifest.get("generated_sha256") != hashlib.sha256(
                        exact_file.read_bytes()
                    ).hexdigest():
                        failures.append(
                            f"{exact_cbg_path}: generated fingerprint mismatch"
                        )
                    manifest_objects = {
                        entry.get("object")
                        for entry in manifest.get("transformations", [])
                        if isinstance(entry, dict) and entry.get("object")
                    }
                    if manifest_objects != structural_buildings:
                        failures.append(
                            f"{exact_cbg_path}: manifest object scope mismatch "
                            f"expected={sorted(structural_buildings)} "
                            f"actual={sorted(manifest_objects)}"
                        )
                    manifests_checked += 1
                generated_files_checked += 1
                exact_files_checked += 1
        else:
            if exact_file.exists():
                failures.append(
                    f"{source_file.name}: exact-path output exists although all "
                    "changes are proven additive"
                )

        for building in sorted(structural_buildings):
            expected_block = expected_blocks.get(building)
            generated_block = generated_blocks.get(building)
            source_block = source_blocks.get(building, [])
            if expected_block is None or generated_block is None:
                failures.append(f"{source_file.name}:{building}: missing object block")
                continue
            if generated_block != expected_block:
                failures.append(
                    f"{source_file.name}:{building}: generated building body differs "
                    "from the parser-derived complete building object"
                )
                continue

            expected_entries = maintenance_entries(expected_block, goods_set)
            generated_entries = maintenance_entries(generated_block, goods_set)
            source_entries = maintenance_entries(source_block, goods_set)
            if source_entries:
                source_files_with_maintenance += 1
            if len(expected_entries) != len(generated_entries):
                failures.append(
                    f"{source_file.name}:{building}: maintenance entry count mismatch "
                    f"expected={len(expected_entries)} generated={len(generated_entries)}"
                )
            else:
                for ordinal, (
                    (expected_key, expected_value, expected_trade_building),
                    (generated_key, generated_value, generated_trade_building),
                ) in enumerate(zip(expected_entries, generated_entries), start=1):
                    if expected_key != generated_key:
                        failures.append(
                            f"{source_file.name}:{building}: maintenance entry #{ordinal} key mismatch "
                            f"expected={expected_key} generated={generated_key}"
                        )
                        continue
                    if expected_trade_building != generated_trade_building:
                        failures.append(
                            f"{source_file.name}:{building}: {expected_key} maintenance entry #{ordinal} "
                            "trade-building classification mismatch"
                        )
                        continue
                    if not compare_float(generated_value, expected_value):
                        failures.append(
                            f"{source_file.name}:{building}: {expected_key} maintenance entry #{ordinal} "
                            f"expected {expected_value:g}, found {generated_value:g}"
                        )
                    maintenance_entries_checked += 1

            objects_checked += 1

        fields_in_source = sorted({
            field
            for fields in additive_fields_by_building.values()
            for field in fields
        })
        for field in fields_in_source:
            field_buildings = {
                building
                for building, fields in additive_fields_by_building.items()
                if field in fields
            }
            field_name = f"cbp_{field}_{source_file.name}"
            field_file = output_dir / field_name
            field_cbg_path = f"in_game/common/building_types/{field_name}"
            expected_cbg_paths.add(field_cbg_path)
            if not field_file.is_file():
                failures.append(f"Missing field-family INJECT: {field_name}")
                continue
            field_text = field_file.read_text(encoding="utf-8-sig")
            field_lines = normalize_generator_whitespace(
                strip_database_entry_modes(strip_generated_header(field_text))
            )
            field_blocks = top_level_blocks(field_lines)
            if set(field_blocks) != field_buildings:
                failures.append(
                    f"{field_name}: object scope mismatch expected="
                    f"{sorted(field_buildings)} actual={sorted(field_blocks)}"
                )
            inject_entries = set(re.findall(
                r"^[ \t]*INJECT:([A-Za-z0-9_.:-]+)[ \t]*=",
                field_text,
                re.MULTILINE,
            ))
            if inject_entries != field_buildings:
                failures.append(
                    f"{field_name}: every field-family object must use INJECT"
                )
            for building in sorted(field_buildings):
                expected_fragment = normalize_generator_whitespace(
                    build_injection_fragment(
                        source_lines,
                        expected_body,
                        building,
                        additive_fields={field},
                    )
                )
                if field_blocks.get(building) != expected_fragment:
                    failures.append(
                        f"{field_name}:{building}: additive delta differs from "
                        "the parser-derived target"
                    )
                if field == "maximum_stockpile_capacity":
                    source_stockpile = active_stockpile_capacity_entries(
                        source_blocks.get(building, [])
                    )
                    if not source_stockpile:
                        failures.append(
                            f"{field_name}:{building}: stockpile cancellation "
                            "has no Vanilla value"
                        )
                    else:
                        stockpile_capacity_entries_checked += len(source_stockpile)
                objects_checked += 1
            manifest = cbg_files.get(field_cbg_path)
            if manifest is None:
                failures.append(f"Missing CBG manifest entry: {field_cbg_path}")
            else:
                manifest_objects = {
                    entry.get("object")
                    for entry in manifest.get("transformations", [])
                    if isinstance(entry, dict) and entry.get("object")
                }
                if (
                    manifest.get("database_entry_mode") != "INJECT"
                    or manifest_objects != field_buildings
                ):
                    failures.append(
                        f"{field_cbg_path}: invalid INJECT manifest contract"
                    )
                manifests_checked += 1
            generated_files_checked += 1
            injected_files_checked += 1

        if production_methods:
            production_name = (
                f"cbp_us09_production_methods_{source_file.name}"
            )
            production_file = output_dir / production_name
            production_cbg_path = (
                f"in_game/common/building_types/{production_name}"
            )
            expected_cbg_paths.add(production_cbg_path)
            if not production_file.is_file():
                failures.append(
                    f"Missing production-method INJECT: {production_name}"
                )
            else:
                production_text = production_file.read_text(encoding="utf-8-sig")
                production_lines = normalize_generator_whitespace(
                    strip_database_entry_modes(
                        strip_generated_header(production_text)
                    )
                )
                production_blocks = top_level_blocks(production_lines)
                if set(production_blocks) != set(production_methods):
                    failures.append(
                        f"{production_name}: production object scope mismatch"
                    )
                for building, methods in sorted(production_methods.items()):
                    expected_fragment = normalize_generator_whitespace(
                        build_injection_fragment(
                            source_lines,
                            expected_body,
                            building,
                            methods,
                            additive_fields=set(),
                        )
                    )
                    if production_blocks.get(building) != expected_fragment:
                        failures.append(
                            f"{production_name}:{building}: production-method "
                            "fragment differs from target"
                        )
                    production_methods_checked += len(methods)
                manifest = cbg_files.get(production_cbg_path)
                if manifest is None:
                    failures.append(
                        f"Missing CBG manifest entry: {production_cbg_path}"
                    )
                else:
                    if manifest.get("database_entry_mode") != "INJECT":
                        failures.append(
                            f"{production_cbg_path}: manifest must declare INJECT"
                        )
                    manifests_checked += 1
                generated_files_checked += 1
                injected_files_checked += 1

    manifested_building_paths = {
        path for path in cbg_files if path.startswith("in_game/common/building_types/")
    }
    unexpected_cbg_paths = sorted(manifested_building_paths - expected_cbg_paths)
    if unexpected_cbg_paths:
        failures.append(
            "CBG manifest contains building outputs without a parser-derived change plan: "
            + ", ".join(unexpected_cbg_paths)
        )

    stale_replace_outputs = sorted(
        path.name
        for path in output_dir.glob("*.txt")
        if re.search(
            r"^[ \t]*(?:REPLACE|TRY_INJECT):",
            path.read_text(encoding="utf-8-sig"),
            re.MULTILINE,
        )
    )
    if stale_replace_outputs:
        failures.append(
            "Runtime-unsafe REPLACE:<building> outputs remain: "
            + ", ".join(stale_replace_outputs)
        )

    nested_mode_pattern = re.compile(
        r"^[ \t]*(?:REPLACE|INJECT|TRY_INJECT):"
        r"(?:unique_production_methods|production_methods|"
        r"possible_production_methods)[ \t]*=",
        re.MULTILINE,
    )
    for generated_file in sorted(output_dir.glob("*.txt")):
        if nested_mode_pattern.search(
            generated_file.read_text(encoding="utf-8-sig")
        ):
            failures.append(
                f"{generated_file.name}: nested production-method containers "
                "must not use a database-entry prefix"
            )

    if failures:
        print("CBP US-08 building maintenance validation failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        return 1

    print(
        "CBP US-08 building maintenance validation passed: "
        f"{source_files_with_maintenance} maintenance objects, "
        f"{generated_files_checked} generated building files "
        f"({exact_files_checked} exact-path, {injected_files_checked} INJECT), "
        f"{objects_checked} changed objects, "
        f"{maintenance_entries_checked} maintenance entries checked, "
        f"{production_methods_checked} prefixed production methods checked, "
        f"{stockpile_capacity_entries_checked} disabled stockpile-capacity lines checked, "
        f"{manifests_checked} building manifests checked."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
