#!/usr/bin/env python3
"""Export CBG selected-object rules for US-09 RGO expansion prices."""

from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import ASSIGNMENT, field_matches, scan_objects


TARGETS = (
    "expand_rgo_mining", "expand_rgo_farming", "expand_rgo_hunting",
    "expand_rgo_gathering", "expand_rgo_forestry",
)
SOURCE = "in_game/common/prices/00_hardcoded.txt"


def compact(value: Decimal, places: int) -> str:
    rendered = f"{value:.{places}f}".rstrip("0").rstrip(".")
    return rendered if "." in rendered else f"{rendered}.0"


def build_spec(game_root: Path, percent: Decimal) -> dict[str, object]:
    factor = Decimal(1) / (Decimal(1) + percent / Decimal(100))
    header = [
        "# Generated by tools/generate_us09_economy_overrides.sh.",
        "# Do not edit manually.",
        "# Source: <EU5_GAME_COMMON_DIR>/prices/00_hardcoded.txt",
        f"# RGO expansion gold multiplier: {compact(factor, 10)} (inverse of 1 + {compact(percent, 10).removesuffix('.0')}%)",
    ]
    lines = (game_root / SOURCE).read_text(encoding="utf-8-sig").splitlines(keepends=True)
    objects = {obj.path: obj for obj in scan_objects(lines)}
    replacements: dict[str, str] = {}
    for name in TARGETS:
        matches = field_matches(lines, objects[(name,)], "gold")
        if len(matches) != 1 or not (match := ASSIGNMENT.match(lines[matches[0]].rstrip("\r\n"))):
            raise ValueError(f"Expected one numeric gold field in {name}")
        adjusted = (Decimal(match.group("value")) * factor).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        replacements[name] = compact(adjusted, 2)
    return {
        "schema_version": 1,
        "mod_id": "cbp-us09-rgo-prices",
        "transformations": [
            {
                "file": SOURCE,
                "output_file": SOURCE,
                "render_mode": "selected_objects",
                "header": header,
                "trailing_blank_lines": 1,
                "object": name,
                "field": "gold",
                "operation": "replace",
                "value": replacements[name],
                "provenance": "preserve",
            }
            for name in TARGETS
        ],
        "scope_contract": {"owned_outputs": [SOURCE], "phase": "rgo-prices"},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--percent", type=Decimal, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(build_spec(args.game_root, args.percent), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Generated {args.output} with US-09 RGO-price CBG policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
