#!/usr/bin/env python3
"""Compile #188 building edge-case analysis into a focused CBG specification."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.transform_cbp_economy_building_overrides import (
    ASSIGNMENT,
    BuildingChange,
    find_named_blocks,
    format_decimal,
    render_generated_text,
    top_level_buildings,
    transform_lines_with_plan,
)

TRADE_CAPACITY_ASSIGNMENT = re.compile(
    r"^(\s*merchant_capacity_from_building\s*=\s*)"
    r"(-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+))(\s*(?:#.*)?)$"
)
FOREIGN_MARKER = re.compile(r"\bis_foreign\s*=\s*yes\b")
ADDITIVE_MODIFIER_FIELDS = {
    "local_burghers_estate_power",
    "local_merchant_capacity",
    "maximum_stockpile_capacity",
    "merchant_capacity_from_building",
    "minting_income_factor",
    "monthly_devotion",
    "monthly_horde_unity",
    "monthly_legitimacy",
    "monthly_republican_tradition",
    "monthly_tribal_cohesion",
}
MODIFIER_BLOCKS = {
    "capital_country_modifier",
    "capital_modifier",
    "foreign_country_modifier",
    "market_center_modifier",
    "modifier",
    "raw_modifier",
}
UNLOCK_PRODUCTION_METHOD = re.compile(
    r"^\s*unlock_production_method\s*=\s*([A-Za-z0-9_.:-]+)"
)


def load_goods(repo_root: Path) -> set[str]:
    text = (repo_root / "tools/cbp_goods.sh").read_text(encoding="utf-8")
    match = re.search(r"cbp_goods=\(\s*(.*?)\s*\)", text, re.DOTALL)
    if not match:
        raise ValueError("tools/cbp_goods.sh does not contain cbp_goods=(...)")
    body = "\n".join(line.split("#", 1)[0] for line in match.group(1).splitlines())
    goods = set(body.split())
    if not goods or any(not re.fullmatch(r"[a-z][a-z0-9_]*", good) for good in goods):
        raise ValueError("tools/cbp_goods.sh contains an invalid cbp_goods token")
    return goods


def apply_foreign_trade_capacity_multiplier(
    lines: list[str], multiplier: float
) -> tuple[list[str], set[str]]:
    """Compose a foreign-building multiplier after the global US-09 multiplier."""
    result = list(lines)
    changed_buildings: set[str] = set()
    for building in top_level_buildings(result):
        block = result[building.start : building.end + 1]
        if not any(FOREIGN_MARKER.search(line.split("#", 1)[0]) for line in block):
            continue
        for index in range(building.start, building.end + 1):
            match = TRADE_CAPACITY_ASSIGNMENT.match(result[index])
            if not match:
                continue
            old_value = float(match.group(2))
            new_value = format_decimal(old_value * multiplier)
            suffix = match.group(3)
            trace = f"# FOREIGN BUILDING x{format_decimal(multiplier)}"
            existing_comment = suffix.strip().lstrip("# ").strip()
            suffix = f" {trace}"
            if existing_comment:
                suffix += f"; {existing_comment}"
            result[index] = f"{match.group(1)}{new_value}{suffix}"
            changed_buildings.add(building.key)
    return result, changed_buildings


def header_for(
    source_basename: str,
    *,
    output_multiplier: float,
    trade_capacity_multiplier: float,
    foreign_trade_capacity_multiplier: float,
    maintenance_multiplier: float,
    trade_maintenance_multiplier: float,
    estate_power_multiplier: float,
    minting_multiplier: float,
    political_multiplier: float,
) -> list[str]:
    rendered = render_generated_text(
        [],
        source_label=f"<EU5_GAME_COMMON_DIR>/building_types/{source_basename}",
        source_basename=source_basename,
        output_multiplier=output_multiplier,
        trade_capacity_multiplier=trade_capacity_multiplier,
        maintenance_multiplier=maintenance_multiplier,
        trade_building_maintenance_multiplier=trade_maintenance_multiplier,
        us07_trade_burghers_estate_power_multiplier=estate_power_multiplier,
        minting_income_multiplier=minting_multiplier,
        political_modifier_multiplier=political_multiplier,
    )
    header = rendered.splitlines()[:-1]
    header[0] = (
        "# Generated by "
        "tools/cbg/adapters/cbp/generate_cbp_cbg_building_spec.py."
    )
    header.insert(
        5,
        "# Foreign-building merchant capacity multiplier: "
        f"{format_decimal(foreign_trade_capacity_multiplier)}",
    )
    return header


def requires_exact_file_override(change: BuildingChange) -> bool:
    """Return whether a Vanilla-file override is required for this mutation."""
    return (
        change.action in {"disable", "remove"}
        or change.field.startswith("maintenance:")
    )


def build_prefixed_production_methods(
    source_lines: list[str],
    output_multiplier: float,
) -> dict[str, list[list[str]]]:
    """Clone productive inline methods as prefixed, higher-output alternatives."""
    if output_multiplier == 1:
        return {}

    blocks = find_named_blocks(source_lines)
    variants: dict[str, list[list[str]]] = {}
    seen_methods: set[str] = set()
    for index, line in enumerate(source_lines):
        match = ASSIGNMENT.match(line)
        if match is None or match.group(2) != "output":
            continue
        ancestors = sorted(
            (block for block in blocks if block.start <= index <= block.end),
            key=lambda block: block.depth,
        )
        if len(ancestors) < 3 or ancestors[-2].key != "unique_production_methods":
            raise ValueError(
                f"output at line {index + 1} is not inside "
                "building.unique_production_methods.<method>"
            )
        building = ancestors[0].key
        method = ancestors[-1]
        prefixed_method = f"cbp_us09_{method.key}"
        if prefixed_method in seen_methods:
            raise ValueError(f"duplicate generated production method: {prefixed_method}")
        seen_methods.add(prefixed_method)

        method_lines = list(source_lines[method.start : method.end + 1])
        start_match = re.match(
            r"^(\s*)" + re.escape(method.key) + r"(\s*=\s*\{.*)$",
            method_lines[0],
        )
        if start_match is None:
            raise ValueError(
                f"cannot rename production method {building}.{method.key}"
            )
        method_lines[0] = (
            f"{start_match.group(1)}{prefixed_method}{start_match.group(2)}"
        )

        relative_output_index = index - method.start
        old_output = match.group(3)
        new_output = format_decimal(float(old_output) * output_multiplier)
        suffix = match.group(4)
        existing_comment = suffix.strip().lstrip("# ").strip()
        suffix = f" # VANILLA = {old_output}"
        if existing_comment:
            suffix += f"; {existing_comment}"
        method_lines[relative_output_index] = (
            f"{match.group(1)}{new_output}{suffix}"
        )
        variants.setdefault(building, []).append(method_lines)
    return variants


def modifier_assignments(
    building_lines: list[str],
) -> dict[tuple[str, str], tuple[float, str]]:
    """Read additive modifier fields as ``(modifier block, field)`` values."""
    blocks = find_named_blocks(building_lines)
    assignments: dict[tuple[str, str], tuple[float, str]] = {}
    for index, line in enumerate(building_lines):
        match = ASSIGNMENT.match(line)
        if match is None or match.group(2) not in ADDITIVE_MODIFIER_FIELDS:
            continue
        ancestors = sorted(
            (
                block
                for block in blocks
                if block.start <= index <= block.end
            ),
            key=lambda block: block.depth,
        )
        path = tuple(block.key for block in ancestors[1:])
        if len(path) != 1 or path[0] not in MODIFIER_BLOCKS:
            raise ValueError(
                f"{ancestors[0].key}.{match.group(2)} is not in one supported "
                "additive modifier block"
            )
        key = (path[0], match.group(2))
        if key in assignments:
            raise ValueError(
                f"{ancestors[0].key} contains duplicate modifier assignment "
                f"{path[0]}.{match.group(2)}"
            )
        assignments[key] = (float(match.group(3)), match.group(3))
    return assignments


def build_injection_fragment(
    source_lines: list[str],
    transformed_lines: list[str],
    building: str,
    production_methods: list[list[str]] | None = None,
    additive_fields: set[str] | None = None,
) -> list[str]:
    """Render one sparse INJECT fragment for additive fields and CBP methods."""
    source_blocks = {block.key: block for block in top_level_buildings(source_lines)}
    transformed_blocks = {
        block.key: block for block in top_level_buildings(transformed_lines)
    }
    source = source_blocks[building]
    transformed = transformed_blocks[building]
    before = modifier_assignments(source_lines[source.start : source.end + 1])
    after = modifier_assignments(
        transformed_lines[transformed.start : transformed.end + 1]
    )

    deltas: dict[str, list[tuple[str, str]]] = {}
    for key, (old_value, old_literal) in before.items():
        modifier_block, field = key
        if additive_fields is not None and field not in additive_fields:
            continue
        target = after.get(key)
        if target is None:
            if field != "maximum_stockpile_capacity":
                raise ValueError(
                    f"{building}.{modifier_block}.{field} disappeared from a "
                    "supposedly additive injection"
                )
            target_value = 0.0
            target_literal = "0"
        else:
            target_value, target_literal = target
        if target_value == old_value:
            continue
        delta = format_decimal(target_value - old_value)
        trace = f"# VANILLA = {old_literal}; TARGET = {target_literal}"
        deltas.setdefault(modifier_block, []).append(
            (field, f"{delta} {trace}")
        )

    production_methods = production_methods or []
    if not deltas and not production_methods:
        raise ValueError(
            f"{building} was selected for INJECT but has no additive content"
        )

    rendered = [f"{building} = {{"]
    for modifier_block in sorted(deltas):
        rendered.append(f"\t{modifier_block} = {{")
        for field, value in sorted(deltas[modifier_block]):
            rendered.append(f"\t\t{field} = {value}")
        rendered.append("\t}")
    if production_methods:
        rendered.append("\tunique_production_methods = {")
        for method_lines in production_methods:
            rendered.extend(method_lines)
        rendered.append("\t}")
    rendered.append("}")
    return rendered


def changed_additive_fields(
    source_lines: list[str],
    transformed_lines: list[str],
    building: str,
) -> set[str]:
    """Return additive fields whose configured final value differs from Vanilla."""
    source_blocks = {block.key: block for block in top_level_buildings(source_lines)}
    transformed_blocks = {
        block.key: block for block in top_level_buildings(transformed_lines)
    }
    source = source_blocks[building]
    transformed = transformed_blocks[building]
    before = modifier_assignments(source_lines[source.start : source.end + 1])
    after = modifier_assignments(
        transformed_lines[transformed.start : transformed.end + 1]
    )
    changed: set[str] = set()
    for key, (old_value, _old_literal) in before.items():
        _modifier_block, field = key
        target = after.get(key)
        if target is None:
            if field != "maximum_stockpile_capacity":
                raise ValueError(
                    f"{building}.{field} disappeared outside the supported "
                    "stockpile cancellation rule"
                )
            changed.add(field)
        elif target[0] != old_value:
            changed.add(field)
    return changed


def build_unlock_injections(
    game_root: Path,
    localized_methods: dict[str, str],
) -> tuple[list[dict[str, object]], list[str], int]:
    """Mirror Vanilla advance unlocks for their CBP production alternatives."""
    generated_for_vanilla = {
        vanilla: generated for generated, vanilla in localized_methods.items()
    }
    transformations: list[dict[str, object]] = []
    outputs: list[str] = []
    unlock_count = 0
    advance_dir = game_root / "in_game/common/advances"
    for source in sorted(advance_dir.glob("*.txt")):
        source_lines = source.read_text(encoding="utf-8-sig").splitlines()
        blocks = find_named_blocks(source_lines)
        by_advance: dict[str, list[str]] = {}
        for index, line in enumerate(source_lines):
            match = UNLOCK_PRODUCTION_METHOD.match(line.split("#", 1)[0])
            if match is None:
                continue
            generated = generated_for_vanilla.get(match.group(1))
            if generated is None:
                continue
            ancestors = sorted(
                (
                    block
                    for block in blocks
                    if block.start <= index <= block.end
                ),
                key=lambda block: block.depth,
            )
            if not ancestors or ancestors[0].depth != 0:
                raise ValueError(
                    f"{source.name}:{index + 1}: production-method unlock is "
                    "outside a top-level advance"
                )
            by_advance.setdefault(ancestors[0].key, []).append(generated)
            unlock_count += 1
        if not by_advance:
            continue

        relative = f"in_game/common/advances/{source.name}"
        output = f"in_game/common/advances/cbp_inject_us09_{source.name}"
        header = [
            "# Generated by tools/cbg/adapters/cbp/generate_cbp_cbg_building_spec.py.",
            "# Mirrors Vanilla production-method unlock timing for CBP alternatives.",
        ]
        for advance, methods in sorted(by_advance.items()):
            value = [f"{advance} = {{"]
            for method in methods:
                value.append(f"\tunlock_production_method = {method}")
            value.append("}")
            transformations.append({
                "file": relative,
                "object": advance,
                "field": "__object__",
                "operation": "replace_object",
                "value": value,
                "provenance": "preserve",
                "render_mode": "inject_objects",
                "output_file": output,
                "header": header,
            })
        outputs.append(output)
    return transformations, outputs, unlock_count


def build_spec(args: argparse.Namespace) -> dict[str, object]:
    common_dir = args.game_root / "in_game/common"
    goods = load_goods(args.repo_root)
    generation_mode = getattr(args, "generation_mode", "override")
    if generation_mode not in {"override", "compatibility"}:
        raise ValueError(
            "building generation mode must be override or compatibility"
        )
    transformations: list[dict[str, object]] = []
    owned_outputs: list[str] = []
    production_method_localizations: dict[str, str] = {}
    for source in sorted((common_dir / "building_types").glob("*.txt")):
        if source.name == "readme.txt":
            continue
        source_lines = source.read_text(encoding="utf-8-sig").splitlines()
        # Compatibility mode packages production as prefixed alternatives.
        # Override mode writes the configured output directly into the complete
        # same-path Vanilla source replacement.
        transformed, changes, _ = transform_lines_with_plan(
            source_lines,
            source_basename=source.name,
            output_multiplier=(
                args.output_multiplier
                if generation_mode == "override"
                else 1.0
            ),
            trade_capacity_multiplier=args.trade_capacity_multiplier,
            maintenance_multiplier=args.maintenance_multiplier,
            trade_building_maintenance_multiplier=args.trade_maintenance_multiplier,
            us07_trade_burghers_estate_power_multiplier=args.estate_power_multiplier,
            minting_income_multiplier=args.minting_multiplier,
            political_modifier_multiplier=args.political_multiplier,
            goods=goods,
        )
        transformed, foreign_changed = apply_foreign_trade_capacity_multiplier(
            transformed, args.foreign_trade_capacity_multiplier
        )
        changed_buildings = {change.building for change in changes} | foreign_changed
        relative = f"in_game/common/building_types/{source.name}"
        header = header_for(
            source.name,
            output_multiplier=args.output_multiplier,
            trade_capacity_multiplier=args.trade_capacity_multiplier,
            foreign_trade_capacity_multiplier=args.foreign_trade_capacity_multiplier,
            maintenance_multiplier=args.maintenance_multiplier,
            trade_maintenance_multiplier=args.trade_maintenance_multiplier,
            estate_power_multiplier=args.estate_power_multiplier,
            minting_multiplier=args.minting_multiplier,
            political_multiplier=args.political_multiplier,
        )
        if generation_mode == "override":
            if not changed_buildings:
                continue
            blocks = {
                block.key: block for block in top_level_buildings(transformed)
            }
            for building in sorted(changed_buildings):
                block = blocks[building]
                transformations.append({
                    "file": relative,
                    "object": building,
                    "field": "__object__",
                    "operation": "replace_object",
                    "value": transformed[block.start : block.end + 1],
                    "provenance": "preserve",
                    "render_mode": "verbatim_with_header",
                    "header": [
                        *header,
                        "# Generation mode: override",
                    ],
                })
            owned_outputs.append(relative)
            continue

        structural_transformed, structural_changes, _ = transform_lines_with_plan(
            source_lines,
            source_basename=source.name,
            output_multiplier=1.0,
            trade_capacity_multiplier=1.0,
            maintenance_multiplier=args.maintenance_multiplier,
            trade_building_maintenance_multiplier=args.trade_maintenance_multiplier,
            us07_trade_burghers_estate_power_multiplier=1.0,
            minting_income_multiplier=1.0,
            political_modifier_multiplier=1.0,
            goods=goods,
            comment_stockpile_capacity=False,
        )
        production_methods = build_prefixed_production_methods(
            source_lines,
            args.output_multiplier,
        )
        for methods in production_methods.values():
            for method_lines in methods:
                match = re.match(
                    r"^\s*(cbp_us09_([A-Za-z0-9_]+))\s*=\s*\{",
                    method_lines[0],
                )
                if match is None:
                    raise ValueError(
                        f"cannot derive localization key from {method_lines[0]!r}"
                    )
                production_method_localizations[match.group(1)] = match.group(2)
        structural_buildings = {
            change.building
            for change in structural_changes
            if requires_exact_file_override(change)
        }
        additive_fields_by_building = {
            building: changed_additive_fields(
                source_lines,
                transformed,
                building,
            )
            for building in sorted(changed_buildings)
        }
        additive_fields_by_building = {
            building: fields
            for building, fields in additive_fields_by_building.items()
            if fields
        }
        all_changed_buildings = (
            structural_buildings
            | set(additive_fields_by_building)
            | set(production_methods)
        )
        if not all_changed_buildings:
            continue
        structural_blocks = {
            block.key: block for block in top_level_buildings(structural_transformed)
        }
        header = [
            *header,
            "# Generation mode: compatibility",
        ]
        if structural_buildings:
            # REPLACE:<building> does not purge Vanilla nested production-method
            # registries in EU5 1.3. Replace the source file itself and compose
            # every changed building from that source into the same exact-path
            # output.
            for building in sorted(structural_buildings):
                block = structural_blocks[building]
                transformations.append({
                    "file": relative,
                    "object": building,
                    "field": "__object__",
                    "operation": "replace_object",
                    "value": structural_transformed[block.start : block.end + 1],
                    "provenance": "preserve",
                    "render_mode": "verbatim_with_header",
                    "header": header,
                })
            owned_outputs.append(relative)

        fields_in_source = sorted({
            field
            for fields in additive_fields_by_building.values()
            for field in fields
        })
        for field in fields_in_source:
            inject_relative = (
                f"in_game/common/building_types/cbp_{field}_{source.name}"
            )
            field_header = [
                *header,
                f"# Additive field family: {field}",
            ]
            for building, fields in sorted(additive_fields_by_building.items()):
                if field not in fields:
                    continue
                transformations.append({
                    "file": relative,
                    "object": building,
                    "field": "__object__",
                    "operation": "replace_object",
                    "value": build_injection_fragment(
                        source_lines,
                        transformed,
                        building,
                        additive_fields={field},
                    ),
                    "provenance": "preserve",
                    "render_mode": "inject_objects",
                    "output_file": inject_relative,
                    "header": field_header,
                })
            owned_outputs.append(inject_relative)

        if production_methods:
            production_relative = (
                "in_game/common/building_types/"
                f"cbp_us09_production_methods_{source.name}"
            )
            production_header = [
                *header,
                "# Additive family: prefixed US-09 production-method alternatives",
            ]
            for building in sorted(production_methods):
                transformations.append({
                    "file": relative,
                    "object": building,
                    "field": "__object__",
                    "operation": "replace_object",
                    "value": build_injection_fragment(
                        source_lines,
                        transformed,
                        building,
                        production_methods.get(building),
                        additive_fields=set(),
                    ),
                    "provenance": "preserve",
                    "render_mode": "inject_objects",
                    "output_file": production_relative,
                    "header": production_header,
                })
            owned_outputs.append(production_relative)
    unlock_rules, unlock_outputs, unlock_count = build_unlock_injections(
        args.game_root,
        production_method_localizations,
    )
    transformations.extend(unlock_rules)
    owned_outputs.extend(unlock_outputs)

    return {
        "schema_version": 1,
        "mod_id": "cbp-economy-rebalance-buildings",
        "business_rule": (
            "Apply configured production, global trade-capacity, foreign-building "
            "merchant-capacity, maintenance, minting, and stockpile policies to Vanilla buildings."
        ),
        "transformations": transformations,
        "scope_contract": {
            "owned_outputs": sorted(set(owned_outputs)),
            "phase": "building-overrides",
            "packaging": (
                (
                    "complete same-path Vanilla source overrides containing "
                    "every configured transformation"
                    if generation_mode == "override"
                    else
                    "prefixed CBP production-method alternatives and additive "
                    "modifier deltas use field-family sparse INJECT:<building> "
                    "files; exact-path Vanilla sources remain only for "
                    "non-additive structural and maintenance changes"
                )
            ),
            "generation_mode": generation_mode,
            "edge_case_compiler": "transform_cbp_economy_building_overrides.transform_lines_with_plan",
            "production_method_localizations": production_method_localizations,
            "mirrored_production_method_unlocks": unlock_count,
        },
    }


def render_localization(payload: dict[str, object]) -> str:
    """Render English labels while reusing each Vanilla method translation."""
    contract = payload.get("scope_contract", {})
    mappings = (
        contract.get("production_method_localizations", {})
        if isinstance(contract, dict)
        else {}
    )
    if not isinstance(mappings, dict):
        raise ValueError("production_method_localizations must be an object")
    lines = ["\ufeffl_english:"]
    for generated, vanilla in sorted(mappings.items()):
        lines.append(
            f' {generated}:0 "(CBP) Improved ${vanilla}$"'
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--localization-output", type=Path)
    parser.add_argument(
        "--generation-mode",
        choices=("override", "compatibility"),
        default="override",
        help=(
            "override writes complete same-path Vanilla files; compatibility "
            "isolates additive fields in sparse INJECT outputs"
        ),
    )
    parser.add_argument("--output-multiplier", type=float, required=True)
    parser.add_argument("--trade-capacity-multiplier", type=float, required=True)
    parser.add_argument("--foreign-trade-capacity-multiplier", type=float, default=2.0)
    parser.add_argument("--maintenance-multiplier", type=float, required=True)
    parser.add_argument("--trade-maintenance-multiplier", type=float, required=True)
    parser.add_argument("--estate-power-multiplier", type=float, default=0.5)
    parser.add_argument("--minting-multiplier", type=float, required=True)
    parser.add_argument("--political-multiplier", type=float, default=0.75)
    args = parser.parse_args()
    if args.foreign_trade_capacity_multiplier < 0:
        raise SystemExit("foreign trade-capacity multiplier must be non-negative")
    payload = build_spec(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if args.localization_output is not None:
        mappings = payload["scope_contract"]["production_method_localizations"]
        if mappings:
            args.localization_output.parent.mkdir(parents=True, exist_ok=True)
            args.localization_output.write_text(
                render_localization(payload),
                encoding="utf-8",
            )
        else:
            args.localization_output.unlink(missing_ok=True)
    exact_path_count = len({
        rule["file"]
        for rule in payload["transformations"]
        if rule.get("render_mode") == "verbatim_with_header"
    })
    exact_object_count = sum(
        rule.get("render_mode") == "verbatim_with_header"
        for rule in payload["transformations"]
    )
    inject_count = sum(
        rule.get("render_mode") == "inject_objects"
        for rule in payload["transformations"]
    )
    print(
        f"Generated {args.output} with {len(payload['transformations'])} "
        f"CBG building mutations ({exact_object_count} objects in "
        f"{exact_path_count} exact-path files, {inject_count} INJECT)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
