#!/usr/bin/env python3
"""Export CBG rules for the dedicated CBP location static-modifier output."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import display_path


SOURCE = "main_menu/common/static_modifiers/location.txt"
OUTPUT = "main_menu/common/static_modifiers/cbp_location.txt"
EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY = os.environ.get(
    "CBP_EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY",
    "5",
)
HEADER = [
    "# Generated by tools/generate_cbp_location_overrides.sh.",
    "# Source: <EU5_INSTALL_DIR>/game/main_menu/common/static_modifiers/location.txt",
    "# Vanilla blocks are preserved; only objects with effective CBP changes are included.",
]

ReplacementTarget = tuple[str, str, str]
ObjectRange = tuple[int, int]


def warn(message: str) -> None:
    rendered = f"[⚠️] {message}"
    if "NO_COLOR" not in os.environ and sys.stderr.isatty():
        rendered = f"\033[38;5;208m{rendered}\033[0m"
    print(rendered, file=sys.stderr)


def file_link(path: Path, line_number: int | None = None) -> str:
    link = path.expanduser().resolve().as_uri()
    return f"{link}#L{line_number}" if line_number is not None else link


def generated_output_link() -> str:
    return file_link(REPO_ROOT / OUTPUT)


def warn_development_object_removed(source: Path) -> None:
    warn(
        "Vanilla development static modifier is not exposed by this EU5 version.\n"
        f"  Vanilla source: {file_link(source)}\n"
        "  Configured rule: remove the active "
        "development.maximum_stockpile_capacity assignment.\n"
        "  Detected Vanilla change: the complete development object has been removed.\n"
        "  Generated result: no development override was emitted; all other location "
        "objects were processed normally.\n"
        f"  Generated output target: {generated_output_link()}\n"
        "  Status: non-fatal; CBP will continue generation according to the remaining "
        "configured rules."
    )


def warn_development_field_removed(source: Path) -> None:
    warn(
        "Vanilla development.maximum_stockpile_capacity is not exposed by this "
        "EU5 version.\n"
        f"  Vanilla source: {file_link(source)}\n"
        "  Configured rule: remove the active maximum_stockpile_capacity assignment "
        "from the development object.\n"
        "  Detected Vanilla change: the target line has been removed from the current "
        "Vanilla object.\n"
        "  Generated result: the development object was processed normally; the rule "
        "is already satisfied and the removed line was not reintroduced. No development "
        "override is emitted unless another effective development transformation remains.\n"
        f"  Generated output target: {generated_output_link()}\n"
        "  Status: non-fatal; CBP will continue generation according to the configured "
        "rules."
    )


def warn_development_value_changed(
    source: Path,
    line_number: int,
    current_value: str,
) -> None:
    rendered_line = (
        f"# maximum_stockpile_capacity = {current_value} "
        "# CBG: commented by cbp-location-static-modifiers"
    )
    warn(
        "Vanilla value changed: development.maximum_stockpile_capacity was "
        f"reviewed at {EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY} and is now "
        f"{current_value}.\n"
        f"  Vanilla source: {file_link(source, line_number)}\n"
        "  Configured rule: remove the active maximum_stockpile_capacity assignment "
        "from the development object.\n"
        f"  Current Vanilla line: maximum_stockpile_capacity = {current_value}\n"
        f"  Generated line: {rendered_line}\n"
        "  Generated result: the current Vanilla value was transformed according to "
        "the configured rule and the remainder of the development object was preserved.\n"
        f"  Generated output target: {generated_output_link()}\n"
        "  Status: non-fatal; CBP will continue and generate the file according to the "
        "configured rule."
    )


def numerically_equal(left: str, right: str) -> bool:
    try:
        return Decimal(left) == Decimal(right)
    except InvalidOperation:
        return left == right


def source_from_environment() -> Path | None:
    explicit = os.environ.get("EU5_GAME_LOCATION_STATIC_MODIFIERS_FILE")
    if explicit:
        return Path(explicit).expanduser().resolve()
    common = os.environ.get("EU5_GAME_COMMON_DIR")
    if not common:
        return None
    game_root = Path(common).expanduser().resolve().parent.parent
    return game_root / SOURCE


def scan_object_ranges(
    lines: list[str],
    target_names: set[str],
) -> dict[str, ObjectRange]:
    ranges: dict[str, ObjectRange] = {}
    index = 0
    while index < len(lines):
        match = re.match(r"^([A-Za-z0-9_]+)\s*=\s*\{", lines[index])
        if not match:
            index += 1
            continue
        name = match.group(1)
        depth = lines[index].count("{") - lines[index].count("}")
        end = index
        while depth > 0:
            end += 1
            if end >= len(lines):
                raise SystemExit(f"Unclosed top-level block: {name}")
            code = lines[end].split("#", 1)[0]
            depth += code.count("{") - code.count("}")
        if name in target_names:
            if name in ranges:
                raise SystemExit(
                    f"Vanilla static modifier block is defined more than once: {name}"
                )
            ranges[name] = (index, end)
        index = end + 1
    return ranges


def scalar_assignment(
    lines: list[str],
    object_name: str,
    object_range: ObjectRange,
    field: str,
) -> tuple[int, re.Match[str]] | None:
    assignment = re.compile(
        rf"^(?P<indent>\s*){re.escape(field)}\s*=\s*"
        rf"(?P<value>[^#\s]+)(?P<suffix>\s*(?:#.*)?)$"
    )
    start, end = object_range
    matches: list[tuple[int, re.Match[str]]] = []
    for line_index in range(start, end + 1):
        match = assignment.match(lines[line_index])
        if match:
            matches.append((line_index, match))
    if not matches:
        return None
    if len(matches) > 1:
        raise SystemExit(f"Vanilla {object_name}.{field} is defined more than once")
    return matches[0]


def replace_object_rule(object_name: str, block: list[str]) -> dict[str, object]:
    return {
        "file": SOURCE,
        "output_file": OUTPUT,
        "render_mode": "selected_objects",
        "header": HEADER,
        "object": object_name,
        "field": "__object__",
        "operation": "replace_object",
        "value": [line.rstrip(" \t") for line in block],
        "provenance": "preserve",
    }


def source_transformations(
    source: Path,
    replacement_targets: list[ReplacementTarget],
) -> list[dict[str, object]]:
    if not source.is_file():
        raise SystemExit(f"Vanilla location static modifiers file is missing: {source}")

    lines = source.read_text(encoding="utf-8-sig").splitlines()
    target_names = {object_name for object_name, _field, _value in replacement_targets}
    target_names.add("development")
    ranges = scan_object_ranges(lines, target_names)
    transformations: list[dict[str, object]] = []

    for object_name, field, replacement in replacement_targets:
        object_range = ranges.get(object_name)
        if object_range is None:
            raise SystemExit(f"Missing Vanilla static modifier block: {object_name}")
        assignment = scalar_assignment(lines, object_name, object_range, field)
        if assignment is None:
            raise SystemExit(f"Missing Vanilla field: {object_name}.{field}")
        line_index, match = assignment
        current_value = match.group("value")
        if numerically_equal(current_value, replacement):
            continue

        start, end = object_range
        block = list(lines[start : end + 1])
        local_index = line_index - start
        block[local_index] = (
            f"{match.group('indent')}{field} = {replacement}"
            f" # VANILLA VALUE IS {current_value}"
        )
        transformations.append(replace_object_rule(object_name, block))

    development_range = ranges.get("development")
    if development_range is None:
        warn_development_object_removed(source)
        return transformations

    development_assignment = scalar_assignment(
        lines,
        "development",
        development_range,
        "maximum_stockpile_capacity",
    )
    if development_assignment is None:
        warn_development_field_removed(source)
        return transformations

    line_index, match = development_assignment
    current_value = match.group("value")
    if not numerically_equal(
        current_value,
        EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY,
    ):
        warn_development_value_changed(source, line_index + 1, current_value)

    start, end = development_range
    block = list(lines[start : end + 1])
    local_index = line_index - start
    original = block[local_index].lstrip().rstrip()
    block[local_index] = (
        f"{match.group('indent')}# {original}"
        " # CBG: commented by cbp-location-static-modifiers"
    )
    transformations.append(replace_object_rule("development", block))
    return transformations


def configured_replacement_targets() -> list[ReplacementTarget]:
    return [
        (
            "expensive_food_in_location",
            "local_population_growth",
            os.environ.get("CBP_EXPENSIVE_FOOD_POPULATION_GROWTH", "0"),
        ),
        (
            "cheap_food_in_location",
            "local_population_growth",
            os.environ.get("CBP_CHEAP_FOOD_POPULATION_GROWTH", "0.001"),
        ),
        (
            "market_center",
            "maximum_stockpile_capacity",
            os.environ.get("CBP_MARKET_CENTER_STOCKPILE_CAPACITY", "0"),
        ),
        (
            "surplus_jobs",
            "local_migration_attraction",
            os.environ.get("CBP_SURPLUS_JOBS_MIGRATION_ATTRACTION", "0.2"),
        ),
    ]


def fallback_transformations() -> list[dict[str, object]]:
    transformations = [
        {
            "file": SOURCE,
            "output_file": OUTPUT,
            "render_mode": "selected_objects",
            "header": HEADER,
            "object": object_name,
            "field": field,
            "operation": "replace",
            "value": value,
            "provenance": "vanilla_value",
        }
        for object_name, field, value in configured_replacement_targets()
    ]
    transformations.append(
        {
            "file": SOURCE,
            "output_file": OUTPUT,
            "render_mode": "selected_objects",
            "header": HEADER,
            "object": "development",
            "field": "maximum_stockpile_capacity",
            "operation": "comment_out",
        }
    )
    return transformations


def build_spec(source_file: Path | None = None) -> dict[str, object]:
    transformations = (
        source_transformations(source_file, configured_replacement_targets())
        if source_file is not None
        else fallback_transformations()
    )
    return {
        "schema_version": 1,
        "mod_id": "cbp-location-static-modifiers",
        "business_rule": (
            "Apply CBP food-growth, market-center stockpile, surplus-jobs, "
            "and development stockpile policies while omitting no-op objects."
        ),
        "transformations": transformations,
        "scope_contract": {
            "owned_outputs": [OUTPUT],
            "phase": "location-static-modifiers",
            "whitespace_policy": "strip trailing horizontal whitespace from generated lines",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-file", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    source_file = args.source_file.resolve() if args.source_file else source_from_environment()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(build_spec(source_file), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {display_path(args.output)} with CBP location CBG policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
