#!/usr/bin/env python3
"""Export CBG selected-object rules for US-09 RGO expansion prices."""

from __future__ import annotations

import argparse
import json
import os
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import ASSIGNMENT, display_path, field_matches, scan_objects


TARGETS = (
    "expand_rgo_mining", "expand_rgo_farming", "expand_rgo_hunting",
    "expand_rgo_gathering", "expand_rgo_forestry",
)
SOURCE = "in_game/common/prices/00_hardcoded.txt"
DEFAULT_RGO_PRICE = Decimal("60")


def compact(value: Decimal, places: int) -> str:
    rendered = f"{value:.{places}f}".rstrip("0").rstrip(".")
    return rendered if "." in rendered else f"{rendered}.0"


def validate_price_percent(value: Decimal, label: str = "RGO_PRICE") -> Decimal:
    if not value.is_finite() or value < 0:
        raise ValueError(f"{label} must be a non-negative finite percentage; got {value}")
    return value


def legacy_offset_to_price_percent(offset: Decimal) -> Decimal:
    if not offset.is_finite() or offset <= -100:
        raise ValueError(
            "MODEU5_US09_RGO_PRICE_OFFSET_PERCENT must be greater than -100"
        )
    return Decimal(100) / (Decimal(1) + offset / Decimal(100))


def resolve_price_percent(
    explicit_price: Decimal | None,
    legacy_offset: Decimal | None,
) -> Decimal:
    if explicit_price is not None:
        return validate_price_percent(explicit_price, "--price-percent")

    configured_price = os.environ.get("RGO_PRICE")
    if configured_price is not None and configured_price.strip():
        return validate_price_percent(Decimal(configured_price), "RGO_PRICE")

    if legacy_offset is not None:
        return legacy_offset_to_price_percent(legacy_offset)

    configured_offset = os.environ.get("MODEU5_US09_RGO_PRICE_OFFSET_PERCENT")
    if configured_offset is not None and configured_offset.strip():
        return legacy_offset_to_price_percent(Decimal(configured_offset))

    return DEFAULT_RGO_PRICE


def build_spec(game_root: Path, price_percent: Decimal) -> dict[str, object]:
    price_percent = validate_price_percent(price_percent)
    factor = price_percent / Decimal(100)
    header = [
        "# Generated by tools/generate_us09_economy_overrides.sh.",
        "# Do not edit manually.",
        "# Source: <EU5_GAME_COMMON_DIR>/prices/00_hardcoded.txt",
        (
            f"# RGO expansion gold price: {compact(price_percent, 10)}% of Vanilla "
            f"(multiplier {compact(factor, 10)})"
        ),
    ]
    lines = (game_root / SOURCE).read_text(encoding="utf-8-sig").splitlines(keepends=True)
    objects = {obj.path: obj for obj in scan_objects(lines)}
    replacements: dict[str, str] = {}
    for name in TARGETS:
        matches = field_matches(lines, objects[(name,)], "gold")
        if len(matches) != 1 or not (match := ASSIGNMENT.match(lines[matches[0]].rstrip("\r\n"))):
            raise ValueError(f"Expected one numeric gold field in {name}")
        adjusted = (Decimal(match.group("value")) * factor).quantize(
            Decimal("0.01"),
            rounding=ROUND_HALF_UP,
        )
        replacements[name] = compact(adjusted, 2)
    return {
        "schema_version": 1,
        "mod_id": "cbp-us09-rgo-prices",
        "business_rule": (
            "Set RGO expansion gold prices to the configured percentage of Vanilla."
        ),
        "transformations": [
            {
                "file": SOURCE,
                "output_file": SOURCE,
                "render_mode": "selected_objects",
                "header": header,
                "trailing_blank_lines": 1,
                "object": name,
                "field": "gold",
                "operation": "replace",
                "value": replacements[name],
                "provenance": "preserve",
            }
            for name in TARGETS
        ],
        "scope_contract": {"owned_outputs": [SOURCE], "phase": "rgo-prices"},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument(
        "--price-percent",
        type=Decimal,
        help="RGO expansion price as a percentage of Vanilla (60 means Vanilla × 0.60).",
    )
    parser.add_argument(
        "--percent",
        type=Decimal,
        dest="legacy_offset",
        help=(
            "Deprecated inverse-offset input retained for compatibility. "
            "RGO_PRICE or --price-percent takes precedence."
        ),
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    price_percent = resolve_price_percent(args.price_percent, args.legacy_offset)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(build_spec(args.game_root, price_percent), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        f"Generated {display_path(args.output)} with US-09 RGO-price CBG policy "
        f"({compact(price_percent, 10)}% of Vanilla)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
