#!/usr/bin/env python3
"""Export CBG selected-object rules for US-09 RGO expansion prices."""

from __future__ import annotations

import argparse
import json
import os
import sys
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import ASSIGNMENT, display_path, field_matches, scan_objects


TARGETS = (
    "expand_rgo_mining", "expand_rgo_farming", "expand_rgo_hunting",
    "expand_rgo_gathering", "expand_rgo_forestry",
)
SOURCE = "in_game/common/prices/00_hardcoded.txt"
ABSOLUTE_MODE = "absolute"
LEGACY_INVERSE_PERCENT_MODE = "inverse_percent"
DEFAULT_PRICE = Decimal("60")
DEFAULT_PERCENT = Decimal("8")


def compact(value: Decimal, places: int) -> str:
    rendered = f"{value:.{places}f}".rstrip("0").rstrip(".")
    return rendered if "." in rendered else f"{rendered}.0"


def decimal_from_environment(name: str, default: Decimal) -> Decimal:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return Decimal(raw)
    except InvalidOperation as exc:
        raise ValueError(f"{name} must be numeric; got {raw}") from exc


def build_spec(
    game_root: Path,
    mode: str = ABSOLUTE_MODE,
    price: Decimal = DEFAULT_PRICE,
    percent: Decimal = DEFAULT_PERCENT,
) -> dict[str, object]:
    if mode not in {ABSOLUTE_MODE, LEGACY_INVERSE_PERCENT_MODE}:
        raise ValueError(f"Unsupported RGO price mode: {mode}")
    if price <= 0:
        raise ValueError(f"Absolute RGO price must be positive; got {price}")
    if percent <= -100:
        raise ValueError(f"Legacy RGO inverse offset must be greater than -100; got {percent}")

    lines = (game_root / SOURCE).read_text(encoding="utf-8-sig").splitlines(keepends=True)
    objects = {obj.path: obj for obj in scan_objects(lines)}
    source_values: dict[str, Decimal] = {}
    for name in TARGETS:
        obj = objects.get((name,))
        if obj is None:
            raise ValueError(f"Missing Vanilla RGO price object: {name}")
        matches = field_matches(lines, obj, "gold")
        if len(matches) != 1 or not (match := ASSIGNMENT.match(lines[matches[0]].rstrip("\r\n"))):
            raise ValueError(f"Expected one numeric gold field in {name}")
        source_values[name] = Decimal(match.group("value"))

    if mode == ABSOLUTE_MODE:
        replacements = {name: compact(price, 2) for name in TARGETS}
        header = [
            "# Generated by tools/generate_us09_economy_overrides.sh.",
            "# Do not edit manually.",
            "# Source: <EU5_GAME_COMMON_DIR>/prices/00_hardcoded.txt",
            f"# RGO expansion gold price: {compact(price, 2)} (absolute replacement)",
        ]
        business_rule = (
            "Set every RGO expansion gold price to the configured absolute target."
        )
    else:
        factor = Decimal(1) / (Decimal(1) + percent / Decimal(100))
        replacements = {
            name: compact(
                (source_values[name] * factor).quantize(
                    Decimal("0.01"), rounding=ROUND_HALF_UP
                ),
                2,
            )
            for name in TARGETS
        }
        header = [
            "# Generated by tools/generate_us09_economy_overrides.sh.",
            "# Do not edit manually.",
            "# Source: <EU5_GAME_COMMON_DIR>/prices/00_hardcoded.txt",
            f"# RGO expansion gold multiplier: {compact(factor, 10)} "
            f"(legacy inverse of 1 + {compact(percent, 10).removesuffix('.0')}%)",
        ]
        business_rule = (
            "Reduce RGO expansion prices using the legacy inverse-percentage rule."
        )

    return {
        "schema_version": 1,
        "mod_id": "cbp-us09-rgo-prices",
        "business_rule": business_rule,
        "policy": {
            "mode": mode,
            "absolute_price": compact(price, 2),
            "legacy_inverse_percent": compact(percent, 10),
        },
        "transformations": [
            {
                "file": SOURCE,
                "output_file": SOURCE,
                "render_mode": "selected_objects",
                "header": header,
                "trailing_blank_lines": 1,
                "object": name,
                "field": "gold",
                "operation": "replace",
                "value": replacements[name],
                "provenance": "preserve",
            }
            for name in TARGETS
        ],
        "scope_contract": {"owned_outputs": [SOURCE], "phase": "rgo-prices"},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument(
        "--mode",
        choices=(ABSOLUTE_MODE, LEGACY_INVERSE_PERCENT_MODE),
        default=os.environ.get("MODEU5_US09_RGO_PRICE_MODE", ABSOLUTE_MODE),
        help="absolute (default) or inverse_percent for the retained legacy rule",
    )
    parser.add_argument(
        "--price",
        type=Decimal,
        default=decimal_from_environment("MODEU5_US09_RGO_PRICE", DEFAULT_PRICE),
        help="absolute RGO expansion gold price (default: 60)",
    )
    parser.add_argument(
        "--percent",
        type=Decimal,
        default=decimal_from_environment(
            "MODEU5_US09_RGO_PRICE_OFFSET_PERCENT", DEFAULT_PERCENT
        ),
        help="legacy inverse percentage, used only in inverse_percent mode",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(
            build_spec(args.game_root, args.mode, args.price, args.percent),
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Generated {display_path(args.output)} with US-09 RGO-price CBG policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
