#!/usr/bin/env python3
"""Replace stackable building-cost discounts from laws, reforms and privileges.

The generated runtime keeps one visible country modifier whose dynamic size is:

    1 / (1 + factor * sum(vanilla_discount_contributions)) - 1

Only negative local_build_buildings_cost assignments found in laws,
government reforms and estate privileges contribute to the score.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path

ASSIGNMENT = re.compile(
    r"^(?P<indent>\s*)local_build_buildings_cost\s*=\s*"
    r"(?P<value>-(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+))(?P<suffix>\s*(?:#.*)?)$"
)
OBJECT_START = re.compile(r"^(?P<indent>\s*)(?P<key>[a-zA-Z0-9_]+)\s*=\s*\{")


@dataclass(frozen=True)
class SourceKind:
    directory: str
    trigger: str
    prefix: str


KINDS = (
    SourceKind("laws", "has_law", "law"),
    SourceKind("government_reforms", "has_government_reform", "government_reform"),
    SourceKind("estate_privileges", "has_estate_privilege", "estate_privilege"),
)


@dataclass(frozen=True)
class Contribution:
    kind: SourceKind
    object_key: str
    value: float
    file: str


def top_level_objects(lines: list[str]) -> list[tuple[str, int, int]]:
    result: list[tuple[str, int, int]] = []
    depth = 0
    current_key: str | None = None
    current_start = -1
    for index, line in enumerate(lines):
        code = line.split("#", 1)[0]
        if depth == 0:
            match = OBJECT_START.match(code)
            if match:
                current_key = match.group("key")
                current_start = index
        depth += code.count("{") - code.count("}")
        if current_key is not None and depth == 0:
            result.append((current_key, current_start, index))
            current_key = None
            current_start = -1
    return result


def comment_discount_lines(block: list[str]) -> tuple[list[str], float]:
    result = list(block)
    contribution = 0.0
    for index, line in enumerate(result):
        match = ASSIGNMENT.match(line)
        if not match:
            continue
        raw = float(match.group("value"))
        contribution += -raw
        result[index] = (
            f"{match.group('indent')}# {line.lstrip()} "
            "# CBP: reconciled through modeu5_balanced_building_cost"
        )
    return result, contribution


def render_static_modifier() -> str:
    return """# Generated by generate_cbp_cbg_building_cost_reconciliation.py.
modeu5_balanced_building_cost = {
\tgame_data = {
\t\tcategory = country
\t}
\tlocal_build_buildings_cost = 1
}
"""


def render_effect(contributions: list[Contribution], factor: float) -> str:
    lines = [
        "# Generated by generate_cbp_cbg_building_cost_reconciliation.py.",
        "modeu5_reconcile_building_cost = {",
        "\tremove_country_modifier = modeu5_balanced_building_cost",
        "\tset_variable = { name = modeu5_building_discount_score value = 0 }",
    ]
    for item in contributions:
        lines.extend([
            "\tif = {",
            "\t\tlimit = {",
            f"\t\t\t{item.kind.trigger} = {item.kind.prefix}:{item.object_key}",
            "\t\t}",
            "\t\tchange_variable = {",
            "\t\t\tname = modeu5_building_discount_score",
            f"\t\t\tadd = {item.value:.12g}",
            "\t\t}",
            "\t}",
        ])
    lines.extend([
        "\tchange_variable = {",
        "\t\tname = modeu5_building_discount_score",
        f"\t\tmultiply = {factor:.12g}",
        "\t}",
        "\tset_variable = { name = modeu5_building_cost_denominator value = 1 }",
        "\tchange_variable = {",
        "\t\tname = modeu5_building_cost_denominator",
        "\t\tadd = var:modeu5_building_discount_score",
        "\t}",
        "\tset_variable = { name = modeu5_building_cost_modifier value = 1 }",
        "\tchange_variable = {",
        "\t\tname = modeu5_building_cost_modifier",
        "\t\tdivide = var:modeu5_building_cost_denominator",
        "\t}",
        "\tchange_variable = {",
        "\t\tname = modeu5_building_cost_modifier",
        "\t\tsubtract = 1",
        "\t}",
        "\tif = {",
        "\t\tlimit = { var:modeu5_building_discount_score > 0 }",
        "\t\tadd_country_modifier = {",
        "\t\t\tmodifier = modeu5_balanced_building_cost",
        "\t\t\tsize = var:modeu5_building_cost_modifier",
        "\t\t\tmonths = 2",
        "\t\t\trecalculate_immediately = yes",
        "\t\t\tdesc = modeu5_balanced_building_cost_desc",
        "\t\t}",
        "\t}",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_on_action() -> str:
    return """# Generated by generate_cbp_cbg_building_cost_reconciliation.py.
monthly_country_pulse = {
\tpulse_effect = {
\t\tmodeu5_reconcile_building_cost = yes
\t}
}
"""


def render_localization() -> str:
    return """\ufeffl_english:
 modeu5_balanced_building_cost: \"Balanced Building Investment\"
 modeu5_balanced_building_cost_desc: \"The combined building-cost benefits from laws, government reforms and estate privileges are reconciled with diminishing returns.\"
"""


def build(args: argparse.Namespace) -> dict[str, object]:
    common = args.game_root / "in_game/common"
    transformations: list[dict[str, object]] = []
    contributions: list[Contribution] = []
    owned_outputs: list[str] = []

    for kind in KINDS:
        source_dir = common / kind.directory
        if not source_dir.is_dir():
            continue
        for source in sorted(source_dir.glob("*.txt")):
            lines = source.read_text(encoding="utf-8-sig").splitlines()
            for object_key, start, end in top_level_objects(lines):
                replacement, contribution = comment_discount_lines(lines[start : end + 1])
                if contribution <= 0:
                    continue
                relative = f"in_game/common/{kind.directory}/{source.name}"
                transformations.append({
                    "file": relative,
                    "object": object_key,
                    "field": "__object__",
                    "operation": "replace_object",
                    "value": replacement,
                    "provenance": "preserve",
                })
                contributions.append(Contribution(kind, object_key, contribution, relative))
                if relative not in owned_outputs:
                    owned_outputs.append(relative)

    package = args.package_root
    runtime_files = {
        package / "main_menu/common/static_modifiers/modeu5_building_cost_reconciliation.txt": render_static_modifier(),
        package / "in_game/common/scripted_effects/modeu5_building_cost_reconciliation.txt": render_effect(contributions, args.factor),
        package / "in_game/common/on_actions/modeu5_building_cost_reconciliation.txt": render_on_action(),
        package / "main_menu/localization/english/modeu5_building_cost_reconciliation_l_english.yml": render_localization(),
    }
    for path, content in runtime_files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    manifest_path = package / "cbp_generated/building_cost_reconciliation_sources.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({
        "factor": args.factor,
        "formula": "1 / (1 + factor * sum(contributions)) - 1",
        "sources": [
            {
                "category": item.kind.directory,
                "object": item.object_key,
                "vanilla_discount": item.value,
                "file": item.file,
            }
            for item in contributions
        ],
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return {
        "schema_version": 1,
        "mod_id": "cbp-building-cost-reconciliation",
        "business_rule": "Replace additive law/reform/privilege building discounts with one diminishing-return modifier.",
        "transformations": transformations,
        "scope_contract": {
            "owned_outputs": owned_outputs,
            "phase": "building-cost-reconciliation",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--package-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--factor", type=float, default=1.5)
    args = parser.parse_args()
    if args.factor < 0:
        raise SystemExit("factor must be non-negative")
    payload = build(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Generated {args.output} with {len(payload['transformations'])} reconciled objects.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
