#!/usr/bin/env python3
"""Export CBG selected-object rules that set RGO expansion prices to a fixed value."""

from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import ASSIGNMENT, display_path, field_matches, scan_objects
from tools.cbg.adapters.cbp.generate_cbp_cbg_rgo_prices_spec import (
    OUTPUT,
    SOURCE,
    TARGETS,
    compact,
)


def build_spec(game_root: Path, fixed_price: Decimal) -> dict[str, object]:
    if fixed_price <= 0:
        raise ValueError("Fixed RGO expansion price must be greater than zero")

    rendered_price = compact(fixed_price, 10)
    header = [
        "# Generated by tools/generate_us09_economy_overrides.sh.",
        "# Do not edit manually.",
        "# Source: <EU5_GAME_COMMON_DIR>/prices/00_hardcoded.txt",
        f"# Fixed RGO expansion gold price: {rendered_price}",
    ]

    lines = (game_root / SOURCE).read_text(encoding="utf-8-sig").splitlines(keepends=True)
    objects = {obj.path: obj for obj in scan_objects(lines)}
    for name in TARGETS:
        if (name,) not in objects:
            raise ValueError(f"Missing RGO expansion price object: {name}")
        matches = field_matches(lines, objects[(name,)], "gold")
        if len(matches) != 1 or not ASSIGNMENT.match(lines[matches[0]].rstrip("\r\n")):
            raise ValueError(f"Expected one numeric gold field in {name}")

    return {
        "schema_version": 1,
        "mod_id": "cbp-us09-fixed-rgo-prices",
        "business_rule": f"Set RGO expansion prices to the configured fixed value {rendered_price}.",
        "transformations": [
            {
                "file": SOURCE,
                "output_file": OUTPUT,
                "render_mode": "replace_objects",
                "header": header,
                "trailing_blank_lines": 0,
                "object": name,
                "field": "gold",
                "operation": "replace",
                "value": rendered_price,
                "provenance": "preserve",
            }
            for name in TARGETS
        ],
        "scope_contract": {
            "owned_outputs": [OUTPUT],
            "phase": "rgo-prices",
            "packaging": "CBP-prefixed REPLACE entries preserve unrelated Vanilla prices",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--price", type=Decimal, default=Decimal("60"))
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(build_spec(args.game_root, args.price), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        f"Generated {display_path(args.output)} with fixed RGO expansion price {compact(args.price, 10)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
