#!/usr/bin/env python3
"""Export CBG rules for the dedicated CBP location static-modifier output."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import display_path


SOURCE = "main_menu/common/static_modifiers/location.txt"
OUTPUT = "main_menu/common/static_modifiers/cbp_location.txt"
HEADER = [
    "# Generated by tools/generate_cbp_location_overrides.sh.",
    "# Source: <EU5_INSTALL_DIR>/game/main_menu/common/static_modifiers/location.txt",
    "# Vanilla blocks are preserved; only the annotated assignment in each block is changed.",
]


def build_spec() -> dict[str, object]:
    targets = [
        ("expensive_food_in_location", "local_population_growth", os.environ.get("CBP_EXPENSIVE_FOOD_POPULATION_GROWTH", "0")),
        ("cheap_food_in_location", "local_population_growth", os.environ.get("CBP_CHEAP_FOOD_POPULATION_GROWTH", "0.001")),
        ("market_center", "maximum_stockpile_capacity", os.environ.get("CBP_MARKET_CENTER_STOCKPILE_CAPACITY", "0")),
        ("surplus_jobs", "local_migration_attraction", os.environ.get("CBP_SURPLUS_JOBS_MIGRATION_ATTRACTION", "0.2")),
    ]
    return {
        "schema_version": 1,
        "mod_id": "cbp-location-static-modifiers",
        "business_rule": "Apply CBP food-growth, market-center stockpile, and surplus-jobs location policies.",
        "transformations": [
            {
                "file": SOURCE,
                "output_file": OUTPUT,
                "render_mode": "selected_objects",
                "header": HEADER,
                "object": object_name,
                "field": field,
                "operation": "replace",
                "value": value,
                "provenance": "vanilla_value",
            }
            for object_name, field, value in targets
        ],
        "scope_contract": {"owned_outputs": [OUTPUT], "phase": "location-static-modifiers"},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(build_spec(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Generated {display_path(args.output)} with CBP location CBG policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
