#!/usr/bin/env python3
"""Reconcile stackable building-cost discounts from laws, reforms and privileges.

Vanilla modifiers remain active and visible. The generated runtime applies one
additional visible country modifier equal to the delta between the vanilla
additive result and the target diminishing-return result.

    D = sum(vanilla discount contributions)
    target = 1 / (1 + factor * D) - 1
    reconciliation = target - (-D) = target + D
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path

ASSIGNMENT = re.compile(
    r"^\s*local_build_buildings_cost\s*=\s*"
    r"(?P<value>-(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+))\s*(?:#.*)?$"
)
OBJECT_START = re.compile(r"^\s*(?P<key>[a-zA-Z0-9_]+)\s*=\s*\{")


@dataclass(frozen=True)
class SourceKind:
    directory: str
    trigger: str
    prefix: str


KINDS = (
    SourceKind("laws", "has_law", "law"),
    SourceKind("government_reforms", "has_government_reform", "government_reform"),
    SourceKind("estate_privileges", "has_estate_privilege", "estate_privilege"),
)


@dataclass(frozen=True)
class Contribution:
    kind: SourceKind
    object_key: str
    value: float
    file: str


def top_level_objects(lines: list[str]) -> list[tuple[str, int, int]]:
    result: list[tuple[str, int, int]] = []
    depth = 0
    current_key: str | None = None
    current_start = -1
    for index, line in enumerate(lines):
        code = line.split("#", 1)[0]
        if depth == 0:
            match = OBJECT_START.match(code)
            if match:
                current_key = match.group("key")
                current_start = index
        depth += code.count("{") - code.count("}")
        if current_key is not None and depth == 0:
            result.append((current_key, current_start, index))
            current_key = None
            current_start = -1
    return result


def discount_contribution(block: list[str]) -> float:
    contribution = 0.0
    for line in block:
        match = ASSIGNMENT.match(line)
        if match:
            contribution += -float(match.group("value"))
    return contribution


def render_static_modifier() -> str:
    return """# Generated by generate_cbp_cbg_building_cost_reconciliation.py.
modeu5_building_cost_reconciliation = {
\tgame_data = {
\t\tcategory = country
\t}
\tlocal_build_buildings_cost = 1
}
"""


def render_effect(contributions: list[Contribution], factor: float) -> str:
    lines = [
        "# Generated by generate_cbp_cbg_building_cost_reconciliation.py.",
        "modeu5_reconcile_building_cost = {",
        "\tremove_country_modifier = modeu5_building_cost_reconciliation",
        "\tset_variable = { name = modeu5_vanilla_building_discount value = 0 }",
    ]
    for item in contributions:
        lines.extend([
            "\tif = {",
            "\t\tlimit = {",
            f"\t\t\t{item.kind.trigger} = {item.kind.prefix}:{item.object_key}",
            "\t\t}",
            "\t\tchange_variable = {",
            "\t\t\tname = modeu5_vanilla_building_discount",
            f"\t\t\tadd = {item.value:.12g}",
            "\t\t}",
            "\t}",
        ])
    lines.extend([
        "\tset_variable = { name = modeu5_building_cost_denominator value = 1 }",
        "\tset_variable = { name = modeu5_amplified_building_discount value = var:modeu5_vanilla_building_discount }",
        "\tchange_variable = {",
        "\t\tname = modeu5_amplified_building_discount",
        f"\t\tmultiply = {factor:.12g}",
        "\t}",
        "\tchange_variable = {",
        "\t\tname = modeu5_building_cost_denominator",
        "\t\tadd = var:modeu5_amplified_building_discount",
        "\t}",
        "\tset_variable = { name = modeu5_target_building_cost_modifier value = 1 }",
        "\tchange_variable = {",
        "\t\tname = modeu5_target_building_cost_modifier",
        "\t\tdivide = var:modeu5_building_cost_denominator",
        "\t}",
        "\tchange_variable = {",
        "\t\tname = modeu5_target_building_cost_modifier",
        "\t\tsubtract = 1",
        "\t}",
        "\tset_variable = { name = modeu5_building_cost_reconciliation value = var:modeu5_target_building_cost_modifier }",
        "\tchange_variable = {",
        "\t\tname = modeu5_building_cost_reconciliation",
        "\t\tadd = var:modeu5_vanilla_building_discount",
        "\t}",
        "\tif = {",
        "\t\tlimit = { var:modeu5_vanilla_building_discount > 0 }",
        "\t\tadd_country_modifier = {",
        "\t\t\tmodifier = modeu5_building_cost_reconciliation",
        "\t\t\tsize = var:modeu5_building_cost_reconciliation",
        "\t\t\tmonths = 2",
        "\t\t\trecalculate_immediately = yes",
        "\t\t\tdesc = modeu5_building_cost_reconciliation_desc",
        "\t\t}",
        "\t}",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_on_action() -> str:
    return """# Generated by generate_cbp_cbg_building_cost_reconciliation.py.
monthly_country_pulse = {
\tpulse_effect = {
\t\tmodeu5_reconcile_building_cost = yes
\t}
}
"""


def render_localization() -> str:
    return """\ufeffl_english:
 modeu5_building_cost_reconciliation: \"Building Cost Reconciliation\"
 modeu5_building_cost_reconciliation_desc: \"Adjustment applied on top of the visible Vanilla law, government reform and estate privilege bonuses so their combined effect follows diminishing returns.\"
"""


def build(args: argparse.Namespace) -> dict[str, object]:
    common = args.game_root / "in_game/common"
    contributions: list[Contribution] = []

    for kind in KINDS:
        source_dir = common / kind.directory
        if not source_dir.is_dir():
            continue
        for source in sorted(source_dir.glob("*.txt")):
            lines = source.read_text(encoding="utf-8-sig").splitlines()
            for object_key, start, end in top_level_objects(lines):
                contribution = discount_contribution(lines[start : end + 1])
                if contribution > 0:
                    contributions.append(Contribution(
                        kind,
                        object_key,
                        contribution,
                        f"in_game/common/{kind.directory}/{source.name}",
                    ))

    package = args.package_root
    runtime_files = {
        package / "main_menu/common/static_modifiers/modeu5_building_cost_reconciliation.txt": render_static_modifier(),
        package / "in_game/common/scripted_effects/modeu5_building_cost_reconciliation.txt": render_effect(contributions, args.factor),
        package / "in_game/common/on_actions/modeu5_building_cost_reconciliation.txt": render_on_action(),
        package / "main_menu/localization/english/modeu5_building_cost_reconciliation_l_english.yml": render_localization(),
    }
    for path, content in runtime_files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    manifest_path = package / "cbp_generated/building_cost_reconciliation_sources.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({
        "factor": args.factor,
        "target_formula": "1 / (1 + factor * D) - 1",
        "reconciliation_formula": "target_modifier + D",
        "vanilla_values_preserved": True,
        "sources": [
            {
                "category": item.kind.directory,
                "object": item.object_key,
                "vanilla_discount": item.value,
                "file": item.file,
            }
            for item in contributions
        ],
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return {
        "schema_version": 1,
        "mod_id": "cbp-building-cost-reconciliation",
        "business_rule": "Preserve visible Vanilla discounts and apply one signed reconciliation delta.",
        "transformations": [],
        "scope_contract": {
            "owned_outputs": [],
            "phase": "building-cost-reconciliation",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--package-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--factor", type=float, default=1.5)
    args = parser.parse_args()
    if args.factor < 0:
        raise SystemExit("factor must be non-negative")
    payload = build(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print("Generated visible building-cost reconciliation runtime.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
