#!/usr/bin/env python3
"""Export CBG rules for the dedicated CBP location static-modifier output."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.cbg.community_balance_generator import display_path


SOURCE = "main_menu/common/static_modifiers/location.txt"
OUTPUT = "main_menu/common/static_modifiers/cbp_location.txt"
EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY = os.environ.get(
    "CBP_EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY",
    "5",
)
HEADER = [
    "# Generated by tools/generate_cbp_location_overrides.sh.",
    "# Source: <EU5_INSTALL_DIR>/game/main_menu/common/static_modifiers/location.txt",
    "# Vanilla blocks are preserved; only objects with effective CBP changes are included.",
    "# Each emitted static modifier is an explicit REPLACE database entry.",
]

ReplacementTarget = tuple[str, str, str]
ObjectRange = tuple[int, int]


def warn(message: str) -> None:
    prefix = "[⚠️]"
    if "NO_COLOR" not in os.environ and sys.stderr.isatty():
        prefix = f"\033[1;33m{prefix}\033[0m"
    print(f"{prefix} {message}", file=sys.stderr)


def vanilla_link(source: Path, line_number: int | None = None) -> str:
    link = source.expanduser().resolve().as_uri()
    return f"{link}#L{line_number}" if line_number is not None else link


def numerically_equal(left: str, right: str) -> bool:
    try:
        return Decimal(left) == Decimal(right)
    except InvalidOperation:
        return left == right


def source_from_environment() -> Path | None:
    explicit = os.environ.get("EU5_GAME_LOCATION_STATIC_MODIFIERS_FILE")
    if explicit:
        return Path(explicit).expanduser().resolve()
    common = os.environ.get("EU5_GAME_COMMON_DIR")
    if not common:
        return None
    game_root = Path(common).expanduser().resolve().parent.parent
    return game_root / SOURCE


def scan_object_ranges(
    lines: list[str],
    target_names: set[str],
) -> dict[str, ObjectRange]:
    ranges: dict[str, ObjectRange] = {}
    index = 0
    while index < len(lines):
        match = re.match(r"^([A-Za-z0-9_]+)\s*=\s*\{", lines[index])
        if not match:
            index += 1
            continue
        name = match.group(1)
        depth = lines[index].count("{") - lines[index].count("}")
        end = index
        while depth > 0:
            end += 1
            if end >= len(lines):
                raise SystemExit(f"Unclosed top-level block: {name}")
            code = lines[end].split("#", 1)[0]
            depth += code.count("{") - code.count("}")
        if name in target_names:
            if name in ranges:
                raise SystemExit(
                    f"Vanilla static modifier block is defined more than once: {name}"
                )
            ranges[name] = (index, end)
        index = end + 1
    return ranges


def scalar_assignment(
    lines: list[str],
    object_name: str,
    object_range: ObjectRange,
    field: str,
) -> tuple[int, str] | None:
    assignment = re.compile(
        rf"^\s*{re.escape(field)}\s*=\s*"
        rf"(?P<value>[^#\s]+)(?:\s*(?:#.*)?)$"
    )
    start, end = object_range
    matches: list[tuple[int, re.Match[str]]] = []
    for line_index in range(start, end + 1):
        match = assignment.match(lines[line_index])
        if match:
            matches.append((line_index, match))
    if not matches:
        return None
    if len(matches) > 1:
        raise SystemExit(f"Vanilla {object_name}.{field} is defined more than once")
    line_index, match = matches[0]
    return line_index, match.group("value")


def inspect_source(
    source: Path,
    replacement_targets: list[ReplacementTarget],
) -> tuple[list[ReplacementTarget], bool]:
    if not source.is_file():
        raise SystemExit(f"Vanilla location static modifiers file is missing: {source}")

    lines = source.read_text(encoding="utf-8-sig").splitlines()
    target_names = {object_name for object_name, _field, _value in replacement_targets}
    target_names.add("development")
    ranges = scan_object_ranges(lines, target_names)

    active_replacements: list[ReplacementTarget] = []
    for object_name, field, replacement in replacement_targets:
        object_range = ranges.get(object_name)
        if object_range is None:
            raise SystemExit(f"Missing Vanilla static modifier block: {object_name}")
        assignment = scalar_assignment(lines, object_name, object_range, field)
        if assignment is None:
            raise SystemExit(f"Missing Vanilla field: {object_name}.{field}")
        _line_index, current_value = assignment
        if not numerically_equal(current_value, replacement):
            active_replacements.append((object_name, field, replacement))

    development_range = ranges.get("development")
    if development_range is None:
        warn(
            "Vanilla development static modifier is not exposed by this EU5 version; "
            "skipping its stockpile-capacity transformation. "
            f"Review Vanilla source: {vanilla_link(source)}"
        )
        return active_replacements, False

    development_assignment = scalar_assignment(
        lines,
        "development",
        development_range,
        "maximum_stockpile_capacity",
    )
    if development_assignment is None:
        warn(
            "Vanilla development.maximum_stockpile_capacity is not exposed by this "
            "EU5 version; skipping this location transformation. "
            f"Review Vanilla source: {vanilla_link(source)}"
        )
        return active_replacements, False

    line_index, current_value = development_assignment
    if not numerically_equal(
        current_value,
        EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY,
    ):
        warn(
            "Vanilla value changed: development.maximum_stockpile_capacity was "
            f"reviewed at {EXPECTED_DEVELOPMENT_STOCKPILE_CAPACITY} and is now "
            f"{current_value}. CBP will continue and comment the current value. "
            f"Review Vanilla source: {vanilla_link(source, line_index + 1)}"
        )
    return active_replacements, True


def configured_replacement_targets() -> list[ReplacementTarget]:
    return [
        (
            "expensive_food_in_location",
            "local_population_growth",
            os.environ.get("CBP_EXPENSIVE_FOOD_POPULATION_GROWTH", "0"),
        ),
        (
            "cheap_food_in_location",
            "local_population_growth",
            os.environ.get("CBP_CHEAP_FOOD_POPULATION_GROWTH", "0.001"),
        ),
        (
            "market_center",
            "maximum_stockpile_capacity",
            os.environ.get("CBP_MARKET_CENTER_STOCKPILE_CAPACITY", "0"),
        ),
        (
            "surplus_jobs",
            "local_migration_attraction",
            os.environ.get("CBP_SURPLUS_JOBS_MIGRATION_ATTRACTION", "0.2"),
        ),
    ]


def build_spec(source_file: Path | None = None) -> dict[str, object]:
    replacement_targets = configured_replacement_targets()
    development_available = True
    if source_file is not None:
        replacement_targets, development_available = inspect_source(
            source_file,
            replacement_targets,
        )

    transformations = [
        {
            "file": SOURCE,
            "output_file": OUTPUT,
            "render_mode": "replace_objects",
            "header": HEADER,
            "object": object_name,
            "field": field,
            "operation": "replace",
            "value": value,
            "provenance": "vanilla_value",
        }
        for object_name, field, value in replacement_targets
    ]
    if development_available:
        transformations.append(
            {
                "file": SOURCE,
                "output_file": OUTPUT,
                "render_mode": "replace_objects",
                "header": HEADER,
                "object": "development",
                "field": "maximum_stockpile_capacity",
                "operation": "comment_out",
            }
        )
    return {
        "schema_version": 1,
        "mod_id": "cbp-location-static-modifiers",
        "business_rule": (
            "Apply CBP food-growth, market-center stockpile, surplus-jobs, "
            "and development stockpile policies while omitting no-op objects."
        ),
        "transformations": transformations,
        "scope_contract": {
            "owned_outputs": [OUTPUT],
            "phase": "location-static-modifiers",
            "packaging": "cbp-prefixed REPLACE entries for effectively changed objects only",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-file", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    source_file = args.source_file.resolve() if args.source_file else source_from_environment()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(build_spec(source_file), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {display_path(args.output)} with CBP location CBG policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
